### ISSUE TITLE
[TASK] Deprecate ext:fluid fillDefaultsByPackageName()

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1003]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/fb443fd15541d2ec1456788698684052ada7b0a7)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[TASK] Deprecate ext:fluid fillDefaultsByPackageName()

TemplatePaths->fillDefaultsByPackageName() is located
at the wrong place by having this magic within ext:fluid:
It is the last piece of ext:fluid core (non-VH) classes
that mixes extbase logic into fluid.

The method is only triggered actively by extbase, and
indirectly via parent __construct() in standalone fluid
if the class is constructed with a string, which is not
used by the core.

The patch refactors the single consumer in extbase
ActionController, which leads to simplified fluid path
setup in that class. Two obsolete heavy mocking tests
that don't add value bite the dust along the way.

Even though ext:fluid TemplatePaths is marked @internal,
the method is not removed directly but deprecated since
it is used by quite a few extensions in practice, and
it does not harm much to just let it log deprecation
note in v13.

Resolves: #104764
Releases: main
Change-Id: Ia2fbcb38a6ef76f6aad41fcda927e3f32447ca9d
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85813
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Simon Praetorius <simon@praetorius.me>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Deprecation-104764-FluidTemplatePaths-fillDefaultsByPackageName.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-104764-1724851918:

=====================================================================
Deprecation: #104764 - Fluid TemplatePaths->fillDefaultsByPackageName
=====================================================================

See :issue:`104764`

Description
===========

Method :php:`TYPO3\CMS\Fluid\View\TemplatePaths->fillDefaultsByPackageName()`
has been marked as deprecated in TYPO3 v13 and will be removed in TYPO3 v14.

Fluid template paths should be set directly using the methods
:php:`setTemplateRootPaths()`, :php:`setLayoutRootPaths()` and
:php:`setPartialRootPaths()`, or - even better - be handled by
:php:`ViewFactoryInterface`, which comes as new feature in TYPO3 v13.


Impact
======

Calling :php:`fillDefaultsByPackageName()` triggers a deprecation level
log level entry in TYPO3 v13 and will be removed in TYPO3 v14.


Affected installations
======================

The method is relatively rarely used by extensions directly, a usage in
extbase :php:`ActionController` has been refactored away. The extension
scanner will find candidates.

Note class :php:`TemplatePaths` is marked `@internal` and should not be
used by extensions at all.

Migration
=========

Use :php:`TYPO3\CMS\Core\View\ViewFactoryInterface` to create views with
proper template paths instead. The TYPO3 core extensions come with plenty
of examples on how to do this.

.. index:: PHP-API, FullyScanned, ext:fluid

```

</details>

**Comment by linawolf** [comment]
We did not mention the method in the docs
