### ISSUE TITLE
[TASK] Deprecate instantiation of IconRegistry in ext_localconf.php

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1007]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/2b5a88a3bba6e599bfe556a33d47986c2b99e105)
:busts_in_silhouette: Authored by Nikita Hovratov nikita.h@live.de
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[TASK] Deprecate instantiation of IconRegistry in ext_localconf.php

Nowadays, it is not needed anymore to manually call IconRegistry
to register icons. Since TYPO3 v11 we have the Configuration/Icons.php
file, which should be enough for most use cases.

This deprecation gives extension authors incentive to clean their
ext_localconf.php files.

Some background: This has become problematic with Content Blocks, as
it uses service provider extension method to dynamically register icons.
However, when other extensions instantiate IconRegistry in
ext_localconf.php the WHOLE Content Blocks compiling is triggered at an
early stage of bootstrapping, when TCA is not even available yet. This
does not work and forces us to use a less clean method by listening to
the BootstrapComplete event.

Resolves: #104778
Related: #94692
Releases: main
Change-Id: I8ee6d80e8979f506cd076236c577302e323af77a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85662
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Simon Praetorius <simon@praetorius.me>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Torben Hansen <derhansen@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Torben Hansen <derhansen@gmail.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Deprecation-104778-InstantiationOfIconRegistryInExtLocalconf.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-104778-1724953249:

=========================================================================
Deprecation: #104778 - Instantiation of IconRegistry in ext_localconf.php
=========================================================================

See :issue:`104778`

Description
===========

Since TYPO3 v11 it is possible to automatically register own icons via
`Configuration/Icons.php`. Prior to this, extension authors used to register
icons manually via instantiating the IconRegistry in their ext_localconf.php
files. This method has now been deprecated. It is recommended to switch to
the newer method introduced with :issue:`94692`.

Impact
======

Instantiating :php:`\TYPO3\CMS\Core\Imaging\IconRegistry` inside
ext_localconf.php files will trigger a deprecation-level log entry.

Affected installations
======================

All installations, which instantiate :php:`\TYPO3\CMS\Core\Imaging\IconRegistry`
before the :php:`\TYPO3\CMS\Core\Core\Event\BootCompletedEvent`. This includes
`ext_localconf.php` files as well as `TCA/Overrides`.

Migration
=========

The most common use-cases can be accomplished via the `Configuration/Icons.php`
file.

Before:

..  code-block:: php
    :caption: EXT:example/ext_localconf.php

    <?php

    $iconRegistry = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
      \TYPO3\CMS\Core\Imaging\IconRegistry::class,
    );
    $iconRegistry->registerIcon(
        'example',
        \TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class,
        [
            'source' => 'EXT:example/Resources/Public/Icons/example.svg'
        ],
    );

After:

..  code-block:: php
    :caption: EXT:example/Configuration/Icons.php

    <?php

    return [
        'example' => [
            'provider' => \TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class,
            'source' => 'EXT:example/Resources/Public/Icons/example.svg',
        ],
    ];

For more complex tasks, it is recommended to register an event listener for the
:php:`\TYPO3\CMS\Core\Core\Event\BootCompletedEvent`. At this stage the system
is fully booted and you have a completely configured IconRegistry at hand.

In case the registry was used in `TCA/Overrides` files to retrieve icon
identifiers, then this should be replaced completely with static identifiers.
The reason behind this is, that the registry isn't even fully usable at this
stage. TCA isn't fully built yet and icons can still be registered at a later
point.

.. index:: PHP-API, NotScanned, ext:core

```

</details>

**Comment by linawolf** [comment]
We only mention the old way in migration sections
