### ISSUE TITLE
[FEATURE] Add console command to mark upgrade wizards as undone

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1010]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/b99439613cc2ca553c3be17eedd690b981ca9233)
:busts_in_silhouette: Authored by Till Hörner thoerner@3pc.de
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] Add console command to mark upgrade wizards as undone

A new CLI command `typo3 upgrade:mark:undone` has been introduced
that allows to mark a previously executed upgrade wizard as undone
so it can be run again. This makes the existing functionality
from the install tool also available on CLI.

Resolves: #104655
Releases: main
Change-Id: I0d4601e3e81b447793586ddfc31e10bd40a87e64
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85672
Tested-by: core-ci <typo3@b13.com>
Tested-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Feature-104655-AddConsoleCommandToMarkUpgradeWizardsAsUndone.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-104655-1724859386:

========================================================================
Feature: #104655 - Add console command to mark upgrade wizards as undone
========================================================================

See :issue:`104655`

Description
===========

A new CLI command :bash:`typo3 upgrade:mark:undone` has been
introduced. It allows to mark a previously executed upgrade wizard as "undone",
so it can be run again.

This makes the existing functionality from the install tool also available on
CLI.

..  note::

    Bear in mind that wizards theoretically can cause data inconsistencies when
    being run again. Also, a wizard may not run properly again when its
    pre-requisites no longer apply after its first run.

Impact
======

You can now mark an already executed upgrade wizard as "undone" with
:bash:`typo3 upgrade:markUndone <wizardIdentifier>`

.. index:: CLI, ext:install

```

</details>

**Comment by Alagts** [comment]
I will close this issue since we already documented this in [our list of TYPO3 commands](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/CommandControllers/ListCommands.html#console-command-upgrade-mark-undone).
