### ISSUE TITLE
[FEATURE] Add file embedding option to asset viewhelpers

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1021]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f344429f937f408072e78ff2691e7c19d3143768)
:busts_in_silhouette: Authored by André Buchmann andy.schliesser@gmail.com
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[FEATURE] Add file embedding option to asset viewhelpers

The viewhelpers f:asset.css and f:asset.script are great but
missed an option to render referenced files inline.

A boolean option "inline" is now added to load the file contents
as inline styles or scripts. This is especially useful for
content elements which are used first in a page and need
some custom css to improve the Cumulative Layout Shift (CLS).

Resolves: #99510
Releases: main
Change-Id: Ic4282cd4a6ff00594a0aa0cbdf51f49d80806489
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84424
Tested-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Simon Praetorius <simon@praetorius.me>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Feature-99510-AddFileEmbeddingOptionToAssetViewhelpers.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99510-1716815124:

================================================================
Feature: #99510 - Add file embedding option to asset viewhelpers
================================================================

See :issue:`99510`

Description
===========

The ViewHelpers :html:`<f:asset.css>` and :html:`<f:asset.script>` have
been extended with a new argument :html:`inline`. If this argument is set,
the referenced asset file is rendered inline.

Setting the argument will therefore load the file content of the defined
:html:`href` / :html:`src` as inline style or script. This is especially
useful for content elements which are used as first element on a page and
need some custom CSS to improve the Cumulative Layout Shift (CLS).

Impact
======

To add inline styles and scripts from a referenced file, the new :html:`inline`
argument can be set. For example, to add above-the-fold styles, the
:html:`priority` option can be set, which will put the file contents of
:file:`EXT:sitepackage/Resources/Public/Css/my-hero.css` as inline styles
to the :html:`<head>` section.

.. code-block:: html

    <f:asset.css identifier="my-hero" href="EXT:sitepackage/Resources/Public/Css/my-hero.css" inline="1" priority="1"/>

To add JavaScript:

.. code-block:: html

    <f:asset.script identifier="my-hero" src="EXT:sitepackage/Resources/Public/Js/my-hero.js" inline="1" priority="1"/>

.. index:: Fluid, Frontend, ext:fluid

```

</details>

**Comment by linawolf** [comment]
Will be automatically documented in the viewhelper reference
