### ISSUE TITLE
[FEATURE] Introduce Site Settings Editor

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1026]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/e463366cfbcb77b6ac956a4b329a796f53d07f5e)
:busts_in_silhouette: Authored by Benjamin Franzke ben@bnf.dev
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[FEATURE] Introduce Site Settings Editor

A new Site Settings editor has been introduced that allows to configure
per-site settings in `config/sites/*/settings.yaml`.

The new backend module `Site Management > Settings` provides an overview
of sites which offer configurable settings and makes them editable based
on Site Set provided Settings Definitions.

The editor shows a list of settings categories and respective settings.
It will persist all settings into `config/sites/*/settings.yaml`.
The module will only persist settings that deviate from the site-scoped
default value. That means it will only change the minimal difference to
the settings set defined by the active sets for the respective site.

The backend module is currently available for administrators only, but
will likely be extended to be made available for editors in future.

Anonymous (undefined) site settings – as supported since TYPO3 v10 –
will not be made editable, but will be preserved as-is when persisting
changes through the settings editor.

Resolves: #104794
Releases: main
Change-Id: I7eea8445b86b50efa498238daa3436f0940f4b78
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84342
Tested-by: Benjamin Kott <benjamin.kott@outlook.com>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Reviewed-by: Benjamin Kott <benjamin.kott@outlook.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Feature-104794-IntroduceSiteSettingsEditor.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-104794-1725980585:

=================================================
Feature: #104794 - Introduce Site Settings Editor
=================================================

See :issue:`104794`

Description
===========

A new Site Settings editor has been introduced that allows to configure per-site
settings in file:`config/sites/*/settings.yaml`.

The new backend module :guilabel:`Site Management > Settings`
provides an overview of sites which offer configurable settings and makes
them editable based on
:doc:`Site Set provided Settings Definitions <../13.1/Feature-103437-IntroduceSiteSets>`.

The editor shows a list of settings categories and respective settings. It will
persist all settings into file:`config/sites/*/settings.yaml`. The module will
only persist settings that deviate from the site-scoped default value. That
means it will only change the minimal difference to the settings set defined
by the active sets for the respective site.

The backend module is currently available for administrators only, but will
likely be extended to be made available for editors in future.

Anonymous (undefined) site settings – as supported since TYPO3 v10 –
will not be made editable, but will be preserved as-is when persisting changes
through the settings editor.


Categorization
--------------

Sets can define categories and settings definitions can reference the category
by ID in order to assign a setting to a specific category.
These definitions are placed in :file:`settings.definitions.yaml`
next to the site set file :file:`config.yaml`.

..  code-block:: yaml
    :caption: EXT:my_extension/Configuration/Sets/MySet/settings.definitions.yaml

    categories:
      myCategory:
        label: 'My Category'

    settings:
      my.example.setting:
        label: 'My example setting'
        category: myCategory
        type: string
        default: ''

      my.seoRelevantSetting:
        label: 'My SEO relevant setting'
        # show in EXT:seo provided category "seo"
        category: seo
        type: int
        default: 5

The settings ordering is defined through the loading order of extensions and by
the order of categories. Uncategorized settings will be grouped into a virtual
"Other" category and shown at the end of the list of available settings.


Impact
======

Site-scoped settings will most likely be the place to configure site-wide
configuration, which was previously only possible to modify via Constant Editor,
modifying TypoScript constants.

It is recommended to use site-sets and their UI configuration in favor of
Typoscript Constants in the future.


.. index:: Backend, Frontend, YAML, ext:backend

```

</details>

**Comment by linawolf** [comment]
For system extensions: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86040

**Comment by linawolf** [comment]
This still needs to be documented in the Site package tutorial and getting started

**Comment by linawolf** [comment]
Site package and getting started are still missing
