### ISSUE TITLE
[!!!][TASK] Remove unused MailerAdapterInterface

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#103]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/6f84ff5215822b22295cf0dcbd039021f149f253)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Georg Ringer georg.ringer@gmail.com

## Commit message

[!!!][TASK] Remove unused MailerAdapterInterface

The MailerAdapterInterface, related to SwiftMailer
is removed, since it is unused in core since v7.

Resolves: #97752
Releases: main
Change-Id: Ibb0a97dd17a06cb7b4d43d8d9aa4326194f550f5
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/74860
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-97752-MailerAdapterInterfaceRemoved.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-97752-1654761506

=================================================
Breaking: #97752 - MailerAdapterInterface removed
=================================================

See :issue:`97752`

Description
===========

The :php:`\TYPO3\CMS\Core\Mail\MailerAdapterInterface` has been removed,
since the interface became unused in v7 due to removal of core's
:php:`SwiftMailerAdapter` implementation, which had been used as hook
subscriber in the also removed :php:`MailUtility::mail()` method.

Impact
======

Implementing the interface in custom extension code will trigger
a PHP Error.

Affected installations
======================

All installations implementing the interface in custom extension code,
which is very unlikely. The extenion scanner will report any usage as
strong match.

Migration
=========

Remove any usage of the interface in extension code.

.. index:: PHP-API, FullyScanned, ext:core

```

</details>

**Comment by brotkrueml** [comment]
Searching "MailerAdapterInterface" in docs has no results. So closing this issue.
