### ISSUE TITLE
[TASK] Remove unused fields from tt_content

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1039]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/05209358a2c6a9129edac7d8d6b8f3694f35b8ec)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[TASK] Remove unused fields from tt_content

Since the removal of CSS Styled Content in TYPO3 v8,
the usage for the DB fields in tt_content:

- Menu block title [accessibility_title]
- Add link to bypass navigation block [accessibility_bypass]
- Link text to bypass navigation block [accessibility_bypass_text]

have been unused, and are not needed anymore.

If someone still uses them with CSS Styled Content,
they need to add the fields and the TCA definitions
to their own schema again.

Resolves: #101535
Releases: main
Change-Id: Ia841d700c5cf48eefc43b277edcec2a5ff3dde71
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85933
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Jasmina Ließmann <minapokhalo+typo3@gmail.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Jasmina Ließmann <minapokhalo+typo3@gmail.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Important-101535-UnusedDBFieldsFromTt_contentRemoved.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-101535-1726059919:

=============================================================
Important: #101535 - Unused DB fields from tt_content removed
=============================================================

See :issue:`101535`

Description
===========

The database table `tt_content` contains all necessary fields for rendering
content elements.

Back with TYPO3 v4.7, a major feature to render certain Content Types in a more
accessible way, funded by the German Government (BLE_) with the
"Konjunkturpaket II" was merged into CSS Styled Content.

In this procedure, certain Content Types received new fields and rendering definitions, which
were stored in the database fields "accessibility_title", "accessibility_bypass" and "accessibility_bypass_text".

When CSS Styled Content was removed in favor of Fluid Styled Content in TYPO3 v8, the DB
fields continued to exist in TYPO3 Core, so a migration from CSS Styled Content was possible.

However, the DB fields are not evaluated anymore since then, and are removed, along with
their TCA definition in "tt_content".

If these fields are still relevant for a custom legacy installation, these DB fields need to be
re-created via TCA for further use in a third-party extension.

.. _BLE: https://typo3.org/article/typo3-receives-german-governmental-funding-for-accessibility-and-usability-project

.. index:: Database, PHP-API, ext:frontend

```

</details>

**Comment by linawolf** [comment]
No need to document
