### ISSUE TITLE
[FEATURE] Introduce `lint:yaml` command

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1046]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/54a6262dc7cd520a06d737cc033d10e5c28475b3)
:busts_in_silhouette: Authored by Stefan Bürk stefan@buerk.tech
:heavy_check_mark: Merged by Anja Leichsenring aleichsenring@ab-softlab.de

## Commit message

[FEATURE] Introduce `lint:yaml` command

The `symfony/yaml` package is a hard dependency of the
TYPO3 Core and ships a dedicated `yaml-lint` binary as
entry point for the shipped `LintCommand` class.

Most TYPO3 integrators and developers are not aware of
that dedicated binary installed along the way and only
know about the TYPO3 binary for command execution. As
the TYPO3 core relies on YAML files and parsing with an
increasing number of implementation and use cases it's
good to have linting of these files in available and easy to reach.

This change adds the `symfony/yaml` linting command to
the TYPO3 binary as feature with corresponding raise
of awareness, albeit being a development and pipeline
support feature only.

The new command can be used from the TYPO3 binary with:

  bin/typo3 lint:yaml
  bin/typo3 lint:yaml --help

directly in composer and non-composer installations.

Resolves: #104973
Releases: main
Change-Id: Ic65da691d34dccec2b292a946f59985ceadaf780
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84438
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Guido Schmechel <guido.schmechel@brandung.de>
Tested-by: Guido Schmechel <guido.schmechel@brandung.de>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Feature-104973-ActivateLintYamlExecutableForTYPO3.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-104973-1726393875:

=====================================================================
Feature: #104973 - Activate the shipped LintYaml executable for TYPO3
=====================================================================

See :issue:`104973`

Description
===========

The `typo3` executable received a new command `lint:yaml` to ease and encourage linting of yaml files before deploying to production and therefor avoid failures.

Usage as follows:

.. code-block:: bash

    bin/typo3 lint:yaml
    bin/typo3 lint:yaml --help

The `help` argument will list possible usage elements.


Impact
======

Integrate easy made linting of yaml files from core, custom extensions or
any other source into your quality assurance workflow in the known format of the typo3 executable.

.. index:: CLI, YAML

```

</details>

**Comment by Alagts** [comment]
I will close the issue because in our [list of TYPO3 commands](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/CommandControllers/ListCommands.html#console-command-lint-yaml) we already documented this command.
