### ISSUE TITLE
[DOCS] Add readonly site settings to changelog entry

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1047]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/3cd724d7035f5e4909cc6be2f73d5073b2fdc39e)
:busts_in_silhouette: Authored by Lina Wolf 112@linawolf.de
:heavy_check_mark: Merged by Garvin Hicking gh@faktor-e.de

## Commit message

[DOCS] Add readonly site settings to changelog entry

With https://review.typo3.org/c/Packages/TYPO3.CMS/+/86028 readonly
site setting definitions were introduced but not mentioned in
any changelog entry.

Resolves: #104993
Releases: main
Change-Id: I563f953ca3e10da32201d0f8c1b4164944052402
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86124
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>13.3/Feature-104794-IntroduceSiteSettingsEditor.rst</summary>

```diff
@@ -66,6 +66,23 @@ The settings ordering is defined through the loading order of extensions and by
 the order of categories. Uncategorized settings will be grouped into a virtual
 "Other" category and shown at the end of the list of available settings.
 
+Readonly
+--------
+
+Site settings can be made readonly. They can be overridden only by editing
+the :file:`config/sites/my-site/settings.yaml` but not from within the editor.
+
+The value of the field is displayed in a readonly field in the settings editor.
+
+..  code-block:: yaml
+    :caption: EXT:my_extension/Configuration/Sets/MySet/settings.definitions.yaml
+
+    settings:
+      my.readonlySetting:
+        label: 'My readonly setting'
+        type: int
+        default: 5
+        readonly: true
 
 Impact
 ======
```

</details>

**Comment by linawolf** [comment]
Already documented
