### ISSUE TITLE
[FEATURE] New TCA type "country"

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1052]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ad813a0d73a9f23c4934c55f1274b949cafba089)
:busts_in_silhouette: Authored by Georg Ringer georg.ringer@gmail.com
:heavy_check_mark: Merged by Garvin Hicking gh@faktor-e.de

## Commit message

[FEATURE] New TCA type "country"

The TCA type "country" utilizes the country API provided
with #99618 to give integrators a simple way to implement
a country selection.

Resolves: #99911
Related: #99618
Releases: main
Change-Id: Ifee9dcea1114f8522f2884afb4d2dec3100e1a49
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77792
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Feature-99911-NewTCATypeCountry.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99911-1675976882:

========================================
Feature: #99911 - New TCA type "country"
========================================

See :issue:`99911`

Description
===========

A new TCA field type called :php:`country` has been added to TYPO3 Core. Its main
purpose is to use the newly introduced Country API to provide a country selection in the backend.

The new TCA type displays all filtered countries including the configurable name and the corresponding flag.

.. code-block:: php

    'country' => [
        'label' => 'Country',
        'config' => [
            'type' => 'country',
            // available options: name, localizedName, officialName, localizedOfficialName, iso2, iso3
            'labelField' => 'localizedName',
            // countries which are listed before all others
            'prioritizedCountries' => ['AT', 'CH'],
            // sort by the label
            'sortItems' => [
                'label' => 'asc'
            ],
            'filter' => [
                // restrict to the given country ISO2 or ISO3 codes
                'onlyCountries' => ['DE', 'AT', 'CH', 'FR', 'IT', 'HU', 'US', 'GR', 'ES'],
                // exclude by the given country ISO2 or ISO3 codes
                'excludeCountries' => ['DE', 'ES'],
            ],
            'items' => [
                ['label' => '', 'value' => ''],
            ],
            'default' => 'HU',
        ],
    ],

.. index:: Backend, TCA, ext:core

```

</details>

**Comment by linawolf** [comment]
See https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1053
