### ISSUE TITLE
[DOCS] Use correct command name upgrade:mark:undone in changelog

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1057]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/df5fd788639249c19b3de3d26154c0b039c23b70)
:busts_in_silhouette: Authored by Till Hörner thoerner@3pc.de
:heavy_check_mark: Merged by Garvin Hicking gh@faktor-e.de

## Commit message

[DOCS] Use correct command name upgrade:mark:undone in changelog

Resolves: #105080
Related: #104655
Releases: main
Change-Id: I3de2f92440c21da7e30f4ac8954deaaf567395e4
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86255
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Lina Wolf <112@linawolf.de>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Lina Wolf <112@linawolf.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>13.3/Feature-104655-AddConsoleCommandToMarkUpgradeWizardsAsUndone.rst</summary>

```diff
@@ -28,6 +28,6 @@ Impact
 ======
 
 You can now mark an already executed upgrade wizard as "undone" with
-:bash:`typo3 upgrade:markUndone <wizardIdentifier>`
+:bash:`typo3 upgrade:mark:undone <wizardIdentifier>`
 
 .. index:: CLI, ext:install
```

</details>

**Comment by Alagts** [comment]
I will close this issue since we already documented this command in [our list of TYPO3 commands](https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/CommandControllers/ListCommands.html#console-command-upgrade-mark-undone).
