### ISSUE TITLE
[TASK] Replace single quotes by double quotes in annotations

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#106]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/7e0fe3e0ad4ce28c16ad463669eb07fd462a044a)
:busts_in_silhouette: Authored by Julian Hofmann noreply@example.com
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[TASK] Replace single quotes by double quotes in annotations

Doctrine (now?) does not allow values to be surrounded by single quotes.
It expects a `PlainValue` but struggles over the quotes. Replacing the
single quotes with double quotes solves this problem:

`[Syntax Error] Expected PlainValue, got ''' at position ***`

Releases: main, 11.5
Resolves: #97716
Change-Id: I34042f350bcac2d6518f73be9796d39e0bcc64a7
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/74794
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>11.0/Feature-91719-CustomErrorMessagesInRegularExpressionValidator.rst</summary>

```rst
.. include:: /Includes.rst.txt

=====================================================================
Feature: #91719 - Custom error messages in RegularExpressionValidator
=====================================================================

See :issue:`91719`

Description
===========

The :php:`RegularExpressionValidator` can now return a custom validation error message
to help the user providing valid input.


Impact
======

A new option :php:`errorMessage` has been introduced to the validator.

Example:

.. code-block:: php

   class MyModel extends \TYPO3\CMS\Extbase\DomainObject\AbstractEntity
   {
       /**
        * @var string
        * @TYPO3\CMS\Extbase\Annotation\Validate(
        *    "RegularExpression",
        *    options={
        *       "regularExpression": "/^SO[0-9]$/",
        *       "errorMessage": "explain how to provide a valid value"
        *    }
        * )
        */
       protected $customField;
   }

It is also possible to provide a translation key to render a localized message:

.. code-block:: php

   class MyModel extends \TYPO3\CMS\Extbase\DomainObject\AbstractEntity
   {
       /**
        * @var string
        * @TYPO3\CMS\Extbase\Annotation\Validate(
        *    "RegularExpression",
        *    options={
        *       "regularExpression": "/^SO[0-9]$/",
        *       "errorMessage": "LLL:EXT:my_extension/path/to/xlf:translation.key"
        *    }
        * )
        */
       protected $customField;
   }

If no :php:`errorMessage` is provided, the default message will be displayed in case of a validation error.

.. index:: Frontend, ext:extbase

```

</details>

**Comment by sypets** [comment]
Change in changelog only.

`@TYPO3\CMS\Extbase\Annotation\Validate` is [used in some places in the Extbase Book](https://docs.typo3.org/m/typo3/book-extbasefluid/main/en-us/9-CrosscuttingConcerns/2-validating-domain-objects.html#validating-in-the-domain-model-with-annotations), but no single quotes are used.
