### ISSUE TITLE
[TASK] Move FrontendBackendUserAuthentication into EXT:frontend

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1066]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ed37a8e92937d9bc002538cf6436d43b9074b3a0)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[TASK] Move FrontendBackendUserAuthentication into EXT:frontend

Since FrontendBackendUserAuthentication, required for executing
the Frontend request process, has only dependencies to EXT:frontend
and EXT:core it is now moved to EXT:frontend.

Resolves: #105175
Releases: main
Change-Id: Ib04e7d1e7a47b00b32d9c477cb7cdb47238b158e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85901
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.4/Important-105175-MoveFrontendBackendUserAuthenticationIntoEXTfrontend.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-105175-1727799093:

=============================================================================
Important: #105175 - Move FrontendBackendUserAuthentication into EXT:frontend
=============================================================================

See :issue:`105175`

Description
===========

The internal :php:`FrontendBackendUserAuthentication` class, used for frontend
requests while being logged in the backend has been moved from EXT:backend to
EXT:frontend, since its dependencies are limited to EXT:core and EXT:frontend.

While for v13 a class alias mapping and a legacy notation for IDE's is
available, the class is marked as `@internal` and therefore does not fall
under TYPO3's Core API deprecation policy.

.. index:: Frontend, ext:frontend

```

</details>

**Comment by linawolf** [comment]
Not mentioned
