### ISSUE TITLE
[TASK] Replace TYPO3 `EnumType` with doctrine/dbal type

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1078]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/8f2f637d2b0fc5a2691455d0b7ae3ebaa7f1c6bd)
:busts_in_silhouette: Authored by Stefan Bürk stefan@buerk.tech
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[TASK] Replace TYPO3 `EnumType` with doctrine/dbal type

Doctrine DBAL 4.2.0 implemented an `EnumType`. This
conflicts with an existing TYPO3 implementation.

The TYPO3 implementation does not supported DBMS apart
from MariaDB/MySQL. The new DBAL implementation does not
contain a fully working replacement either.

The database analyzer however benefits from the Doctrine
DBAL type and can create compatible fields for database
systems not having native `ENUM` support when replaced.

The patch switches to the new doctrine/dbal implementation.

The patch:

* No longer registers the TYPO3 custom enum type for TYPO3
  managed connections retrieved through the `ConnectionPool`.
* Upgrades to Doctrine DBAL 4.2.1 as minimum version to
  ensure the doctrine/dbal type exists.
* Removes now obsolete code and workarounds at several places
  related to the TYPO3 EnumType.
* Activates EnumType SchemaMigrator tests with all TYPO3
  supported database systems.
* Removes the TYPO3 EnumType class and adds a class alias
  to the doctrine/dbal implementaton for maximum compatibility.

> composer require --no-update -d typo3/sysext/core doctrine/dbal:"^4.2.1"
> composer require --no-update -d typo3/sysext/redirects doctrine/dbal:"^4.2.1"
> composer require --no-update -d typo3/sysext/install doctrine/dbal:"^4.2.1"
> composer require doctrine/dbal:"^4.2.1"

Note TYPO3 13.x composer mode instances before 13.4 should
probably set a conflict to doctrin/dbal:^4.2.x. This situation
resolves itself with the 13.4.0 release in a couple of days.

[1] https://github.com/doctrine/dbal/releases/tag/4.2.0

Resolves: #105279
Releases: main
Change-Id: I14b29d3e8b7e263ba9d4e53eb929bcca265c6551
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86561
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.4/Deprecation-105279-ReplaceTYPO3EnumTypeWithDoctrinedbalEnumType.rst</summary>

```rst
..  include:: /Includes.rst.txt

..  _deprecation-105279-1728669356:

=========================================================================
Deprecation: #105279 - Replace TYPO3 EnumType with doctrine/dbal EnumType
=========================================================================

See :issue:`105279`

Description
===========

TYPO3 provided a custom Doctrine DBAL column type implementation for native
:sql:`ENUM` that was only compatible with MySQL and MariaDB connections.

The Doctrine DBAL Team implemented `ENUM` support with
`Release 4.2.0 <https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md>`__ in
class :php:`\Doctrine\DBAL\Types\EnumType`, only supporting MySQL and MariaDB
as well.

TYPO3 removed its custom implementation with TYPO3 v13.4.0.

Class :php:`\TYPO3\CMS\Core\Database\Schema\Types\EnumType` has been marked as deprecated
and is replaced with an class alias of :php-short:`\Doctrine\DBAL\Types\EnumType`.
The alias will be removed with TYPO3 v14.

See `Release 4.2.0 <https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md>`__

Impact
======

doctrine/dbal >= 4.2.0 is incompatible with TYPO3 versions before v13.4.0.
Composer based instances using TYPO3 v13.3 or older should add an according
conflict to their :file:`composer.json`.

Affected installations
======================

Instances using the the :sql:`ENUM` type directly or by any 3rd party
extension using TYPO3 13.0 to 13.3 in composer mode will break, when
the `doctrine/dbal` composer packages is updated to `4.2.0` or newer.

Migration
=========

Upgrade (directly) to TYPO3 v13.4 or ensure to avoid updating to
Doctrine DBAL 4.2.x or newer versions in composer based instances.

Replace :php:`\TYPO3\CMS\Core\Database\Schema\Types\EnumType` type
declarations with :php:`\Doctrine\DBAL\Types\EnumType`.

..  index:: Database, PHP-API, NotScanned, ext:core

```

</details>

**Comment by linawolf** [comment]
Not mentioned
