### ISSUE TITLE
[FEATURE] Provide default queue for notifications

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#108]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/1039ba36942aa860970607ec670b763636fa906f)
:busts_in_silhouette: Authored by Andreas Fernandez a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[FEATURE] Provide default queue for notifications

To allow dispatching notifications to the user the easy way, a new global
flash message queue, identified by
`TYPO3\CMS\Core\Messaging\FlashMessageQueue::NOTIFICATION_QUEUE`, is
introduced that takes the flash message and renders it as a notification on
the top-right edge of the backend.

Backend modules based on `TYPO3\CMS\Backend\Template\ModuleTemplate`
automatically gain advantage of this feature.

Resolves: #97595
Releases: main
Change-Id: I0e04f0412117649391c0f50fa4249b7832dded69
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/74582
Tested-by: core-ci <typo3@b13.com>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Oliver Bartsch <bo@cedev.de>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Feature-97595-ProvideDefaultQueueForNotifications.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-97595-1652121042

=========================================================
Feature: #97595 - Provide default queue for notifications
=========================================================

See :issue:`97595`

Description
===========

To allow dispatching notifications to the user the easy way, a new global flash
message queue, identified by
:php:`TYPO3\CMS\Core\Messaging\FlashMessageQueue::NOTIFICATION_QUEUE`, is
introduced that takes the flash message and renders it as a notification on the
top-right edge of the backend.

Backend modules based on :php:`TYPO3\CMS\Backend\Template\ModuleTemplate`
automatically gain advantage of this feature.

Example
=======

.. code-block:: php

    $flashMessageService = GeneralUtility::makeInstance(FlashMessageService::class);
    $notificationQueue = $flashMessageService->getMessageQueueByIdentifier(FlashMessageQueue::NOTIFICATION_QUEUE);
    $flashMessage = GeneralUtility::makeInstance(
        FlashMessage::class,
        'I\'m a message rendered as notification',
        'Hooray!',
        FlashMessage::OK
    );
    $notificationQueue->enqueue($flashMessage);


Impact
======

All flash messages dispatched to the flash message queue
:php:`FlashMessageQueue::NOTIFICATION_QUEUE` will be rendered as notifications
in the browser.

.. index:: Backend, ext:backend

```

</details>

**Comment by sypets** [comment]
This requires 2 changes AFAICS:

* [x] in FlashMessage documentation: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/FlashMessages/Index.html
* [ ] ??? in examples documentation, the triggering of a FlashMessage in JavaScript can be replaced with the "new" mechanism
   * source: [Application.js](https://github.com/TYPO3-Documentation/t3docs-examples/blob/main/Resources/Public/JavaScript/Application.js)   
   *  see example in [changelog](https://review.typo3.org/c/Packages/TYPO3.CMS/+/74582)
