### ISSUE TITLE
[TASK] Move FluidViewAdapter to EXT:fluid

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1082]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/e8450922b2a551c7bd51dcc31aa2de5c57f0aaa2)
:busts_in_silhouette: Authored by Benjamin Franzke ben@bnf.dev
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[TASK] Move FluidViewAdapter to EXT:fluid

The fluid view adapter depends on rendering
context from EXT:fluid, therefore it's better
to be provided by EXT:fluid itself.

While FluidViewAdapter has not been documented as API, an alias is
provided via ClassAliasMap.php, in case instanceof checks have been
used by 3rd party extensions. Also the implementations of the
core view interface are now marked as internal.

Releases: main
Resolves: #105086
Change-Id: I09ee139dcb99fc73e9f7ab50496bdcdda9956213
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86262
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>13.3/Deprecation-101559-ExtbaseUsesExtcoreViewInterface.rst</summary>

```diff
@@ -18,7 +18,7 @@ implementing any view that implements :php-short:`\TYPO3\CMS\Core\View\ViewInter
 and frees the direct dependency to Fluid.
 
 The default return object is an instance of
-:php:`\TYPO3\CMS\Core\View\FluidViewAdapter` which implements all
+:php:`\TYPO3\CMS\Fluid\View\FluidViewAdapter` which implements all
 special methods tailored for Fluid. Extbase controllers should
 check for instance of this object before calling these methods,
 especially:
@@ -48,7 +48,7 @@ Affected installations
 ======================
 
 Instances with Extbase based extensions that call :php:`$view` methods without
-testing for :php-short:`\TYPO3\CMS\Core\View\FluidViewAdapter`.
+testing for :php-short:`\TYPO3\CMS\Fluid\View\FluidViewAdapter`.
 
 
 Migration
```

</details>

**Comment by linawolf** [comment]
Not mentioned
