### ISSUE TITLE
[!!!][TASK] Remove deprecated method returnWebmounts

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1091]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/8df6235dae7113e9140278c1cc10a191ddb24bd1)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated method returnWebmounts

The class method `returnWebmounts` has been removed in class
`\TYPO3\CMS\Core\Authentication\BackendUserAuthentication`.

Resolves: #105380
Related: #105377
Related: #104607
Releases: main
Change-Id: I695edf13b530bb6e0414f69651180e96a26b9bd2
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86679
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -33,7 +33,7 @@ The following PHP class aliases that have previously been marked as deprecated w
 
 The following PHP class methods that have previously been marked as deprecated with v13 have been removed:
 
-- :php:``
+- :php:`\TYPO3\CMS\Core\Authentication\BackendUserAuthentication->returnWebmounts()`
 
 The following PHP static class methods that have previously been marked as deprecated for v13 have been removed:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
