### ISSUE TITLE
[!!!][TASK] Remove deprecated class InformationStatus

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1094]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/21206b500094938071559f55443f10bc48493a38)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Garvin Hicking gh@faktor-e.de

## Commit message

[!!!][TASK] Remove deprecated class InformationStatus

Removed the deprecated class:

`TYPO3\CMS\Backend\Toolbar\Enumeration\InformationStatus´

Resolves: #105392
Related: #105377
Related: #101174
Releases: main
Change-Id: I2838290d3df5053ec07ea91dd09b43530dfb0697
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86689
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -13,7 +13,7 @@ Description
 
 The following PHP classes that have previously been marked as deprecated with v13 have been removed:
 
-- :php:``
+- :php:`\TYPO3\CMS\Backend\Toolbar\Enumeration\InformationStatus`
 
 The following PHP classes have been declared :php:`final`:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
