### ISSUE TITLE
[!!!][TASK] Remove deprecated BackendUtility::thumbCode()

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1095]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/44b63936262d226736091f84f42dec8a4568e47c)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Garvin Hicking gh@faktor-e.de

## Commit message

[!!!][TASK] Remove deprecated BackendUtility::thumbCode()

Previously deprecated `BackendUtility::thumbCode()`
method is now removed.

Resolves: #105397
Related: #105377
Related: #104662
Releases: main
Change-Id: Ifd2a7f39addcc77ebdc2a257888d2df789d908a8
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86695
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -38,7 +38,7 @@ The following PHP class methods that have previously been marked as deprecated w
 
 The following PHP static class methods that have previously been marked as deprecated for v13 have been removed:
 
-- :php:``
+- :php:`\TYPO3\CMS\Backend\Utility\BackendUtility::thumbCode()`
 
 The following methods changed signature according to previous deprecations in v13 at the end of the argument list:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
