### ISSUE TITLE
[!!!][TASK] Remove deprecated Extbase HashService

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1096]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/8e46ba81477db43c04f2d6bfe417b6162819fa46)
:busts_in_silhouette: Authored by Torben Hansen derhansen@gmail.com
:heavy_check_mark: Merged by Andreas Kienast akienast@scripting-base.de

## Commit message

[!!!][TASK] Remove deprecated Extbase HashService

The previously deprecated Extbase `HashService` class is now
removed.

Resolves: #105399
Related: #105377
Related: #102763
Releases: main
Change-Id: Ieae43539041a80e994b04324123082d5bbeaca84
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86699
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -14,6 +14,7 @@ Description
 The following PHP classes that have previously been marked as deprecated with v13 have been removed:
 
 - :php:`\TYPO3\CMS\Backend\Toolbar\Enumeration\InformationStatus`
+- :php:`\TYPO3\CMS\Extbase\Security\Cryptography\HashService`
 
 The following PHP classes have been declared :php:`final`:
 
```

</details>

**Comment by linawolf** [comment]
the HashService from extbase is not mentioned, the one from the core still exists
