### ISSUE TITLE
[!!!][TASK] Remove deprecated `@typo3/t3editor` specifier

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1097]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/901e4df4feeafe19c59a41eb3e8dd1237f8f5c74)
:busts_in_silhouette: Authored by Andreas Kienast akienast@scripting-base.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated `@typo3/t3editor` specifier

The JavaScript module specifier `@typo3/t3editor` has been deprecated
with the merge of EXT:t3editor into EXT:backend in v13.0 and is now
removed.

Resolves: #105406
Related: #105377
Related: #102440
Releases: main
Change-Id: I3398141cda05a9ce2f95a798914d631a4345e4f4
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86706
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -154,9 +154,9 @@ The following global JavaScript function has been removed:
 
 - :js:``
 
-The following JavaScript module has been removed:
+The following JavaScript modules have been removed:
 
-- :js:`x`
+- :js:`@typo3/t3editor/*`
 
 The following JavaScript method behaviour has changed:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
