### ISSUE TITLE
[!!!][TASK] Remove deprecated class IconState

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1098]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/0cd6d1e7a4f3fd4d3ff58ede28e5ddd0d4ca096c)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated class IconState

Removed the deprecated class:
`\TYPO3\CMS\Core\Type\Icon\IconState`

Change signature of `\TYPO3\CMS\Core\Imaging\IconFactory->getIcon()`,
argument 4 is now of type `?\TYPO3\CMS\Core\Imaging\IconState`.

Resolves: #105393
Related: #105377
Related: #101133
Releases: main
Change-Id: I6d1f6e2db388496784a0e73da92552d3008065fc
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86700
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -15,6 +15,7 @@ The following PHP classes that have previously been marked as deprecated with v1
 
 - :php:`\TYPO3\CMS\Backend\Toolbar\Enumeration\InformationStatus`
 - :php:`\TYPO3\CMS\Extbase\Security\Cryptography\HashService`
+- :php:`\TYPO3\CMS\Core\Type\Icon\IconState`
 
 The following PHP classes have been declared :php:`final`:
 
@@ -43,7 +44,7 @@ The following PHP static class methods that have previously been marked as depre
 
 The following methods changed signature according to previous deprecations in v13 at the end of the argument list:
 
-- :php:`` (argument X is now required)
+- :php:`\TYPO3\CMS\Core\Imaging\IconFactory->getIcon()` (argument 4 is now of type :php:`\TYPO3\CMS\Core\Imaging\IconState|null`)
 
 The following public class properties have been dropped:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
