### ISSUE TITLE
[!!!][TASK] Remove deprecated PageRepositoryHook interfaces

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1100]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/c3eef13125ac66375b302b181a5b13eab47b9575)
:busts_in_silhouette: Authored by Garvin Hicking gh@faktor-e.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated PageRepositoryHook interfaces

The previously deprecated PageRepositoryHook interfaces
are now removed:

* `\TYPO3\CMS\Core\Domain\Repository\PageRepositoryInitHookInterface`
* `\TYPO3\CMS\Core\Domain\Repository\PageRepositoryGetPageHookInterface`

Releases: main
Resolves: #105383
Related: #102806
Related: #105377
Change-Id: I6c97630244d6bd28504f5439d05ae8235475af26
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86705
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -23,7 +23,8 @@ The following PHP classes have been declared :php:`final`:
 
 The following PHP interfaces that have previously been marked as deprecated with v13 have been removed:
 
-- :php:``
+- :php:`\TYPO3\CMS\Core\Domain\Repository\PageRepositoryInitHookInterface`
+- :php:`\TYPO3\CMS\Core\Domain\Repository\PageRepositoryGetPageHookInterface`
 
 The following PHP interfaces changed:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
