### ISSUE TITLE
[!!!][TASK] Remove deprecated methods in DataProviderContext

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1101]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/6909d22955bd469ce39f02e955f859290754700e)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated methods in DataProviderContext

Clean up constructor and remove methods as
advertised in v13.

Resolves: #105415
Related: #105377
Related: #105252
Releases: main
Change-Id: Ic773143c4fa1d784a4db14fd01e5ed3d715b444e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86714
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -36,6 +36,16 @@ The following PHP class aliases that have previously been marked as deprecated w
 
 The following PHP class methods that have previously been marked as deprecated with v13 have been removed:
 
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->getData()`
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->getFieldName()`
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->getPageId()`
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->getPageTsConfig()`
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->getTableName()`
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->setData()`
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->setFieldName()`
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->setPageId()`
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->setPageTsConfig()`
+* :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->setTableName()`
 - :php:`\TYPO3\CMS\Core\Authentication\BackendUserAuthentication->returnWebmounts()`
 - :php:`\TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent->getSize()`
 
@@ -45,6 +55,7 @@ The following PHP static class methods that have previously been marked as depre
 
 The following methods changed signature according to previous deprecations in v13 at the end of the argument list:
 
+- :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->__construct()` - All arguments are now mandatory
 - :php:`\TYPO3\CMS\Core\Imaging\IconFactory->getIcon()` (argument 4 is now of type :php:`\TYPO3\CMS\Core\Imaging\IconState|null`)
 
 The following public class properties have been dropped:
```

</details>

**Comment by linawolf** [comment]
Not mentioned
