### ISSUE TITLE
[!!!][TASK] Remove jQuery compatibility from `@typo3/backend/form-engine-validation`

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1102]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ad777a1a87ed48d5cc70b56c7b1db804386f3ebe)
:busts_in_silhouette: Authored by Andreas Kienast akienast@scripting-base.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove jQuery compatibility from `@typo3/backend/form-engine-validation`

The following JavaScript method behaviours have changed:

- `markFieldAsChanged()` does not accept jQuery objects anymore
- `validateField()` does not accept jQuery object anymore

Resolves: #105409
Related: #105377
Related: #101912
Releases: main
Change-Id: I15eb8ddb2e3438e0458ec357779678944b104f8f
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86709
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -177,9 +177,10 @@ The following JavaScript modules have been removed:
 
 - :js:`@typo3/t3editor/*`
 
-The following JavaScript method behaviour has changed:
+The following JavaScript method behaviours have changed:
 
-- :js:`X.y()` always requires an :js:`X` to be passed as first argument
+- :js:`FormEngineValidation.markFieldAsChanged()` always requires :js:`HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement` to be passed as first argument
+- :js:`FormEngineValidation.validateField()` always requires :js:`HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement` to be passed as first argument
 
 The following JavaScript method has been removed:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
