### ISSUE TITLE
[!!!][TASK] Remove ext:fluid fillDefaultsByPackageName()

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1104]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/1a49ef72b4f007d980ae1cbb8277426e26874b82)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove ext:fluid fillDefaultsByPackageName()

Remove as advertised.

Resolves: #105419
Related: #105377
Related: #104764
Releases: main
Change-Id: I0e96a90f4518ff67dede7ba3392d3e884919150b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86720
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -48,6 +48,7 @@ The following PHP class methods that have previously been marked as deprecated w
 * :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->setTableName()`
 - :php:`\TYPO3\CMS\Core\Authentication\BackendUserAuthentication->returnWebmounts()`
 - :php:`\TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent->getSize()`
+- :php:`\TYPO3\CMS\Fluid\View\TemplatePaths->fillDefaultsByPackageName()`
 
 The following PHP static class methods that have previously been marked as deprecated for v13 have been removed:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
