### ISSUE TITLE
[!!!][TASK] Remove deprecations in VersionState

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1106]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/a990e69dd8c1d7d297ae0331e5633bfe90b6e240)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Andreas Kienast akienast@scripting-base.de

## Commit message

[!!!][TASK] Remove deprecations in VersionState

The following class methods have been removed:

* `\TYPO3\CMS\Core\Versioning\VersionState::cast()`
* `\TYPO3\CMS\Core\Versioning\VersionState->equals()`

Resolves: #105385
Related: #105377
Related: #101175
Releases: main
Change-Id: I9a485b6b7f7c95ff337bedd40e703de78a8273d1
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86684
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -48,11 +48,13 @@ The following PHP class methods that have previously been marked as deprecated w
 * :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->setTableName()`
 - :php:`\TYPO3\CMS\Core\Authentication\BackendUserAuthentication->returnWebmounts()`
 - :php:`\TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent->getSize()`
+- :php:`\TYPO3\CMS\Core\Versioning\VersionState->equals()`
 - :php:`\TYPO3\CMS\Fluid\View\TemplatePaths->fillDefaultsByPackageName()`
 
 The following PHP static class methods that have previously been marked as deprecated for v13 have been removed:
 
 - :php:`\TYPO3\CMS\Backend\Utility\BackendUtility::thumbCode()`
+- :php:`\TYPO3\CMS\Core\Versioning\VersionState::cast()`
 
 The following methods changed signature according to previous deprecations in v13 at the end of the argument list:
 
```

</details>

**Comment by linawolf** [comment]
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Enumerations/Enumeration.html#implement-custom-logic

**Comment by brotkrueml** [comment]
Is removed with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4886
