### ISSUE TITLE
[!!!][TASK] Remove support for arrays returned by `readFileContent()` in external parsers

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1107]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/2d9bfaf496ccd082be47d78369514731874563ad)
:busts_in_silhouette: Authored by Andreas Kienast akienast@scripting-base.de
:heavy_check_mark: Merged by Andreas Kienast akienast@scripting-base.de

## Commit message

[!!!][TASK] Remove support for arrays returned by `readFileContent()` in external parsers

External parsers for Indexed Search were allowed to return an array via
`readFileContent()`, which was converted to an instance of
`IndexingDataAsString`. This fallback has been removed, anything that is
not of type `IndexingDataAsString` is ignored.

Resolves: #105420
Related: #105377
Related: #102908
Change-Id: Ia26b80f95b511482cc3f9cdd619ad0bb2f3cb04a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86721
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -147,7 +147,7 @@ The following event has been removed:
 
 The following fallbacks have been removed:
 
-- Usage of the X
+- Accepting arrays returned by :php:`readFileContent()` in Indexed Search external parsers
 
 The following upgrade wizards have been removed:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
