### ISSUE TITLE
[!!!][TASK] Remove deprecated `MathUtility::convertToPositiveInteger()`

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1109]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/90a1b8e649cdaae0cd8676fa5658e47a2512dc57)
:busts_in_silhouette: Authored by Andreas Kienast akienast@scripting-base.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated `MathUtility::convertToPositiveInteger()`

The following PHP static class method that has previously been marked as
deprecated for v13 has been removed:

- `\TYPO3\CMS\Core\Utility\MathUtility::convertToPositiveInteger()`

Resolves: #105428
Related: #105377
Related: #103785
Releases: main
Change-Id: Ib0810abd2a88663490843025a3c53e073ff7d00b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86727
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: Thomas Hohn <tho@gyldendal.dk>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -55,6 +55,7 @@ The following PHP class methods that have previously been marked as deprecated w
 The following PHP static class methods that have previously been marked as deprecated for v13 have been removed:
 
 - :php:`\TYPO3\CMS\Backend\Utility\BackendUtility::thumbCode()`
+- :php:`\TYPO3\CMS\Core\Utility\MathUtility::convertToPositiveInteger()`
 - :php:`\TYPO3\CMS\Core\Versioning\VersionState::cast()`
 
 The following methods changed signature according to previous deprecations in v13 at the end of the argument list:
```

</details>

**Comment by linawolf** [comment]
Never mentioned
