### ISSUE TITLE
[!!!][TASK] Remove 'extension download' upgrade wizard aliases

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1110]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/53f92e26e789b80669169c03fe76f6121a396833)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove 'extension download' upgrade wizard aliases

Alias definitions of the moved classes are removed.

Resolves: #105434
Related: #105377
Related: #102943
Releases: main
Change-Id: Ib7c3b5ccda34a49cb5bafe281f1458cb59a86878
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86753
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Thomas Hohn <tho@gyldendal.dk>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -20,7 +20,7 @@ The following PHP classes that have previously been marked as deprecated with v1
 
 The following PHP classes have been declared :php:`final`:
 
-- :php:``
+- :php:`\TYPO3\CMS\Extensionmanager\Updates\ExtensionModel`
 
 The following PHP interfaces that have previously been marked as deprecated with v13 have been removed:
 
@@ -33,7 +33,8 @@ The following PHP interfaces changed:
 
 The following PHP class aliases that have previously been marked as deprecated with v13 have been removed:
 
-- :php:``
+- :php:`\TYPO3\CMS\Install\Updates\AbstractDownloadExtensionUpdate`
+- :php:`\TYPO3\CMS\Install\Updates\ExtensionModel`
 
 The following PHP class methods that have previously been marked as deprecated with v13 have been removed:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
