### ISSUE TITLE
[!!!][TASK] Remove `Utility.updateQueryStringParameter()`

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1111]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/5d1a40d9319689e14bcf8852d16029deec631247)
:busts_in_silhouette: Authored by Andreas Kienast akienast@scripting-base.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove `Utility.updateQueryStringParameter()`

The following JavaScript method has been removed:

- `updateQueryStringParameter()` of `@typo3/backend/utility.js`

If required, developers shall use the native `URL` and `URLSearchParams`
objects instead.

Resolves: #105427
Related: #105377
Related: #104154
Releases: main
Change-Id: Iaa3edfdf2eb50897ed415858c37dee5851a3d090
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86726
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -218,7 +218,7 @@ The following JavaScript method behaviours have changed:
 
 The following JavaScript method has been removed:
 
-- :js:`X()` of :js:`@typo3/x/y`
+- :js:`updateQueryStringParameter()` of :js:`@typo3/backend/utility.js`
 
 The following CKEditor plugin has been removed:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
