### ISSUE TITLE
[!!!][TASK] Remove deprecated `@typo3/backend/wizard.js` module

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1113]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/5781f810f425a63746f4365dc3bd155e13723728)
:busts_in_silhouette: Authored by Andreas Kienast akienast@scripting-base.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated `@typo3/backend/wizard.js` module

The deprecated JavaScript module `@typo3/backend/wizard.js` is now
removed from Core.

Resolves: #105435
Related: #105377
Related: #103230
Releases: main
Change-Id: I7c1b7674a5e5082d36313a150fabb6f13c5d4b4e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86756
Tested-by: Thomas Hohn <tho@gyldendal.dk>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -210,6 +210,7 @@ The following global JavaScript function has been removed:
 
 The following JavaScript modules have been removed:
 
+- :js:`@typo3/backend/wizard.js`
 - :js:`@typo3/t3editor/*`
 
 The following JavaScript method behaviours have changed:
```

</details>

**Comment by linawolf** [comment]
Not mentioned
