### ISSUE TITLE
[!!!][TASK] Remove deprecated `@typo3/backend/document-save-actions` module

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1114]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/9189a82ea26e1fae1bcc3beb3c39995b97b55af0)
:busts_in_silhouette: Authored by Andreas Kienast akienast@scripting-base.de
:heavy_check_mark: Merged by Garvin Hicking gh@faktor-e.de

## Commit message

[!!!][TASK] Remove deprecated `@typo3/backend/document-save-actions` module

The deprecated JavaScript module `@typo3/backend/document-save-actions`
is now removed from Core.

Resolves: #105436
Related: #105377
Related: #103528
Releases: main
Change-Id: I7ce6a08c146caba98af893648a678ea8f065394e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86757
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Thomas Hohn <tho@gyldendal.dk>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -210,6 +210,7 @@ The following global JavaScript function has been removed:
 
 The following JavaScript modules have been removed:
 
+- :js:`@typo3/backend/document-save-actions.js`
 - :js:`@typo3/backend/wizard.js`
 - :js:`@typo3/t3editor/*`
 
```

</details>

**Comment by linawolf** [comment]
Was not mentioned
