### ISSUE TITLE
[!!!][TASK] Remove deprecated class SlugEnricher

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1117]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/fc59275df7df957ba9f6f524d29b530ff55321cb)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated class SlugEnricher

The functionality has been inlined to DataHandler
in v13 and was just kept for backwards compatibility.

Resolves: #105448
Related: #105377
Related: #103244
Releases: main
Change-Id: I4b5d335f2e92d4fe54b75f12d25caa15ae260f83
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86766
Tested-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -14,6 +14,7 @@ Description
 The following PHP classes that have previously been marked as deprecated with v13 have been removed:
 
 - :php:`\TYPO3\CMS\Backend\Toolbar\Enumeration\InformationStatus`
+- :php:`\TYPO3\CMS\Core\DataHandling\SlugEnricher`
 - :php:`\TYPO3\CMS\Core\Resource\DuplicationBehavior`
 - :php:`\TYPO3\CMS\Core\Type\Enumeration`
 - :php:`\TYPO3\CMS\Core\Type\Icon\IconState`
```

</details>

**Comment by linawolf** [comment]
Never mentioned
