### ISSUE TITLE
[!!!][TASK] Remove deprecated method getTcaFieldConfiguration

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1118]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/101bcfb126a1311eeb04a5c285cafbc838f32f32)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated method getTcaFieldConfiguration

The PHP static class method `getTcaFieldConfiguration()` that has
previously been marked as deprecated for v13 has been removed in
`\TYPO3\CMS\Backend\Utility\BackendUtility`.

Resolves: #105443
Related: #105377
Related: #104304
Releases: main
Change-Id: I073ac675b2ec1b0b73128ef4df1b5d47b76ae2ab
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86761
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -76,6 +76,7 @@ The following PHP class methods that have previously been marked as deprecated w
 
 The following PHP static class methods that have previously been marked as deprecated for v13 have been removed:
 
+- :php:`\TYPO3\CMS\Backend\Utility\BackendUtility::getTcaFieldConfiguration()`
 - :php:`\TYPO3\CMS\Backend\Utility\BackendUtility::thumbCode()`
 - :php:`\TYPO3\CMS\Core\Utility\MathUtility::convertToPositiveInteger()`
 - :php:`\TYPO3\CMS\Core\Versioning\VersionState::cast()`
```

</details>

**Comment by linawolf** [comment]
Was never mentioned
