### ISSUE TITLE
[TASK] Remove superfluous namespace within form configuration

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#112]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/451c896f0b35f9409fbcf0ef53166085496bb96c)
:busts_in_silhouette: Authored by Ralf Zimmermann hello@waldhacker.dev
:heavy_check_mark: Merged by waldhacker hello@waldhacker.dev

## Commit message

[TASK] Remove superfluous namespace within form configuration

Removes the vendor namespace (TYPO3.CMS.Form) within form
configuration.
The compatibility to the notation with the vendor namespace is
maintained, both notations are still possible.

Resolves: #97517
Related: #97520
Releases: main
Change-Id: I406e968c89002f32854729c96349f44bba3263ae
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/74490
Tested-by: core-ci <typo3@b13.com>
Tested-by: Elias Häußler <e.haeussler@familie-redlich.de>
Tested-by: Björn Jacob <bjoern.jacob@tritum.de>
Tested-by: waldhacker <hello@waldhacker.dev>
Reviewed-by: Elias Häußler <e.haeussler@familie-redlich.de>
Reviewed-by: Björn Jacob <bjoern.jacob@tritum.de>
Reviewed-by: waldhacker <hello@waldhacker.dev>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Important-97517-RemoveTheSuperfluousNamespaceWithinTheFormConfiguration.rst</summary>

```rst
.. include:: /Includes.rst.txt

==================================================================================
Important: #97517 - Remove the superfluous namespace within the form configuration
==================================================================================

See :issue:`97517`

Description
===========

The superfluous vendor namespace (:yaml:`TYPO3.CMS.Form`) has been removed from the form configuration. That way the configuration of the form framework is less deeply nested.

The compatibility to the notation with the vendor namespace is
maintained, both notations are still possible. Nevertheless we recommend not to apply the vendor namespace.

Migration
=========

This is how the legacy configuration with vendor namespace looks like:

.. code-block:: yaml

    TYPO3:
      CMS:
        Form:
          prototypes:
            standard:
              formElementsDefinition:
                # ...
          # ...

This is how the new (preferred) configuration without vendor namespace looks like:

.. code-block:: yaml

    prototypes:
      standard:
        formElementsDefinition:
                # ...
    # ...

.. index:: Backend, ext:form

```

</details>

**Comment by sypets** [comment]
Must be documented in sysext form, see https://forge.typo3.org/issues/97896
