### ISSUE TITLE
[!!!][TASK] Remove deprecated method getExtensionIcon

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1121]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/87a018cf0974b8ce1d2bd62a71d2e04cfadb8adb)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Anja Leichsenring aleichsenring@ab-softlab.de

## Commit message

[!!!][TASK] Remove deprecated method getExtensionIcon

The PHP static class method `getExtensionIcon()` that has previously
been marked as deprecated for v13 has been removed in
`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility`.

Resolves: #105442
Related: #105377
Related: #102895
Releases: main
Change-Id: I458e0b411d4d0213dd48f0138f37577681e33593
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86760
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -89,6 +89,7 @@ The following PHP static class methods that have previously been marked as depre
 - :php:`\TYPO3\CMS\Backend\Utility\BackendUtility::getTcaFieldConfiguration()`
 - :php:`\TYPO3\CMS\Backend\Utility\BackendUtility::thumbCode()`
 - :php:`\TYPO3\CMS\Core\Utility\GeneralUtility::hmac()`
+- :php:`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getExtensionIcon()`
 - :php:`\TYPO3\CMS\Core\Utility\MathUtility::convertToPositiveInteger()`
 - :php:`\TYPO3\CMS\Core\Versioning\VersionState::cast()`
 
```

</details>

**Comment by linawolf** [comment]
Never mentioned
