### ISSUE TITLE
[!!!][TASK] Remove deprecated DataHandler `checkStoredRecords` properties

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1123]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/7b69e1a9bf8073d73b80f4d2c7386415c7408e80)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Andreas Kienast akienast@scripting-base.de

## Commit message

[!!!][TASK] Remove deprecated DataHandler `checkStoredRecords` properties

Remove these unused properties.

Resolves: #105449
Related: #105377
Related: #101793
Releases: main
Change-Id: I16f5d36f271da0bada1141f4c2b896c0979532a7
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86767
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -120,7 +120,8 @@ The following methods changed signature according to previous deprecations in v1
 
 The following public class properties have been dropped:
 
-- :php:``
+- :php:`\TYPO3\CMS\Core\DataHandling->checkStoredRecords`
+- :php:`\TYPO3\CMS\Core\DataHandling->checkStoredRecords_loose`
 
 The following class method visibility has been changed to protected:
 
```

</details>

**Comment by linawolf** [comment]
not mentioned anymore

**Comment by linawolf** [comment]
The variables themselves are not mentioned but the TYPO3_CONF_VARS need to be removed
