### ISSUE TITLE
[DOCS] Add example for rendering record objects in PAGEVIEW

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1124]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/92092f0faa4c0f4fde7e064ff5465bf175175959)
:busts_in_silhouette: Authored by Nikita Hovratov nikita.h@live.de
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[DOCS] Add example for rendering record objects in PAGEVIEW

Usually, the existing rendering definition is used for rendering
Content Elements, instead of building it manually in the page template.
The example is changed to use the f:cObject ViewHelper, which makes
use of already available information for table, record type and
the raw record.

Resolves: #105355
Releases: main, 13.4
Change-Id: I62647b865c539d6e7b7b97c90896bd7f59533e99
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86651
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_division_sign: Modified files

<details>
<summary>13.2/Feature-103894-AdditionalPropertiesForColumnsInPageLayouts.rst</summary>

```diff
@@ -97,7 +97,7 @@ Example of the frontend output:
 
     <main>
         <f:for each="{myContent.main.records}" as="record">
-            <h4>{record.header}</h4>
+            <f:cObject typoscriptObjectPath="{record.fullType}" table="{record.mainType}" data="{record.rawRecord}"/>
         </f:for>
     </main>
 
```

</details>

**Comment by linawolf** [comment]
Resolved with https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1140
