### ISSUE TITLE
[!!!][TASK] Remove deprecated code from DiffUtility

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1125]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/2db8202368314a49119bfe5c470fbd87d1387f21)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Andreas Kienast akienast@scripting-base.de

## Commit message

[!!!][TASK] Remove deprecated code from DiffUtility

Clean up the class which makes it fully stateless.

Resolves: #105450
Related: #105377
Related: #104325
Releases: main
Change-Id: I6732b440ddca3df384ba154afa6f87887fa1d5cb
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86768
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Andreas Kienast <akienast@scripting-base.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -62,6 +62,7 @@ The following PHP class methods that have previously been marked as deprecated w
 - :php:`\TYPO3\CMS\Backend\View\BackendLayout\DataProviderContext->setTableName()`
 - :php:`\TYPO3\CMS\Core\Authentication\BackendUserAuthentication->returnWebmounts()`
 - :php:`\TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent->getSize()`
+- :php:`\TYPO3\CMS\Core\Utility\DiffUtility->makeDiffDisplay()`
 - :php:`\TYPO3\CMS\Core\Versioning\VersionState->equals()`
 - :php:`\TYPO3\CMS\Extbase\Mvc\View\JsonView->renderSection()`
 - :php:`\TYPO3\CMS\Extbase\Mvc\View\JsonView->renderPartial()`
@@ -122,6 +123,7 @@ The following public class properties have been dropped:
 
 - :php:`\TYPO3\CMS\Core\DataHandling->checkStoredRecords`
 - :php:`\TYPO3\CMS\Core\DataHandling->checkStoredRecords_loose`
+- :php:`\TYPO3\CMS\Core\Utility\DiffUtility->stripTags`
 
 The following class method visibility has been changed to protected:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
