### ISSUE TITLE
[!!!][TASK] Remove deprecated `PageRepository->enableFields()`

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1126]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/7be505b4e892e33e23051bcaaca19945d3609006)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Garvin Hicking gh@faktor-e.de

## Commit message

[!!!][TASK] Remove deprecated `PageRepository->enableFields()`

The following PHP class method that has previously been marked as
deprecated for v13 has been removed:

- `\TYPO3\CMS\Frontend\Page\PageRepository->enableFields()`

Resolves: #105453
Related: #105377
Related: #102793
Releases: main
Change-Id: I4b9a770e2a4f3973e14d0ac115409c4c19e1c937
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86772
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -84,6 +84,7 @@ The following PHP class methods that have previously been marked as deprecated w
 - :php:`\TYPO3\CMS\Fluid\View\FluidViewAdapter->setTemplateRootPaths()`
 - :php:`\TYPO3\CMS\Fluid\View\FluidViewAdapter->setTemplateSource()`
 - :php:`\TYPO3\CMS\Fluid\View\TemplatePaths->fillDefaultsByPackageName()`
+- :php:`\TYPO3\CMS\Frontend\Page\PageRepository->enableFields()`
 
 The following PHP static class methods that have previously been marked as deprecated for v13 have been removed:
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned
