### ISSUE TITLE
[!!!][TASK] Remove legacy class aliases

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1127]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f7d6dd25d5a590cb1f389ac9da7e284c125fad88)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove legacy class aliases

Remove a series of aliases of classes that
have been moved in v13.

Need a raise of typo3/testing-framework which
still used the alias.

> composer u typo3/testing-framework

Resolves: #105458
Related: #105377
Related: #102631
Related: #105279
Related: #105086
Related: #105175
Releases: main
Change-Id: I286e8b9c74b47c81e8ccda923afe3e3afe0ca10f
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86774
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -41,6 +41,11 @@ The following PHP interfaces changed:
 
 The following PHP class aliases that have previously been marked as deprecated with v13 have been removed:
 
+- :php:`\TYPO3\CMS\Backend\Attribute\AsController`
+- :php:`\TYPO3\CMS\Backend\FrontendBackendUserAuthentication`
+- :php:`\TYPO3\CMS\Core\Database\Schema\Types\EnumType`
+- :php:`\TYPO3\CMS\Core\View\FluidViewAdapter`
+- :php:`\TYPO3\CMS\Core\View\FluidViewFactory`
 - :php:`\TYPO3\CMS\Install\Updates\AbstractDownloadExtensionUpdate`
 - :php:`\TYPO3\CMS\Install\Updates\ExtensionModel`
 
```

</details>

**Comment by linawolf** [comment]
Not mentioned in the docs
