### ISSUE TITLE
[!!!][TASK] Remove deprecated methods in `TypoScriptFrontendController`

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1129]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/954c005b146d210c667d4e9ec249847530480988)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated methods in `TypoScriptFrontendController`

The following PHP class methods that have previously been marked as
deprecated for v13 have been removed in class
`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController`:

- `addCacheTags()`
- `getPageCacheTags()`

Resolves: #105460
Related: #105377
Related: #102422
Releases: main
Change-Id: I9c24f68e6b697e76c2cfc5bd721027ce176b30ed
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86775
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -91,6 +91,8 @@ The following PHP class methods that have previously been marked as deprecated w
 - :php:`\TYPO3\CMS\Fluid\View\FluidViewAdapter->setTemplateRootPaths()`
 - :php:`\TYPO3\CMS\Fluid\View\FluidViewAdapter->setTemplateSource()`
 - :php:`\TYPO3\CMS\Fluid\View\TemplatePaths->fillDefaultsByPackageName()`
+- :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->addCacheTags()`
+- :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->getPageCacheTags()`
 - :php:`\TYPO3\CMS\Frontend\Page\PageRepository->enableFields()`
 
 The following PHP static class methods that have previously been marked as deprecated for v13 have been removed:
```

</details>

**Comment by linawolf** [comment]
Depends on https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1042
