### ISSUE TITLE
[BUGFIX] Fix typo in #96935 changelog

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#113]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ef2a2d893da6cdab2fec61fb9493cb7bea828ae2)
:busts_in_silhouette: Authored by Nikita Hovratov nikita.h@live.de
:heavy_check_mark: Merged by Nikita Hovratov nikita.h@live.de

## Commit message

[BUGFIX] Fix typo in #96935 changelog

Resolves: #97840
Related: #96935
Releases: main
Change-Id: If3ea919f5350aa65d2967b22b40a1334eb33fbca
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75006
Tested-by: Björn Jacob <bjoern.jacob@tritum.de>
Tested-by: Nikita Hovratov <nikita.h@live.de>
Reviewed-by: Björn Jacob <bjoern.jacob@tritum.de>
Reviewed-by: Nikita Hovratov <nikita.h@live.de>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Feature-96935-NewRegistrationForLinkvalidatorLinktype.rst</summary>

```rst
.. include:: /Includes.rst.txt

=============================================================
Feature: #96935 - New registration for linkvalidator linktype
=============================================================

See :issue:`96935`

Description
===========

The system extension `linkvalidator` uses so called `linktypes` for
checking different types of links, e.g. internal or external links.
All `linktypes` have to implement the :php:`LinktypeInterface`.

This fact is now used to automatically register the `linktypes`, based
on the interface, if :yaml:`autoconfigure` is enabled in :file:`Services.yaml`.
Alternatively, one can manually tag a custom `linktype` with the
:yaml:`linkvalidator.linktype` tag (See section "Migration" in the
:doc:`breaking changelog <Breaking-96935-RegisterLinkvalidatorLinktypesViaServiceConfiguration>`).

Due to the autoconfiguration, the identifier has to be provided by the
class directly, using the now required :php:`getIdentifier()` method.
When extending :php:`\TYPO3\CMS\Linkvalidator\Linktype\AbstractLinktype`
it's sufficient to set the `$identifier` class property.

Impact
======

`linktypes` are now automatically registered through the service configuration,
based on the implemented interface.

.. index:: Backend, LocalConfiguration, PHP-API, ext:linkvalidator

```

</details>

**Comment by linawolf** [comment]
Minor typo fix
