### ISSUE TITLE
[!!!][TASK] Remove deprecated ExtensionManagementUtility::addPItoST43()

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1130]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/42172d5cfe783a3cc2345d9506decf278dfb5faa)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated ExtensionManagementUtility::addPItoST43()

The following PHP static class method that has previously been marked as
deprecated for v13 has been removed:

- `\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPItoST43()`

Resolves: #105465
Related: #105377
Related: #102821
Releases: main
Change-Id: I31b70720222bcf31b7bc595c4543dc25663e21b1
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86779
Tested-by: Andreas Nedbal <andy@pixelde.su>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Andreas Nedbal <andy@pixelde.su>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Andreas Kienast <akienast@scripting-base.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -100,6 +100,7 @@ The following PHP static class methods that have previously been marked as depre
 - :php:`\TYPO3\CMS\Backend\Utility\BackendUtility::getTcaFieldConfiguration()`
 - :php:`\TYPO3\CMS\Backend\Utility\BackendUtility::thumbCode()`
 - :php:`\TYPO3\CMS\Core\Utility\GeneralUtility::hmac()`
+- :php:`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPItoST43()`
 - :php:`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getExtensionIcon()`
 - :php:`\TYPO3\CMS\Core\Utility\MathUtility::convertToPositiveInteger()`
 - :php:`\TYPO3\CMS\Core\Versioning\VersionState::cast()`
```

</details>

**Comment by linawolf** [comment]
Not mentioned anymore
