### ISSUE TITLE
[!!!][TASK] Remove deprecated CacheService->getPageIdStack()

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1132]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/b13de28e3a10bc94f91b4a7e4f50c4d5b948cba2)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Andreas Kienast akienast@scripting-base.de

## Commit message

[!!!][TASK] Remove deprecated CacheService->getPageIdStack()

Removal in an @internal class.

Resolves: #105469
Related: #105377
Related: #104990
Releases: main
Change-Id: I99af5cc15fb83233f28ddbc6022e6b70d36e6020
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86784
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Thomas Hohn <tho@gyldendal.dk>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -71,6 +71,7 @@ The following PHP class methods that have previously been marked as deprecated w
 - :php:`\TYPO3\CMS\Core\Versioning\VersionState->equals()`
 - :php:`\TYPO3\CMS\Extbase\Mvc\View\JsonView->renderSection()`
 - :php:`\TYPO3\CMS\Extbase\Mvc\View\JsonView->renderPartial()`
+- :php:`\TYPO3\CMS\Extbase\Service\CacheService->getPageIdStack()`
 - :php:`\TYPO3\CMS\Fluid\Core\Rendering\RenderingContext->setRequest()`
 - :php:`\TYPO3\CMS\Fluid\Core\Rendering\RenderingContext->getRequest()`
 - :php:`\TYPO3\CMS\Fluid\View\FluidViewAdapter->getLayoutRootPaths()`
```

</details>

**Comment by linawolf** [comment]
Never mentioned
