### ISSUE TITLE
[!!!][TASK] Remove deprecated ContentObjectOneSourceCollectionHookInterface

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1134]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ea41bb42c57e2e16eed3843935e0e287f86e6fbc)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[!!!][TASK] Remove deprecated ContentObjectOneSourceCollectionHookInterface

Resolves: #105474
Related: #105377
Related: #102624
Releases: main
Change-Id: I713951aa3b9e60dbc8fb8db9b0b83e3378c6478a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86789
Reviewed-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Andreas Kienast <akienast@scripting-base.de>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -33,6 +33,7 @@ The following PHP interfaces that have previously been marked as deprecated with
 - :php:`\TYPO3\CMS\Core\Domain\Repository\PageRepositoryInitHookInterface`
 - :php:`\TYPO3\CMS\Core\Domain\Repository\PageRepositoryGetPageHookInterface`
 - :php:`\TYPO3\CMS\Extbase\Mvc\View\ViewResolverInterface`
+- :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectOneSourceCollectionHookInterface`
 
 The following PHP interfaces changed:
 
```

</details>

**Comment by linawolf** [comment]
Was never mentioned
