### ISSUE TITLE
[!!!][TASK] Remove deprecated ContentObjectGetImageResourceHookInterface

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1135]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/a663d3cb0b8e98c9a938a3326ab93f9ef6649a7a)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated ContentObjectGetImageResourceHookInterface

Resolves: #105473
Related: #105377
Related: #102755
Releases: main
Change-Id: I869e9e5aa32ef576b57541492f9a95c559438a6e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86788
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Thomas Hohn <tho@gyldendal.dk>
Reviewed-by: Thomas Hohn <tho@gyldendal.dk>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -33,6 +33,7 @@ The following PHP interfaces that have previously been marked as deprecated with
 - :php:`\TYPO3\CMS\Core\Domain\Repository\PageRepositoryInitHookInterface`
 - :php:`\TYPO3\CMS\Core\Domain\Repository\PageRepositoryGetPageHookInterface`
 - :php:`\TYPO3\CMS\Extbase\Mvc\View\ViewResolverInterface`
+- :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectGetImageResourceHookInterface`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectOneSourceCollectionHookInterface`
 
 The following PHP interfaces changed:
```

</details>

**Comment by linawolf** [comment]
Was never mentioned
