### ISSUE TITLE
[!!!][TASK] Remove deprecated ContentObjectStdWrapHookInterface

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1136]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/26e0cc5edecfcc119830de5e19aa7241b51af36a)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated ContentObjectStdWrapHookInterface

Resolves: #105475
Related: #105377
Related: #102745
Releases: main
Change-Id: I610b92e571d71cb6936ece72adfd9af8e538f50c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86790
Tested-by: core-ci <typo3@b13.com>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -35,6 +35,7 @@ The following PHP interfaces that have previously been marked as deprecated with
 - :php:`\TYPO3\CMS\Extbase\Mvc\View\ViewResolverInterface`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectGetImageResourceHookInterface`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectOneSourceCollectionHookInterface`
+- :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectStdWrapHookInterface`
 
 The following PHP interfaces changed:
 
```

</details>

**Comment by linawolf** [comment]
Was never mentioned
