### ISSUE TITLE
[!!!][TASK] Remove deprecated ContentObjectGetDataHookInterface

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1137]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/96fa46ed8472b87d63822fd7e37b08941bcf7679)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated ContentObjectGetDataHookInterface

Resolves: #105472
Related: #105377
Related: #102614
Releases: main
Change-Id: I71ef3d0a2d473ab42fb413d5ad24f7ad3914fe2b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86787
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -33,6 +33,7 @@ The following PHP interfaces that have previously been marked as deprecated with
 - :php:`\TYPO3\CMS\Core\Domain\Repository\PageRepositoryInitHookInterface`
 - :php:`\TYPO3\CMS\Core\Domain\Repository\PageRepositoryGetPageHookInterface`
 - :php:`\TYPO3\CMS\Extbase\Mvc\View\ViewResolverInterface`
+- :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectGetDataHookInterface`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectGetImageResourceHookInterface`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectOneSourceCollectionHookInterface`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectStdWrapHookInterface`
```

</details>

**Comment by linawolf** [comment]
Was never mentioned
