### ISSUE TITLE
[!!!][TASK] Remove deprecated ContentObjectPostInitHookInterface

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1138]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/1636c98e4df2ab7a3a9ef2d0b358e03eb0eea151)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated ContentObjectPostInitHookInterface

Resolves: #105471
Related: #105377
Related: #102581
Releases: main
Change-Id: Ib0a69df206c9f8343c867f4a6760695a10c98d13
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86786
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -36,6 +36,7 @@ The following PHP interfaces that have previously been marked as deprecated with
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectGetDataHookInterface`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectGetImageResourceHookInterface`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectOneSourceCollectionHookInterface`
+- :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectPostInitHookInterface`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectStdWrapHookInterface`
 
 The following PHP interfaces changed:
```

</details>

**Comment by linawolf** [comment]
Was never mentioned
