### ISSUE TITLE
[BUGFIX] Show number of total records found in EXT:indexed_search

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1141]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/dd868a232f866bdd770a0180f37c72d09cfffda9)
:busts_in_silhouette: Authored by Garvin Hicking gh@faktor-e.de
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[BUGFIX] Show number of total records found in EXT:indexed_search

With the refactorings in #102925 and #102945 the total number
of search results was referred to in `result.pagination.totalAmount`.

However due to the Slice-pagination used, that variable will
not contain the right contents and needs to be replaced with
`result.count`.

This change adapts the default indexedsearch Search.html template
and adjusts the Changelog entry.

Resolves: #104861
Related: #102925
Related: #102945
Releases: main, 13.4
Change-Id: Ia7d8d42d7884f776d996318c75c115722433f564
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86704
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Mogens Fiebrandt <mogens.fiebrandt@googlemail.com>
Reviewed-by: Mogens Fiebrandt <mogens.fiebrandt@googlemail.com>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-102925-TemplateChangesInIndexedSearch.rst</summary>

```diff
@@ -51,7 +51,7 @@ JavaScript via :html:`<f:asset.script>`:
 ..  code-block:: html
 
     <f:sanitize.html>
-        <f:translate key="displayResults" arguments="{0: result.pagination.startRecordNumber, 1: result.pagination.endRecordNumber, 2: result.pagination.totalAmount}" />
+        <f:translate key="displayResults" arguments="{0: result.pagination.startRecordNumber, 1: result.pagination.endRecordNumber, 2: result.count}" />
     </f:sanitize.html>
 
 `is:pageBrowsing` has been replaced with a new Fluid partial file:
```

</details>

<details>
<summary>13.0/Breaking-102945-PaginationOfIndexedSearchReplaced.rst</summary>

```diff
@@ -39,7 +39,7 @@ Migration
 ..  code-block:: html
 
     <f:sanitize.html>
-        <f:translate key="displayResults" arguments="{0: result.pagination.startRecordNumber, 1: result.pagination.endRecordNumber, 2: result.pagination.totalAmount}" />
+        <f:translate key="displayResults" arguments="{0: result.pagination.startRecordNumber, 1: result.pagination.endRecordNumber, 2: result.count}" />
     </f:sanitize.html>
 
 `is:pageBrowsing` has been replaced with a new Fluid partial file:
```

</details>

**Comment by linawolf** [comment]
No need to document
