### ISSUE TITLE
[!!!][TASK] Remove RegularExpressionValidator option "errorMessage"

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1143]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/57f531519976630615e92a4b40c9e2c0a36ab96b)
:busts_in_silhouette: Authored by Torben Hansen derhansen@gmail.com
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove RegularExpressionValidator option "errorMessage"

The `errorMessage` validator option has been removed.

Resolves: #105481
Related: #102326
Related: #105377
Releases: main
Change-Id: I9a745173f3b0c93ac03ca6e7a6384f4e12eacba8
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86798
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -226,6 +226,10 @@ The following event has been removed:
 
 - :php:``
 
+The following extbase validator options have been removed:
+
+- :php:`errorMessage` in :php:`TYPO3\CMS\Extbase\Validation\Validator\RegularExpressionValidator`
+
 The following fallbacks have been removed:
 
 - Accepting arrays returned by :php:`readFileContent()` in Indexed Search external parsers
```

</details>

**Comment by linawolf** [comment]
Was never mentioned
