### ISSUE TITLE
[!!!][TASK] Remove deprecated XLIFF files

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1145]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/51dc4c07a155d74cecc5fad37c1d522e404717df)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Garvin Hicking gh@faktor-e.de

## Commit message

[!!!][TASK] Remove deprecated XLIFF files

Resolves: #105484
Related: #105377
Related: #102834
Releases: main
Change-Id: I049617fb71fa576e90e544a5564da29a6a5bcfe9
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86800
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Nikita Hovratov <nikita.h@live.de>
Reviewed-by: Nikita Hovratov <nikita.h@live.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -299,6 +299,11 @@ The following dependency injection service alias has been removed:
 
 - :yaml:`@x.y`
 
+The following localization XLIFF files have been removed:
+
+- :file:`EXT:backend/Resources/Private/Language/locallang_db_new_content_el.xlf`
+- :file:`EXT:frontend/Resources/Private/Language/Database.xlf`
+
 Impact
 ======
 
```

</details>

**Comment by linawolf** [comment]
These were never mentioned
