### ISSUE TITLE
[TASK] Add note on removal of FileRepository->findFileReferenceByUid()

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1151]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/cd1644789784462e7107b60dd63affde0a0e8aee)
:busts_in_silhouette: Authored by Martin Kutschker noreply@example.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[TASK] Add note on removal of FileRepository->findFileReferenceByUid()

FileRepository->findFileReferenceByUid() has been removed and was
not yet mentioned in the changelog entry.

Also, the extension scanner has been adapted to find this usage.

Releases: main, 13.4
Resolves: #105535
Related: #101948
Change-Id: I9fbe4028d42465face3507bf051325b4d264b9a0
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86876
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-101948-FileBasedAbstractRepositoryClassRemoved.rst</summary>

```diff
@@ -41,6 +41,10 @@ that arose around :php:`AbstractRepository`.
 extend from this class anymore, as they only include the methods required for
 their purpose, and are now completely strictly typed.
 
+Additionally, :php:`FileRepository` has been cleaned up by removing
+:php:`findFileReferenceByUid()` as it is only a wrapper to
+:php:`ResourceFactory::getFileReferenceObject()`
+
 
 Impact
 ======
@@ -51,6 +55,8 @@ implementing PHP repositories :php:`FileRepository` and
 
 PHP extensions that derive from the :php:`AbstractRepository` will stop working.
 
+Code that used :php:`FileRepository::findFileReferenceByUid()` will break.
+
 
 Affected installations
 ======================
@@ -74,4 +80,23 @@ It is highly recommended to not use any of these classes, but rather stick
 to high-level API of FAL, such as :php:`ResourceFactory`, :php:`File`
 or :php:`ResourceStorage`.
 
+Replace former calls to :php:`FileRepository::findFileReferenceByUid()` like:
+
+..  code-block:: php
+
+    $fileRepository = GeneralUtility::makeInstance(FileRepository::class);
+    $reference = $fileRepository->findFileReferenceByUid($referenceUid);
+
+by using the :php:`ResourceFactory` with new code like:
+
+..  code-block:: php
+
+    $resourceFactory = GeneralUtility::makeInstance(ResourceFactory::class);
+    $reference = $resourceFactory->getFileReferenceObject($referenceUid);
+
+..  note::
+
+    Ideally use dependency injection instead of :php:`GeneralUtility::makeInstance()` to
+    retrieve the instance for :php:`ResourceFactory`.
+
 .. index:: FAL, PHP-API, PartiallyScanned, ext:core
```

</details>

**Comment by linawolf** [comment]
Not mentioned
