### ISSUE TITLE
[DOCS] Add hint about "temp." TypoScript top-level object

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1162]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/3a42fd3456ffaee433bf2e4e45c04ba310be914e)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[DOCS] Add hint about "temp." TypoScript top-level object

Frontend TypoScript 'temp.' was removed after parsing
with the pre-v12 parser. The v12 parser does not do this
anymore. Unsetting 'temp.' never really made much
sense, and for instance had the side effects that
the object browser could never show it. We thus
decided to not add this special handling again, but
to document this subtle change instead.

Note 'styles.' had the same handling as 'temp.'
until v7, where its special handling was removed
without further impact.

Resolves: #105599
Related: #97816
Related: #60567
Releases: main, 13.4, 12.4
Change-Id: I5b2773317b7d69114bcc6da5d38439d93c633e34
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/86986
Tested-by: Oliver Thiele <oliver.thiele@typo3.org>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Oliver Thiele <oliver.thiele@typo3.org>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Breaking-97816-TypoScriptSyntaxChanges.rst</summary>

```diff
@@ -313,5 +313,14 @@ a whitespace between :typoscript:`=` and :typoscript:`<`:
 
     lib.nav.wrap = <ul id="nav">|</ul>
 
+Frontend TypoScript `temp.` top level object
+--------------------------------------------
+
+The Frontend TypoScript related top level object :typoscript:`temp` had special
+functionality until v12: Any TypoScript defined within was "temporary" at parse time
+and unset afterwards. It was not cached and could not be used as reference
+(:typoscript:`=<` operator). This special meaning has been removed, the key
+:typoscript:`temp` now works just like any other top level key.
+
 
 .. index:: Backend, Frontend, TSConfig, TypoScript, NotScanned, ext:core
```

</details>

**Comment by linawolf** [comment]
Already documented
