### ISSUE TITLE
[FEATURE] Allow modifying fetched page content

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1165]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/a255e74e961de0ddbf9dc5c3f06d6d8145d7bdf5)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[FEATURE] Allow modifying fetched page content

With #103894, the `PageContentFetchingProcessor` was introduced.
It allows to easily fetch and provide page content based on
the selected page layout in fluid templates.

While this makes the configuration effort a lot easier
for the most common use cases, it fails to provide
any possibility for custom adjustments.

For example, EXT:content_block needs to provide
an additional condition to the select configuration,
to hide "inline content elements" [2].

Since this is not directly possible when using the
`PageContentFetchingProcessor` [1], the new PSR-14
AfterContentHasBeenFetchedEvent is introduced as
an exceptional feature. The event therefore allows
to modify the fetched page content.

Therefore, instead of using user functions
to manipulate SQL statements, e.g.

page.20 = CONTENT
page.20 {
    table = tt_content
    select {
        orderBy = sorting
        where = colPos=0
        where.postUserFunc = TYPO3\CMS\ContentBlocks\UserFunction\ContentWhere->extend
    }
}

one can now use the event to post
process the fetched content:

public function __invoke(AfterContentHasBeenFetchedEvent $event): void
{
    foreach ($event->groupedContent['main']['records'] as $key => $record) {
        if ($record->has('parent_field_name') && (int)($record->get('parent_field_name') ?? 0) > 0) {
            unset($event->groupedContent['main']['records'][$key]);
        }
    }
}

[1] https://github.com/FriendsOfTYPO3/content-blocks/issues/273
[2] https://docs.typo3.org/p/friendsoftypo3/content-blocks/main/en-us/API/NestedContentElements/Index.html#preventing-output-in-frontend

Resolves: #105638
Related: #103894
Releases: main, 13.4
Change-Id: I356b9232d50a085393c3ce0c63182409eb8a0527
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/87058
Reviewed-by: Nikita Hovratov <nikita.h@live.de>
Tested-by: Nikita Hovratov <nikita.h@live.de>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.4.x/Feature-105638-ModifyFetchedPageContent.rst</summary>

```rst
..  include:: /Includes.rst.txt

..  _feature-105638-1732034075:

==============================================
Feature: #105638 - Modify fetched page content
==============================================

See :issue:`105638`

Description
===========

With :issue:`103894` the new data processor :ref:`PageContentFetchingProcessor <feature-103894-1716544976>`
has been introduced, to allow fetching page content based on the current page
layout, taking the configured :php:`SlideMode` into account.

Fetching content has previously mostly been done via the `Content` content
object. A common example looked like this:

..  code-block:: typoscript

    page.20 = CONTENT
    page.20 {
        table = tt_content
        select {
            orderBy = sorting
            where = colPos=0
        }
    }

As mentioned in the linked changelog, using the `page-content` data processor,
this can be simplified to:

..  code-block:: typoscript

    page.20 = page-content

This however reduces the possibility to modify the select configuration
(SQL statement), used to define which content should be fetched, as this
is automatically handled by the data processor. However, there might be some
use cases in which the result needs to be adjusted, e.g. to hide specific
page content, like it's done by :ref:`EXT:content_blocks <friendsoftypo3/content-blocks:cb-nesting-prevent-output-fe>`
for child elements. For such use cases, the new PSR-14 :php:`AfterContentHasBeenFetchedEvent`
has been introduced, which allows to manipulate the list of fetched page
content.

The following member properties of the event object are provided:

- :php:`$groupedContent`: The fetched page content, grouped by their column - as defined in the page layout
- :php:`$request`: The current request, which can be used to e.g. access the page layout in question

Example
=======

The event listener class, using the PHP attribute :php:`#[AsEventListener]` for
registration, removes some of the fetched page content elements based on
specific field values.

..  code-block:: php
    :caption: my_extension/Classes/EventListener/MyEventListener.php

    use TYPO3\CMS\Core\Attribute\AsEventListener;
    use TYPO3\CMS\Frontend\Event\AfterContentHasBeenFetchedEvent;

    final class MyEventListener
    {
        #[AsEventListener]
        public function removeFetchedPageContent(AfterContentHasBeenFetchedEvent $event): void
        {
            foreach ($event->groupedContent as $columnIdentifier => $column) {
                foreach ($column['records'] ?? [] as $key => $record) {
                    if ($record->has('parent_field_name') && (int)($record->get('parent_field_name') ?? 0) > 0) {
                        unset($event->groupedContent[$columnIdentifier]['records'][$key]);
                    }
                }
            }
        }
    }

Impact
======

Using the new PSR-14 :php:`AfterContentHasBeenFetchedEvent`, it's possible
to manipulate the page content, which has been fetched by the
:php:`PageContentFetchingProcessor`, based on the page layout and
corresponding columns configuration.

..  index:: Frontend, PHP-API, TypoScript, ext:frontend

```

</details>

## :heavy_division_sign: Modified files

<details>
<summary>13.2/Feature-103894-AdditionalPropertiesForColumnsInPageLayouts.rst</summary>

```diff
@@ -43,6 +43,9 @@ is introduced for the frontend rendering,
 which fetches all content for a page and respecting the settings from the
 page layout.
 
+The new data processor allows to manipulate the fetched page content via
+the PSR-14 :ref:`AfterContentHasBeenFetchedEvent <feature-105638-1732034075>`.
+
 
 Impact
 ======
```

</details>

<details>
<summary>13.4.x/Index.rst</summary>

```diff
@@ -24,11 +24,12 @@ None since TYPO3 v13.4.0 LTS release.
 Features
 ========
 
-None since TYPO3 v13.4.0 LTS release.
-
-..  attention::
+..  toctree::
+    :maxdepth: 1
+    :titlesonly:
+    :glob:
 
-    New features are not planned after the TYPO3 v13.4.0 LTS release.
+    Feature-*
 
 Deprecation
 ===========
```

</details>

**Comment by linawolf** [comment]
Needs to be documented in TSref after event is merged
