### ISSUE TITLE
[!!!][TASK] Remove deprecated doctrine driverMiddleware handling

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1171]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ee5e20b430ddddf4a738140cb2c9e2655026ad2f)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove deprecated doctrine driverMiddleware handling

Remove the previously deprecated doctrine driverMiddleware
configuration based on class strings.

Resolves: #105709
Related: #102586
Related: #105377
Releases: main
Change-Id: I974ed8f8cf73d578e156cc4e121bc2584ef4181c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/87255
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>14.0/Breaking-105377-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -215,9 +215,10 @@ The following global option handling have been dropped and are ignored:
 - :php:`$GLOBALS['TYPO3_CONF_VARS']['BE']['defaultPageTSconfig']` :ref:`(Deprecation entry) <deprecation-101799-1693397542>`
 - :php:`$GLOBALS['TYPO3_CONF_VARS']['BE']['defaultUserTSconfig']` :ref:`(Deprecation entry) <deprecation-101807-1693474000>`
 
-The following global variables have been removed:
+The following global variables have been changed:
 
-- :php:`$GLOBALS['X']`
+- :php:`$GLOBALS['TYPO3_CONF_VARS']['DB']['Connections']['SecondDatabase']['driverMiddlewares']['driver-middleware-identifier']`
+  must be an array, not a class string :ref:`(Deprecation entry) <deprecation-102586-1701536568>`
 
 The following hooks have been removed:
 
```

</details>

**Comment by linawolf** [comment]
Never mentioned
