### ISSUE TITLE
[FEATURE] Add timezone option to DateViewHelper

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#1178]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/74bd1209127dae510a52cfd187339204d9d2cfb6)
:busts_in_silhouette: Authored by Georg Ringer georg.ringer@gmail.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Add timezone option to DateViewHelper

The argument `timezone´ can be used to render a date
with a different timezone.

Resolves: #92760
Releases: main
Change-Id: Id164cc7783b69331e848b9fd37056e2694c9062f
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/72995
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>14.0/Feature-92760-ConfigurableTimezoneForDateViewHelper.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-92760-1733907198:

==========================================================
Feature: #92760 - Configurable timezone for DateViewHelper
==========================================================

See :issue:`92760`

Description
===========

A new option :html:`timezone` has been added to the :php:`DateViewHelper` to render
a date with the provided time zone.

.. code-block:: html

    <f:format.date format="d.m.Y g:i a" date="1640995200" /><br>
    <f:format.date format="d.m.Y g:i a" date="1640995200" timezone="America/Phoenix" /><br>
    <f:format.date format="d.m.Y g:i a" date="1640995200" timezone="Indian/Mayotte" />

will render:

.. code-block:: html

    01.01.2022 12:00 am
    31.12.2021 5:00 pm
    01.01.2022 3:00 am

Impact
======

Using the new :html:`timezone` option, it's now possible to set a specific
time zone for the the :php:`DateViewHelper`.

.. index:: Fluid, ext:fluid

```

</details>

**Comment by linawolf** [comment]
Will be documented automatically
