### ISSUE TITLE
[!!!][FEATURE] Use LanguageAspect in QuerySettings for Extbase

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#132]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/fda25134846a80f3b213d716a5621a7ce04db8c3)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[!!!][FEATURE] Use LanguageAspect in QuerySettings for Extbase

This change adapts the QuerySettings functionality
for Extbase in v12 to allow to work with a LanguageAspect
which contains all information regarding the language ID
and the overlay mode.

For this reason, the following method definitions are removed
within Extbase's QuerySettingsInterface

- setLanguageOverlayMode()
- getLanguageOverlayMode()
- setLanguageUid()
- getLanguageUid()

However, it is still possible to use the existing methods
on the QuerySettings implementation of TYPO3
for TYPO3 v12.

It is now recommended to use ->getLanguageAspect()
and ->setLanguageAspect().

This change is a pre-requisite to extend language
handling across TYPO3 and Extbase.

Resolves: #97926
Releases: main
Change-Id: I38a685fcfdb98d5ec3c82b02e6cc78df12062fa0
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75093
Tested-by: core-ci <typo3@b13.com>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-97926-ExtbaseQuerySettingsMethodsRemoved.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-97926-1657726187:

========================================================
Breaking: #97926 - Extbase QuerySettings methods removed
========================================================

See :issue:`97926`

Description
===========

Extbase's Persistence functionality is basing ORM queries on certain settings
usually fetched from :php:`QuerySettingsInterface`, with a default
implementation :php:`Typo3QuerySettings`.

The interface itself has changed that it now requires two new methods:

:php:`QuerySettingsInterface::getLanguageAspect(): LanguageAspect`
:php:`QuerySettingsInterface::setLanguageAspect(LanguageAspect $aspect)`

The LanguageAspect covers both the overlay functionality and setting the
language ID.

For this reason, the following methods are removed from
:php:`QuerySettingsInterface`:

- :php:`QuerySettingsInterface::getLanguageOverlayMode()`
- :php:`QuerySettingsInterface::setLanguageOverlayMode($languageOverlayMode)`
- :php:`QuerySettingsInterface::getLanguageUid()`
- :php:`QuerySettingsInterface::setLanguageUid($languageUid)`

All adaptions have been made to the default implementation in
`Typo3QuerySettings`, however the removed methods from the interface are kept
within the implementation to avoid fatal PHP errors.


Impact
======

Any custom implementation of :php:`QuerySettingsInterface` needs to implement
the newly defined methods of the interface.


Affected installations
======================

TYPO3 installations with custom Extbase extensions dealing with QuerySettings
that are adjusted with the methods used above.


Migration
=========

Switch the affected extensions via PHP to calling the newly added methods, as this is
how TYPO3 Core behaves the most reliable.

.. index:: PHP-API, FullyScanned, ext:extbase

```

</details>

<details>
<summary>12.0/Feature-97926-ConfigureExtbasePersistenceLanguageViaLanguageAspect.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-97926-1657726554:

===========================================================================
Feature: #97926 - Configure Extbase Persistence Language via LanguageAspect
===========================================================================

See :issue:`97926`

Description
===========

Extbase's Persistence functionality allows to configure the ORM queries via QuerySettings.

QuerySettings now accept to use a custom LanguageAspect (known from the Context API)
to define the language ID and the overlay behaviour.

This is more consistent to other places within TYPO3 Core to define translation behaviour when
querying records.


Impact
======

You can now specify a custom Language Aspect per query as defined in the query settings
in any Repository class:

Example to use the fallback to the default language when working with overlays:

.. code-block:: php

        $query = $this->createQuery();
        $query->getQuerySettings()->setLanguageAspect(new LanguageAspect(2, 2, LanguageAspect::OVERLAYS_MIXED));

.. index:: PHP-API, ext:extbase
```

</details>

**Comment by DavidBruchmann** [comment]
The extension blog_example is not concerned as related features are not used.
