### ISSUE TITLE
[DOCS] Fix typo in title and filename

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#148]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/242735f15d34dca2e36c81a4bc210be9bd0a162e)
:busts_in_silhouette: Authored by Česlav Przywara noreply@example.com
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[DOCS] Fix typo in title and filename

Releases: main, 11.5
Resolves: #98115
Related: #92118
Change-Id: Ibcd5fa26155dbb36216422e1c806c9a4035d878f
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75409
Tested-by: core-ci <typo3@b13.com>
Tested-by: Chris Müller <typo3@krue.ml>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Chris Müller <typo3@krue.ml>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>11.0/Breaking-92118-TCACtrlThumbnailSettingDropped.rst</summary>

```rst
.. include:: /Includes.rst.txt

=====================================================
Breaking: #92118 - TCA ctrl thumbnail setting dropped
=====================================================

See :issue:`92118`

Description
===========

The TCA setting :php:`$GLOBALS['TCA'][$aTableName]['ctrl']['thumbnail']` has been dropped.


Impact
======

Setting the control field for a custom table has no effect anymore.


Affected Installations
======================

The setting has been used in the :guilabel:`List` module for tables with image fields to render a preview
of attached images. It has been used for :php:`tt_content` in core versions until TYPO3 v7.
There are probably not many extensions using the setting. The :guilabel:`List` module will
no longer show preview images for rendered rows.


Migration
=========

Drop this setting during extension clean up. The setting is simply ignored, no PHP error will be thrown.

.. index:: TCA, NotScanned, ext:recordlist

```

</details>

**Comment by sypets** [comment]
redirects were added for changelog
