### ISSUE TITLE
[DOCS] Correct title and filename of breaking RST

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#149]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/85c2b1d5172abfa9f663b9c23677d9cf2aaa5150)
:busts_in_silhouette: Authored by Chris Müller typo3@krue.ml
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[DOCS] Correct title and filename of breaking RST

Resolves: #98131
Related: #97701
Releases: main
Change-Id: I15408037432516d67e26853b34cfaf9fa320e75a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75426
Tested-by: core-ci <typo3@b13.com>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-97701-RemovedTsConfigOptionDisableNewContentElementWizard.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-97701-1655154047:

=========================================================================
Breaking: #97701 - TSconfig option disableNewContentElementWizard removed
=========================================================================

See :issue:`97701`

Description
===========

The TSconfig option :typoscript:`mod.web_layout.disableNewContentElementWizard`
has been used to explicitly disable the content element wizard. When set,
a new Content Element of type "Text" was created by default, which was then
changed to a different Content Type.

Along with this the option :typoscript:`mod.newContentElementWizard.override` has
been removed, as it served a similar purpose to override the route name itself.


Impact
======

Both TSconfig options have no effect anymore. TYPO3 behaves as if the options
were never set.


Affected installations
======================

TYPO3 installations having one of these options explicitly enabled.


Migration
=========

Remove the TSconfig settings as they have no effect anymore.

Instead, use other TSconfig options to adapt the "New Content Element Wizard"
to your needs. You can find according examples in
:file:`EXT:frontend/Configuration/page.tsconfig`.

It is also possible to create a custom backend route in your extension code
to reimplement both functionalities in a custom TYPO3 Extension, if this option
is still relevant for you.

If you overwrite the fluid template :file:`EXT:backend/Resources/Private/Partials/PageLayout/Record.html`
you have to adjust your template accordingly and remove the "if" condition
checking for `{item.column.context.drawingConfiguration.showNewContentWizard}`.

.. index:: Backend, Fluid, TSConfig, PartiallyScanned, ext:backend

```

</details>

**Comment by sypets** [comment]
Needs redirects

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97701-RemovedTsConfigOptionDisableNewContentElementWizard.html


=> https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0//Breaking-97701-RemovedTsConfigOptionShowNewContentWizard.html

**Comment by linawolf** [comment]
redirect is in place
