### ISSUE TITLE
[!!!][TASK] Remove support for concat/compress of JS+CSS in BE

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#152]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ed88670c6e3a469789fe37fc40098c40f1be3fe7)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[!!!][TASK] Remove support for concat/compress of JS+CSS in BE

This change removes the support for supporting concatenation and
compression of CSS + JS assets in TYPO3 Backend.

This feature was actually introduced back in TYPO3 v4.x because of
limitations of Internet Explorer (max of 31 CSS files per HTML page),
and before the introduction of bundlers + compressors for TYPO3 Core,
as well as HTTP/2 support and optimized caching.

For this reason, all the functionality within PageRenderer and
ResourceCompressor is removed in TYPO3, without any option to
activate this.

TYPO3 already bundles CSS in one single file, and JS is nowadays
loaded with bundlers, and loaders within JS modules in TYPO3 Backend.

For TYPO3 Frontend, this functionality is still available for
the time being.

Resolves: #98100
Releases: main
Change-Id: Id45714d4660080da6f4a1d9d6ae277930c0bbc48
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75389
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Jörg Bösche <typo3@joergboesche.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-98100-CompressionAndConcatenationOfJavaScriptAndCSSFilesForBackendRemoved.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-98100-1659877890:

================================================================================================
Breaking: #98100 - Compression and Concatenation of JavaScript and CSS files for Backend removed
================================================================================================

See :issue:`98100`

Description
===========

TYPO3 Backend introduced Compression and Concatenation of CSS and JavaScript
files in version 4.3 due to limitations of Internet Explorer 9 and lower.
Since then, TYPO3 Backend uses JavaScript modules and loading via RequireJS and
ES Modules, as well as CSS compression and concatenation by default during
build time.

For this reason, this feature is removed from the actual ResourceCompressor,
which only works in TYPO3 Frontend rendering now via the common TypoScript
settings.


Impact
======

A custom handler for concatenation and compression of JS and CSS files has
no effect anymore when registered in a third-party extension.

This could previously be configured via

* :php:`$GLOBALS['TYPO3_CONF_VARS']['BE']['jsConcatenateHandler']`
* :php:`$GLOBALS['TYPO3_CONF_VARS']['BE']['jsCompressHandler']`
* :php:`$GLOBALS['TYPO3_CONF_VARS']['BE']['cssConcatenateHandler']`
* :php:`$GLOBALS['TYPO3_CONF_VARS']['BE']['cssCompressHandler']`

Additionally, it was previously possible to configure a custom root path
in ResourceCompressor via :php:`setRootPath($rootPath)`, which has been removed
as well.

Affected installations
======================

TYPO3 installations with custom JS and CSS handlers for TYPO3 Backend routines
via custom extensions which is highly unlikely.


Migration
=========

None, as component-based CSS files and module-based JS files are loaded already
anyway, and the performance impact of loading multiple files is rather low due
to optimized ".htaccess" configurations already, and through bundling all CSS for
core in optimized files as well.

.. index:: LocalConfiguration, PHP-API, FullyScanned, ext:backend

```

</details>

**Comment by brotkrueml** [comment]
Custom backend compression/concatenation handlers are not mentioned in docs at all. `setRootPath()` only in v6.2 docs as part of an API overview.
