### ISSUE TITLE
[!!!][TASK] Remove jQuery in Popover

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#158]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/08e7dc7012d5c2e86244a3811f10fdcfb9859e20)
:busts_in_silhouette: Authored by Andreas Fernandez a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Andreas Fernandez a.fernandez@scripting-base.de

## Commit message

[!!!][TASK] Remove jQuery in Popover

The support for jQuery in the module `@typo3/backend/popover` has been
dropped. Passing jQuery elements to the module's methods is not possible
anymore.

Resolves: #98261
Releases: main
Change-Id: I8716ad1762d67faf51b67eacec82435690f5b097
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75535
Tested-by: core-ci <typo3@b13.com>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-98261-RemovedJQueryInPopoverModule.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-98261-1662389392:

===================================================
Breaking: #98261 - Removed jQuery in Popover module
===================================================

See :issue:`98261`

Description
===========

The support for jQuery in the module :js:`@typo3/backend/popover` has been
dropped. Passing jQuery elements to the module's methods is not possible anymore.

This affects the following methods:

* :js:`popover()`
* :js:`setOptions()`
* :js:`show()`
* :js:`hide()`
* :js:`destroy()`
* :js:`toggle()`


Impact
======

Calling any of the aforementioned methods with passing a jQuery-based object is
undefined and will lead to JavaScript errors.


Affected installations
======================

All 3rd party extensions using the API of the :js:`@typo3/backend/popover` module
are affected.


Migration
=========

The method :js:`popover()` accepts either an object of type :js:`HTMLElement`
or a collection of type :js:`NodeList`, where all elements must be of type
:js:`HTMLElement`.

Any other method accepts objects of type :js:`HTMLElement` only.

Example:

.. code-block:: js

    // Before
    Popover.popover($('button.popover'));

    // After
    Popover.popover(document.querySelectorAll('button.popover'));

.. index:: Backend, JavaScript, NotScanned, ext:backend

```

</details>

**Comment by linawolf** [comment]
Was not mentioned in the docs
