### ISSUE TITLE
[!!!][TASK] Remove possibility to pre-define link titles in link browser

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#160]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/df53c96b7cefc4d9c84c88725f0164bc9cc70142)
:busts_in_silhouette: Authored by Andreas Fernandez a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Andreas Fernandez a.fernandez@scripting-base.de

## Commit message

[!!!][TASK] Remove possibility to pre-define link titles in link browser

Back in the old HTMLArea it was possible to pre-define a link title in
the `classesAnchor` configuration which got applied after selecting the
CSS class for a link. This feature was migrated to EXT:rte_ckeditor in
TYPO3 v8.

From an SEO and accessibility point of view, this doesn't make much sense
as this would lead to repetitive usage of the same link title, not
helping much at all.

For those reasons, the possibilities to

* pre-define a link title
* make the link title field readonly

have been removed without substitution.

Resolves: #98275
Releases: main
Change-Id: I775f097c610ca14d3c0b20b1c04f62866a7fddc1
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75629
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Susanne Moog <look@susi.dev>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Susanne Moog <look@susi.dev>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-98275-RemovedPreDefinedLinkTitleAttributesInRTELinkBrowser.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-98275-1662540769:

================================================================================
Breaking: #98275 - Removed pre-defined link title attributes in RTE link browser
================================================================================

See :issue:`98275`

Description
===========

Back in the old HTMLArea it was possible to pre-define a link title in the
`classesAnchor` configuration which got applied after selecting the CSS class
for a link. This feature was migrated to EXT:rte_ckeditor in TYPO3 v8.

From an SEO and accessibility point of view, this doesn't make much sense as
this would lead to repetitive usage of the same link title, not helping much at
all.

For those reasons, the possibilities to

* pre-define a link title
* make the link title field read-only

have been removed without substitution.


Impact
======

Pre-configuring a link title based on the applied CSS class is not possible
anymore. Also, configuring the link title field to be read-only is not possible
anymore.


Affected installations
======================

All installations configuring :yaml:`classesAnchor.*.linkText` or
:yaml:`buttons.link.properties.title.readOnly` in an RTE configuration file are
affected.


Migration
=========

There is no migration available. Removing the obsolete settings
:yaml:`classesAnchor.*.linkText` and :yaml:`buttons.link.properties.title.readOnly`
is recommended.

.. index:: Backend, RTE, NotScanned, ext:rte_ckeditor

```

</details>

**Comment by linawolf** [comment]
The settings were not mentioned
