### ISSUE TITLE
[FEATURE] Add TypeConverter for enums

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#162]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/39a05afda4f6d193186c6c76b881eb8539260497)
:busts_in_silhouette: Authored by Matthias Vogel typo3@kanti.de
:heavy_check_mark: Merged by Anja Leichsenring aleichsenring@ab-softlab.de

## Commit message

[FEATURE] Add TypeConverter for enums

With PHP 8.1 we got Enums, to use them also in our extbase actions,
a new TypeConverter is added with this patch.

The EnumConverter is automatically used if the target type is an enum.

Resolves: #98171
Releases: main
Change-Id: Ic95bb69f2a02580f86878cd14a3f608ed3b474f6
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75512
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Feature-98171-AddExtbaseTypeConverterForEnums.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-98171-1660910151:

=====================================================
Feature: #98171 - Add Extbase TypeConverter for enums
=====================================================

See :issue:`98171`

Description
===========

Since PHP 8.1 provides enums, we can also use them in our Extbase actions.
A new TypeConverter
:php:`\TYPO3\CMS\Extbase\Property\TypeConverter\EnumConverter`
was added with this feature.


Example
=======

Given an enum like this one:

.. code-block:: php

    enum ClosedStates
    {
        case Hide;
        case Show;
        case All;
    }

We can now use it like this in any Extbase action:

.. code-block:: php

    public function overviewAction(ClosedStates $closed = ClosedStates::Hide): ResponseInterface
    {
        // ...
    }

The URL argument can be send as `[closed]=Show` and is automatically converted to an instance of :php:`ClosedStates::Show`


Impact
======

Enums can now be used as Extbase action arguments.

.. index:: PHP-API, ext:extbase

```

</details>

**Comment by linawolf** [comment]
The specific typeconverters are not mentioned in the docs
