### ISSUE TITLE
[!!!][TASK] Remove jQuery in PersistentStorage

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#165]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ac0a69174450918e58ee7b7c51469e337e213487)
:busts_in_silhouette: Authored by Andreas Fernandez a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Benjamin Franzke bfr@qbus.de

## Commit message

[!!!][TASK] Remove jQuery in PersistentStorage

All requests are changed to use the AJAX API. Due to this, the return
type of some methods is changed, resulting in a breaking change.

There is one exception: due to how the PersistentStorage module is
designed, the private method `loadFromServer()` send a synchronous
request to the server. In the long run, this must become an asynchronous
request but requires more refactorings as this affects all consumers.

Resolves: #98193
Releases: main
Change-Id: I314e63604c22753925daca29d7eeb25420832352
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75537
Tested-by: core-ci <typo3@b13.com>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Benjamin Franzke <bfr@qbus.de>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Benjamin Franzke <bfr@qbus.de>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-98193-PersistentStorageModuleReturnsPromises.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-98193-1661262696:

=============================================================
Breaking: #98193 - Persistent storage module returns Promises
=============================================================

See :issue:`98193`

Description
===========

The methods of the JavaScript module :js:`@typo3/backend/storage/persistent` now
return native :js:`Promise` objects where jQuery-based promises were returned
previously.

This requires migration of any code using the returned jQuery promise.

This affects the following methods:

* :js:`set()`
* :js:`addToList()`
* :js:`unset()`


Impact
======

Using callbacks of jQuery-based promises (:js:`done`, :js:`fail` or :js:`always`)
will trigger JavaScript errors, as native :js:`Promise` objects don't know these
callbacks.


Affected installations
======================

All extensions using any of the aforementioned methods and relying on the
returned objects are affected.


Migration
=========

In most cases, changing the method name of the callback is sufficient, where the
following rules apply:

+-----------------------+-----------------+
| jQuery-based callback | Native callback |
+=======================+=================+
+-----------------------+-----------------+
| done()                | then()          |
+-----------------------+-----------------+
| fail()                | catch()         |
+-----------------------+-----------------+
| always()              | finally()       |
+-----------------------+-----------------+

.. index:: Backend, JavaScript, NotScanned, ext:backend

```

</details>

**Comment by linawolf** [comment]
This was never mentioned in the docs
