### ISSUE TITLE
[TASK] Remove _DEFAULT_PI_VARS from TypoScript

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#173]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/79459bb71c75d755c2b1318bc3fa13bbfdfe93df)
:busts_in_silhouette: Authored by linawolf 112@linawolf.de
:heavy_check_mark: Merged by Lina Wolf 112@linawolf.de

## Commit message

[TASK] Remove _DEFAULT_PI_VARS from TypoScript

With https://review.typo3.org/c/Packages/TYPO3.CMS/+/75655 the `AbstractPlugin` was made internal.

Option `_DEFAULT_PI_VARS` was only used in the `AbstractPlugin` and can therefore be removed from the TypoScript API.

Additionally `_LOCAL_LANG.[lang-key].[label-key]` now only works for Extbase plugins, the description needs to be adjusted.

Releases: main
Resolves: #98369
Change-Id: I2cf71542f02b5637e8bcf782843e7baa0cb54acd
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75772
Reviewed-by: Chris Müller <typo3@krue.ml>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Lina Wolf <112@linawolf.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Lina Wolf <112@linawolf.de>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Breaking-98281-MakeAbstractPluginInternal.rst</summary>

```diff
@@ -15,6 +15,10 @@ Extending the class :php:`\TYPO3\CMS\Frontend\Plugin\AbstractPlugin` is not a
 recommended way of developing Frontend plugins anymore. This class is not
 maintained anymore and may be removed in future versions without further notice.
 
+The TypoScript property :typoscript`plugin.tx_myextension_pi1._DEFAULT_PI_VARS`
+has only been used in the class :php:`AbstractPlugin`. It is therefore not public
+API anymore.
+
 
 Impact
 ======
@@ -23,6 +27,9 @@ Plugins based on :php:`\TYPO3\CMS\Frontend\Plugin\AbstractPlugin` will
 continue to function. However, there will be PHP warnings about using internal
 code displayed in most IDEs.
 
+:typoscript`_DEFAULT_PI_VARS` has been removed from syntax highlighting as it is
+not public API anymore.
+
 
 Affected installations
 ======================
```

</details>

**Comment by linawolf** [comment]
Already documented
