### ISSUE TITLE
[!!!][TASK] Upgrade to CodeMirror v6

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#176]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/cdf920a6ea56a530d6540e82548842aeb7a2739b)
:busts_in_silhouette: Authored by Benjamin Franzke bfr@qbus.de
:heavy_check_mark: Merged by Benjamin Franzke bfr@qbus.de

## Commit message

[!!!][TASK] Upgrade to CodeMirror v6

CodeMirror v6 is a major rewrite of CodeMirror v5.
Existing addons and language parsers need to be rewritten.
There is a compatibility layer for parsers though, which we
use for our TypoScript parser (which itself is based on
an old CodeMirror javascript parser).

A migration to a grammar based lexer (based on codemirror @lezer
infrastructure) would be desirable in future.

The TypoScript code completion code is adapted via a small shim
that calculates the line-oriented token-state from the
CodeMirror v6 syntax tree. Rewriting the code completer (which
also parses the object structure) has not been an option, without
also rewriting the TypoScript syntax highlighter.
Ideally, both the parser and the code completion would be based
on a modern lezer grammar based parser, allowing to perform
code completion on a proper TypoScript syntax tree.

CodeMirror v6 is authored as ES6 modules and can therefore
be integrated into our JavaScript importmap infrastructure,
without bundling.

Note that also JavaScript invoke instruction for exported functions
are adapted to allow for empty invoke() JavaScriptModule instructions
to call exported functions as plain function without a `this`-context.
Exported methods must not be called with the ES6 module passed
as this-value/context, as that is forbidden for ES6 module exports:
`JavaScriptModuleInstruction->create('@my/module.js', 'myExport')->invoke()`
instead of
`JavaScriptModuleInstruction->create('@my/module.js')->invoke('myExport')`.
This is needed to be able to use JavaScriptModuleInstruction's
for CodeMirror v6 function exports.

Commands executed:

  npm remove codemirror
  npm install \
    @lezer/common \
    @lezer/lr \
    @codemirror/autocomplete \
    @codemirror/commands \
    @codemirror/language \
    @codemirror/lint \
    @codemirror/search \
    @codemirror/state \
    @codemirror/view \
    @codemirror/lang-css \
    @codemirror/lang-html \
    @codemirror/lang-javascript \
    @codemirror/lang-json \
    @codemirror/lang-php \
    @codemirror/lang-sql \
    @codemirror/lang-xml \
    @codemirror/theme-one-dark
  npm run build

Releases: main
Resolves: #96575
Related: #96323
Change-Id: If4a323289144a1212b6fd93ebedd122a62b8052c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/73466
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Benjamin Franzke <bfr@qbus.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Benjamin Franzke <bfr@qbus.de>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-96575-UpdateToCodeMirror6.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-96575-1663324432:

=========================================
Breaking: #96575 - Update to CodeMirror 6
=========================================

See :issue:`96575`

Description
===========

TYPO3 Core now ships with CodeMirror v6.
CodeMirror is used as editor in the TYPO3 Backend for editing
HTML records, TypoScript templates and plaintext files in the file module.


Impact
======

Existing CodeMirror v5 addons and modes need to be adapted for CodeMirror v6
which brings a completely rewritten plugin infrastructure.


Affected installations
======================

TYPO3 Installations with third party extensions that register
custom CodeMirror addons or modes.


Migration
=========

Please consult https://codemirror.net/docs/migration/ for details on
CodeMirror migration itself.

The TYPO3 integration has been adapted to reflect the changed modes and
addons in the `T3editor` configuration files:

Adapt the mode configuration in :file:`Configuration/Backend/T3editor/Modes.php`
to use :php:`JavaScriptModuleInstruction` statements that pick ES6 module
for a specific language mode. A RequireJS module like
:js:`codemirror/mode/css/css` is now shipped in `@codemirror/lang-css`:

.. code-block:: php

   use TYPO3\CMS\Core\Page\JavaScriptModuleInstruction;

   return [
       'css' => [
           'module' => JavaScriptModuleInstruction::create('@codemirror/lang-css', 'css')->invoke(),
           'extensions' => ['css'],
       ],
   ];

Addons no longer bring :php:`cssFiles` or :php:`options`, but only consist
of a :php:`module` and an optional :php:`keymap` statement, as the `options`
interface is gone in CodeMirror v6 and stylesheets are to be embedded into
JavaScript.

See following example for the registration of the history addon via
:file:`Configuration/Backend/T3editor/Modes.php`:

.. code-block:: php

   use TYPO3\CMS\Core\Page\JavaScriptModuleInstruction;

   return [
       'history' => [
           'module' => JavaScriptModuleInstruction::create('@codemirror/commands', 'history')->invoke(),
           'keymap' => JavaScriptModuleInstruction::create('@codemirror/commands', 'historyKeymap'),
       ],
   ];


.. index:: Backend, JavaScript, NotScanned, ext:t3editor

```

</details>

**Comment by linawolf** [comment]
Will be solved by https://forge.typo3.org/issues/98432
