### ISSUE TITLE
[!!!][TASK] Require ServerRequestInterface in Extbase Request

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#180]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/088b745da7416610729b2109bc9de1200ccffdd0)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Benjamin Franzke bfr@qbus.de

## Commit message

[!!!][TASK] Require ServerRequestInterface in Extbase Request

The Extbase Request still had a fallback to fetch
the base Request from $GLOBALS. The base Request
is of course a hard dependency of the Extbase
Request, it should be actively hand over as
construct argument.

Change-Id: If0b66ce0daae8983d2a083808af0b8cbc724e824
Resolves: #98391
Related: #98370
Releases: main
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75782
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Benjamin Franzke <bfr@qbus.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benjamin Franzke <bfr@qbus.de>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Breaking-98370-ExtbaseRequestCleanupAndHardening.rst</summary>

```diff
@@ -42,6 +42,11 @@ Affected installations
 Extensions that actively manipulate the given Extbase :php:`Request` using setter methods
 will trigger fatal PHP "method does not exist" errors.
 
+Instances with extensions actively creating a :php:`Request` must actively hand over
+a :php:`\Psr\Http\Message\ServerRequestInterface` as constructor argument, it must have
+the attribute :php:`extbase` set, which must be an instance of
+:php:`\TYPO3\CMS\Extbase\Mvc\ExtbaseRequestParameters`.
+
 
 Migration
 =========
```

</details>

**Comment by linawolf** [comment]
Special case, not mentioned in the docs
