### ISSUE TITLE
[TASK] Avoid negative pid's in SQL schema

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#196]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f375dac362ec66fa05897b8bc1da414bf6f04707)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[TASK] Avoid negative pid's in SQL schema

Field 'pid' in TCA tables should not allow
negative integer values anymore since "pid -1"
values have been removed from workspaces in v10.

The patch changes the field to an unsigned int.

Change-Id: I876ffe78cef160979fae42a77a59972f26414ddf
Resolves: #98475
Related: #89555
Releases: main
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75915
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Important-98475-UnsignedPidTableColumns.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-98475-1664482965:

================================================
Important: #98475 - Unsigned "pid" table columns
================================================

See :issue:`98475`

Description
===========

When upgrading to TYPO3 core v12, the install tool database analyzer will change
the column field :sql:`pid` of various tables to :sql:`UNSIGNED`: They no longer
accept negative values.

Negative pid's were needed until core v10 in combination with workspaces, the core
nowadays only inserts rows with positive integers or 0 (zero) as pid value. An
upgrade wizard took care of updating affected rows when upgrading to v10, current
databases shouldn't contain such rows anymore.


.. index:: Database, ext:core

```

</details>

**Comment by linawolf** [comment]
Edge case not mentioned in the docs
