### ISSUE TITLE
Core RST Snippet Importer Specs: Legacy Import

### ISSUE THREAD

**Issue by Lefaux** [TYPO3-Documentation/Changelog-To-Doc#2]
This document describes the specs for importing RST snippets into GitHub issues once.

Workflow of script:

1. Find all rst snippets for v12.*
2. Determine whether rst snippet name is part of global blacklist.txt (to be provided by @linawolf in this issue)
3. Extract version number from folder (main branch needs to be mapped to next major resp. minor version)
4. Extract snippet category tag from rst snippet ([BREAKING], [FEATURE] etc.)
5. Extract content of rst snippet
6. Escape rst content of snippet so that it is displayed as code snipped in Markdown
7. Create GitHub issue in Repository https://github.com/TYPO3-Documentation/Changelog-To-Doc
8. Tag GitHub issue with TYPO3 version number extracted in step 3
9. Tag Github issue with category tag extract in step 4
10. Add imported rst snippet name to blacklist.txt (so we can have multiple runs of the same script)
11. Add issue to project board (@linawolf will provide the board identifier once the board has been set up)

**Comment by linawolf** [comment]
[blacklist.txt](https://github.com/TYPO3-Documentation/Changelog-To-Doc/files/8445259/blacklist.txt)

**Comment by linawolf** [comment]
All are imported
