### ISSUE TITLE
[!!!][TASK] Remove example tasks from EXT:scheduler

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#201]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/51ab74ee3a790a3e03e5114166f37ea800a85da5)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[!!!][TASK] Remove example tasks from EXT:scheduler

The example tasks "sleep" and "test" have been removed.
They were introduced in 2009 when EXT:scheduler was added
to TYPO3 Core.

Kudos to Georg Ringer who brought this up in
https://review.typo3.org/c/Packages/TYPO3.CMS/+/74053

Resolves: #98489
Related: #98453
Related: #11555
Releases: main
Change-Id: I4d9ea99a2a886252dccf86183e72d1d4fd008cc4
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75927
Tested-by: core-ci <typo3@b13.com>
Tested-by: Chris Müller <typo3@krue.ml>
Tested-by: Benjamin Franzke <bfr@qbus.de>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Chris Müller <typo3@krue.ml>
Reviewed-by: Benjamin Franzke <bfr@qbus.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-98489-RemovalOfSleepTaskAndTestTask.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-98489-1664577935:

====================================================
Breaking: #98489 - Removal of SleepTask and TestTask
====================================================

See :issue:`98489`

Description
===========

Previous TYPO3 installation contained the task `SleepTask` and `TestTask` which
served as examples when scheduler was introduced in 2009.

The tasks have been removed without substitution.


Impact
======

The scheduler tasks are not available anymore and won't be executed.


Affected installations
======================

All TYPO3 installations relying on these scheduler tasks.


Migration
=========

If used, the tasks can be removed within the scheduler module.

The configuration :php:`$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['scheduler']['showSampleTasks']` is removed automatically.

.. index:: PHP-API, NotScanned, ext:scheduler

```

</details>

**Comment by brotkrueml** [comment]
Was already handled in scheduler's documentation with the patch.
