### ISSUE TITLE
Feature: #91082 - Add new option “show scheduled records” to admin panel

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#22]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-91082-AddNewOptionShowScheduledRecordsToAdminPanel.html

**Comment by brotkrueml** [comment]
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77286
