### ISSUE TITLE
[BUGFIX] Add alias for moved RecordLinkHandler service

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#220]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/a114256189ccecc714f092dc0bcb6493d4371e53)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[BUGFIX] Add alias for moved RecordLinkHandler service

With #98443, EXT:recordlist was moved into EXT:backend.

The moved classes were added to the class alias map,
however there is one special case for the RecordLinkHandler
service. The service id (fully-qualified class name) is used
as static string in custom linkHandler configurations. This
is not automatically resolved by Symfony DI.

This is now fixed by adding a corresponding alias to the
service configuration.

Resolves: #98535
Related: #98443
Releases: main
Change-Id: I8bfa435153137fb4041eb8ab6938b9efd5a671c4
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75994
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Breaking-98443-ExtensionRecordlistMergedIntoBackend.rst</summary>

```diff
@@ -68,6 +68,9 @@ established as aliases. Extensions should update their dependencies in case they
 extending or implementing specific "recordlist" functionality, the extension scanner
 will find possible usages.
 
+Extensions using the LinkHandler API might need to update corresponding
+:typoscript:`TCEMAIN.linkHandler.*` configuration.
+
 Migration
 =========
 
@@ -82,4 +85,10 @@ Extensions supporting both TYPO3 v11 and v12 can continue to use the old class n
 since they have been established as aliases to the new class names. These aliases will
 be removed with TYPO3 Core v13.
 
+Extensions using the :php:`TYPO3\CMS\Recordlist\LinkHandler\RecordLinkHandler`
+as :typoscript:`handler` for a custom :typoscript:`linkHandler` should ajust
+corresponding TSconfig to use the new class name
+:php:`TYPO3\CMS\Backend\LinkHandler\RecordLinkHandler`. Corresponding service
+alias will be removed in TYPO3 v13.
+
 .. index:: Backend, PHP-API, FullyScanned, ext:recordlist
```

</details>

**Comment by brotkrueml** [comment]
Already mentioned in the docs.
