### ISSUE TITLE
[FEATURE] Introduce MailerInterface

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#224]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/7aec7a4bfb07fedab214954c696121388e0d140a)
:busts_in_silhouette: Authored by Rudy Gnodde rudy@famouswolf.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Introduce MailerInterface

In order to register your own mailer implementation,
a new interface has been introduced that makes registration
of your own mailer much easier.

Resolves: #97747
Releases: main
Change-Id: Ibcad8a79cb8750db7725d7983781c4bdb90b363f
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/74853
Tested-by: core-ci <typo3@b13.com>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Kevin Appelt <kevin.appelt@icloud.com>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Feature-97747-IntroduceMailerInterface.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-97747-1654691279

===========================================
Feature: #97747 - Introduce MailerInterface
===========================================

See :issue:`97747`

Description
===========

To be able to use your own custom MailerInterface implementation in the TYPO3 core, an
interface :php:`TYPO3\CMS\Core\Mail\MailerInterface` is introduced, which extends
:php:`Symfony\Component\Mailer\MailerInterface`

By default :php:`TYPO3\CMS\Core\Mail\Mailer` is registered as implementation in `Service.yaml`.

Example
^^^^^^^

.. code-block:: php

    $mailer = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Mail\MailerInterface::class);

Impact
======

This change makes it possible to create your own :php:`My\Custom\Mailer` that implements
:php:`TYPO3\CMS\Core\Mail\MailerInterface` which is used by TYPO3 core. Therefore it is recommended
to use the interface :php:`TYPO3\CMS\Core\Mail\MailerInterface`, to let dependency injection inject the
desired implementation for every :php:`TYPO3\CMS\Core\Mail\MailerInterface`.

Add the following line in :file:`Configuration/Services.yaml`, to ensure that your custom
implementation can be injected.

.. code-block:: yaml

    TYPO3\CMS\Core\Mail\MailerInterface:
      alias: My\Custom\Mailer

.. index:: PHP-API, ext:core

```

</details>

**Comment by brotkrueml** [comment]
Feature RST was accidently in 12.0 folder, it is a 12.1 feature.
