### ISSUE TITLE
Breaking: #96517 - TMENU.collapse Typoscript removed

### ISSUE THREAD

**Issue by nhovratov** [TYPO3-Documentation/Changelog-To-Doc#228]
This changelog seems to be missing in the import:

https://github.com/TYPO3/typo3/commit/5547a73298307c49c523c1ebee844a02a6b0bf06#diff-6c74bc73094bde4adb76cece4bde43ccc46dc655a340b0214cb24b78c1ba3a4e

Any idea why?

**Comment by brotkrueml** [comment]
I assume, the automatic creation of a changelog was implemented/activated after Jan 12 (AFAIK in 2nd quarter 2022).

**Comment by brotkrueml** [comment]
Thanks for the hint :-)

**Comment by nhovratov** [comment]
Ah, ok thanks!

**Comment by brotkrueml** [comment]
I can't find HMENU.collapse neither on 11.5 nor on main branch of the docs:

- https://docs.typo3.org/m/typo3/reference-typoscript/11.5/en-us/ContentObjects/Hmenu/Index.html
- https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/ContentObjects/Hmenu/Index.html

So it looks that it was not documented at all.

I will close this issue. If you think that is wrong, please feel free to open a new issue.

**Comment by nhovratov** [comment]
It is documented: https://docs.typo3.org/m/typo3/reference-typoscript/11.5/en-us/MenuObjects/Tmenu/Index.html?highlight=tmenu#collapse

The commit message / Changelog seems to be wrong.

**Comment by brotkrueml** [comment]
@nhovratov Okay, then the changelog should be changed first.

**Comment by brotkrueml** [comment]
@nhovratov Okay, here it is: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76321
