### ISSUE TITLE
[DOCS] Replace wrong method name in changelog

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#232]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/6a0d6d1c5d406b603c7adefd6a8d7bdb61df3ebe)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Andreas Fernandez a.fernandez@scripting-base.de

## Commit message

[DOCS] Replace wrong method name in changelog

Resolves: #98685
Releases: main
Change-Id: I7cbb2135639ba9a0d03e9e536802c01c60919f88
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76210
Tested-by: core-ci <typo3@b13.com>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Feature-98304-PSR-14EventForModifyingEditFormUserAccess.rst</summary>

```diff
@@ -23,7 +23,7 @@ convenience methods.
 To modify the user access, the following methods are available:
 
 *   :php:`allowUserAccess()`: Allows user access to the editing form
-*   :php:`setLinkExplanation()`: Denies user access to the editing form
+*   :php:`denyUserAccess()`: Denies user access to the editing form
 *   :php:`doesUserHaveAccess()`: Returns the current user access state
 *   :php:`getAccessDeniedException()`: If Core's DataProvider previously denied
     access, this returns the corresponding exception, :php:`null` otherwise
```

</details>

**Comment by brotkrueml** [comment]
As we use the code snippet this is already correct in TYPO3 Explained.
