### ISSUE TITLE
[DOCS] Correct changelog about removing TMENU.collapse

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#235]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/78def4c444443b36850b9504d8f8f400d0268165)
:busts_in_silhouette: Authored by Chris Müller typo3@krue.ml
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[DOCS] Correct changelog about removing TMENU.collapse

Resolves: #98946
Related: #96517
Releases: main
Change-Id: Ibf44b8dad7a1cc79796a5791f194fc7792e9a355
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76321
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Breaking-96517-TMENUcollapseTyposcriptRemoved.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-96517:

====================================================
Breaking: #96517 - TMENU.collapse TypoScript removed
====================================================

See :issue:`96517`

Description
===========

The :typoscript:`collapse` TypoScript property of :typoscript:`TMENU` is removed
without substitution.

When set, active :typoscript:`TMENU` items previously linked to their parent page,
which was primarily a use case for :typoscript:`GMENU_LAYERS`, which was
removed in TYPO3 v6.0.

Impact
======

Setting this TypoScript option has no effect anymore.

Affected Installations
======================

TYPO3 installations with :typoscript:`TMENU` definitions having this option
set which is highly unlikely.

Migration
=========

Use a custom user function or the PSR-14 :php:`FilterMenuItemsEvent` event to modify
the menu items.

.. index:: Frontend, TypoScript, NotScanned, ext:frontend

```

</details>

**Comment by brotkrueml** [comment]
Related to https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/228
