### ISSUE TITLE
[FEATURE] Differentiate redirects based on creation type

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#237]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f1dd77812891884761800ba15e3773146fb7610c)
:busts_in_silhouette: Authored by Georg Ringer georg.ringer@gmail.com
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] Differentiate redirects based on creation type

A new field in the redirect table allows to distinguish
between redirects created automatically because the slug
changed and the ones created by editors in the backend
module.

A new filter in the backend module based on this field
helps to administrate the records better.

Resolves: #97309
Releases: main
Change-Id: Ibe08246e97a8d3e185322f10e8628443c0e66b06
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/74186
Tested-by: core-ci <typo3@b13.com>
Tested-by: Kevin Appelt <kevin.appelt@icloud.com>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Kevin Appelt <kevin.appelt@icloud.com>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Feature-97309-DifferentiateRedirectsBasedOnCreationType.rst</summary>

```rst
.. include:: /Includes.rst.txt

================================================================
Feature: #97309 - Differentiate redirects based on creation type
================================================================

See :issue:`97309`

Description
===========

A new field `creation_type` has been added to the redirects.
This allows to differentiate between redirects created automatically when the
slug of a page is changed and the ones which are created in the backend
module by editors.

A new option in the redirects module allows to filter by this type.

Impact
======

The distinction by the creation type helps users to administrate the redirect
records and helps to identify why a record has been created initially.

A update wizards updates all existing redirects and set the type to manually.

If desired, the available items of the field `creation_type` can be extended
with additional type by adjusting TCA for this field. This simplifies the
registration of additional types, which automatically are available in backend
filtering. Possible use-cases are for example synced redirects or migrated from
other / old sources sources.

.. code-block:: php

    $GLOBALS['TCA']['sys_redirect']['columns']['creation_type']['config']['items'][] = [
        'My extension redirects',
        91,
    ];

.. index:: Backend, ext:redirects

```

</details>

**Comment by brotkrueml** [comment]
Already done in the extension manual merged with the feature.
