### ISSUE TITLE
[FEATURE] Add a description field to redirects

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#247]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/d15d1aef2390b94bcc828a3b6c957597a3ddd084)
:busts_in_silhouette: Authored by Christoph Schwob christoph@websailor.at
:heavy_check_mark: Merged by Georg Ringer georg.ringer@gmail.com

## Commit message

[FEATURE] Add a description field to redirects

Add a description field also for redirects, which
could be used to add notes for further handling of
the correpsonding redirect. This follows the same
logic like for other record types.

Resolves: #99011
Releases: main
Change-Id: I216eca8e72b9bf825ad9542997ec603f01ddc879
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76456
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Feature-99011-AllowDescriptionsForRedirects.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99011-1667944274:

==================================================
Feature: #99011 - Allow descriptions for redirects
==================================================

See :issue:`99011`

Description
===========

A new field :php:`description` has been added to the :sql:`sys_redirects` table.

In the backend edit form, the new field is located under the :guilabel:`Notes`
tab. It can be used to add context to the corresponding redirect. Since the
field is defined as the records' :php:`descriptionColumn`, the added
information is also displayed in the "Record information" info box
above the edit form, like known form e.g. content elements or pages.

Impact
======

It's now possible to add additional information to a redirect
using the new description field, whose value is also displayed
in the corresponding backend edit form.

.. index:: Database, TCA, Backend

```

</details>

**Comment by brotkrueml** [comment]
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77283
