### ISSUE TITLE
[TASK] Deprecate fluid HtmlViewHelper in Backend context

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#250]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/d7b5fb3d51efdb96bcd8dac490f14dd8c5e3e50f)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[TASK] Deprecate fluid HtmlViewHelper in Backend context

The HtmlViewHelper relies of Frontend TypoScript
"parseFunc" functionality and has an ugly hack
to prepare Frontend rendering in Backend context.

The core no longer uses f:format.html in Backend
context since the introduction of f:sanitize.html
and f:transform.html. Using f:format.html in
Backend context should be deprecated.

Resolves: #99031
Related: #94825
Releases: main
Change-Id: I60c5ea36b664a35abde431d2ac845ee9e2bff4bb
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76519
Tested-by: core-ci <typo3@b13.com>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Susanne Moog <look@susi.dev>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Susanne Moog <look@susi.dev>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Deprecation-99031-DeprecatedFformathtmlInBackendContext.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-99031-1667998430:

=================================================================
Deprecation: #99031 - Deprecated f:format.html in Backend context
=================================================================

See :issue:`99031`

Description
===========

The :html:`<f:format.html />` ViewHelper :php:`TYPO3\CMS\Fluid\ViewHelpers\Format\HtmlViewHelper`
should not be used in TYPO3 Backend context anymore.

Using this ViewHelper in Backend context triggers Frontend :typoscript:`parseFunc` logic, which
should be avoided in the backend.

There are other ViewHelpers to output and parse HTML in Backend context. See description of
the :ref:`f:sanitize.html <feature-94825-1667998632>` ViewHelper for more details.


Impact
======

Using :html:`<f:format.html />` logs a deprecation level warning.


Affected installations
======================

Instances with extensions that come with Backend modules using Fluid rendering and
accessing :html:`<f:format.html />` are affected.


Migration
=========

Switch to one of the other ViewHelpers instead, typically :html:`<f:sanitize.html />`
to secure a given HTML string, :html:`<f:transform.html />` to parse links in HTML,
or :html:`<f:format.raw />` to output the HTML as is when the input can be considered
"secure".


.. index:: Backend, Fluid, NotScanned, ext:fluid

```

</details>

## :heavy_division_sign: Modified files

<details>
<summary>9.5.x/Feature-94825-SanitizeHtmlFluidViewHelper.rst</summary>

```diff
@@ -1,5 +1,7 @@
 .. include:: /Includes.rst.txt
 
+.. _feature-94825-1667998632:
+
 ======================================================
 Feature: #94825 - New f:sanitize.html Fluid ViewHelper
 ======================================================
```

</details>

**Comment by brotkrueml** [comment]
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77380
