### ISSUE TITLE
[FEATURE] Move site settings into settings.yaml

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#252]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/51ea3741906869be1f6ddcbb422b619d9e20e09b)
:busts_in_silhouette: Authored by Bastien Lutz bastien.lutz@in2code.de
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Move site settings into settings.yaml

Site Settings were introduced with TYPO3 v10.

In contrast to the rest of the site configuration,
site settings are sane defaults for TypoScript constants,
and consist of simple key value logic.

In order to separate settings, make them
accessible and editable in the TYPO3 Backend,
and distinguish between the functionality between
required site configuration and optional settings,
the "settings" part of the settings are moved to
a separate "settings.yaml" file in the site configuration
folder, which will later-on be editable by the TYPO3 Backend
with the new Settings API introduced in a separate patch.

Resolves: #99047
Releases: main
Change-Id: Idbcb33ccf1c0d8a728b80ad4c242b56ff2d69afd
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76491
Tested-by: Susanne Moog <look@susi.dev>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Susanne Moog <look@susi.dev>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Feature-99047-LoadSiteSettingsFromSeparateSettingsyaml.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99047-1668081474:

================================================================
Feature: #99047 - Load site settings from separate settings.yaml
================================================================

See :issue:`99047`

Description
===========

Site Settings have been introduced with TYPO3 v10 as part of the configuration
of a site. In contrast to the site configuration, they are mostly used to
provide sane defaults for TypoScript constants and have a layer of arbitrary
configuration available in any context.

In order to separate these settings from the system site configuration, make them
accessible and editable in the TYPO3 Backend, and to distinguish between required
site configuration and optional settings, the "settings" part of the settings are
moved to a separate "settings.yaml" file in the site configuration folder.

A migration wizard is provided as upgrade wizard to migrate settings into the
new file.


Impact
======

Settings are now loaded from a separate file called "settings.yaml" residing
next to the :file:`config.yaml` of a site.
Executing the upgrade wizard will load all settings of a site and create that
file for the user. The migration wizard will not remove / rewrite the
:file:`config.yaml` - the user should do that on their own, to avoid breaking
custom-built functionality.

.. index:: Backend, YAML, ext:core

```

</details>

**Comment by brotkrueml** [comment]
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/255
Related: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76486

**Comment by brotkrueml** [comment]
We should wait until the whole PRs are merged:

- new "config/settings.yaml" file (this one)
- new Settings API (#255)
- new Settings backend (open)

Therefore on hold for now.
