### ISSUE TITLE
[FEATURE] Introduce Site Settings Read API

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#255]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/a537d2d85c2de75b352be57c02f8113580eb5701)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Introduce Site Settings Read API

When using site configuration with
settings, they previously were accessible
via $site->getConfiguration()['settings'].

A site now also contains the settings
in a better way to read them via $site->getSettings()
where a SiteSettings object is resolved,
which contains all defined settings.

Settings can be defined in a settings.yaml
within the site configuration folder, which
are then read and populated along with
the site configuration.

The new SiteSettings Read API allows to access
the settings via a flat array or a full array.

Resolves: #99048
Releases: main
Change-Id: I07f1244d0ed45fe09d0f39dfdd52e8523a05b730
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76520
Tested-by: core-ci <typo3@b13.com>
Tested-by: Susanne Moog <look@susi.dev>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Susanne Moog <look@susi.dev>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Feature-99048-SiteSettingsReadAPI.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99048-1668081533:

========================================
Feature: #99048 - Site Settings Read API
========================================

See :issue:`99048`

Description
===========

Settings for site-specific functionality can now be retrieved by a dedicated
`SiteSettings` object, accessible via a Site object
like :php:`$site->getSettings()`.

Settings can be used in custom frontend code to deliver features which might
vary per-site for extensions.


Impact
======

Accessing site settings, which was previously possible via:

:php:`$site->getConfiguration()['settings']['redirects'] ?? []`

in custom PHP code, is now easier via the SiteSettings PHP object.

The Site Settings object can be used to access settings either by
the dot notation ("flat"), e.g.

:php:`$redirectStatusCodeForRedirects = (int)$siteSettings->get('redirects.httpStatusCode', 307);`

or by accessing all options for a certain group

:php:`$allSettingsRelatedToRedirects = $siteSettings->get('redirects');`

or even fetching all settings

:php:`$siteSettings->all();`

In addition, settings can now be accessed in TypoScript via :typoscript:`getData`
with the key `siteSettings`:

.. code-block:: typoscript

    page.10 = TEXT
    page.10.data = siteSettings:redirects.httpStatusCode

.. index:: PHP-API, TypoScript ext:core

```

</details>

**Comment by brotkrueml** [comment]
On hold for now, see: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/252#issuecomment-1311967586
