### ISSUE TITLE
[DOCS] Correct changelog for deprecation of _CSS_PAGE_STYLE

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#257]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/970c398468816dabd3067c7565b6c69e0fbd8b43)
:busts_in_silhouette: Authored by Chris Müller typo3@krue.ml
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[DOCS] Correct changelog for deprecation of _CSS_PAGE_STYLE

The TypoScript "cssInline" property is only available on PAGE
level, not as a property on CONFIG.

Resolves: #99057
Related: #99050
Releases: main
Change-Id: Ic302d6ea79aba3cb32813f001f9d2dc57daabbaf
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76548
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Susanne Moog <look@susi.dev>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Susanne Moog <look@susi.dev>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>12.1/Deprecation-99050-TypoScript_CSS_PAGE_STYLEAndConfigremovePageCss.rst</summary>

```diff
@@ -12,12 +12,12 @@ Description
 ===========
 
 Integrators can use the TypoScript setup plugin-level property :typoscript:`_CSS_PAGE_STYLE`
-to define custom CSS that is loaded in the Frontend. To suppress this output, the additional
+to define custom CSS that is loaded in the frontend. To suppress this output, the additional
 property :typoscript:`config.removePageCss` (or :typoscript:`somePageObject.config.removePageCss`)
 can be used.
 
 Handling of both plugin-level :typoscript:`_CSS_PAGE_STYLE` and config object level
-property ::typoscript:`removePageCss` have been marked as deprecated in TYPO3 v12 and
+property :typoscript:`removePageCss` have been marked as deprecated in TYPO3 v12 and
 will be removed in v13.
 
 
@@ -57,16 +57,13 @@ After:
 
 .. code-block:: typoscript
 
-    config.cssInline {
+    page.cssInline {
         10 = TEXT
         10.value (
             .myClass { text-align: center }
         )
     }
 
-This will add the according CSS to all :typoscript:`PAGE` objects. A more specific
-inclusion can be done for single page objecs with :typoscript:`myPage.config.cssInline`.
-
 As a general note, the :typoscript:`PAGE` property :typoscript:`includeCSS` is often
 better suited to include CSS as files, especially when Frontend CSS is generated by
 some processor like SCSS.
```

</details>

**Comment by brotkrueml** [comment]
Changes already available in PR.
