### ISSUE TITLE
[TASK] Ensure auto-created redirect are stored on site root

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#259]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/e2de460184f5bc437157574a8afdb42bb2c72527)
:busts_in_silhouette: Authored by Stefan Bürk stefan@buerk.tech
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[TASK] Ensure auto-created redirect are stored on site root

Long time back auto-created redirects were created on
page "0", which has been changed meanwhile to create them
using the pageId of the changed page as `pid`.

With this change, auto-created redirects now use the
siteConfigs rootPageId as `pid`. This acts as a preparation
for following features and site based redirects editing
capabilities.

Resolves: #99044
Related: #91776
Releases: main
Change-Id: I9ebacd268999d6a5bdf765dc14ebac5f11777514
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76521
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Important-99044-EnsureAuto-createdRedirectAreStoredOnConnectedSiteRoot.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-99044-1668077928:

==================================================================================
Important: #99044 - Ensure auto-created redirect are stored on connected site root
==================================================================================

See :issue:`99044`

Description
===========

Long time back auto-created redirects were created on top root page
:php:`pid=0`, which has been changed meanwhile to create them
using the pageId of the changed page as :sql:`pid` with #91776.

This led to some issues, like permissions during copy-and-pasting pages.

Auto-created redirects are now stored using the siteConfigs rootPageId as
:sql:`pid` to minimize side-effect issues and preparing follup features.

.. index:: ext:redirects

```

</details>

**Comment by brotkrueml** [comment]
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77360
