### ISSUE TITLE
[TASK] Update chart.js to 4.0.1

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#268]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/bd9e88d35b2beb6743ecdc8f885f71a60fab2129)
:busts_in_silhouette: Authored by Andreas Fernandez a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Andreas Fernandez a.fernandez@scripting-base.de

## Commit message

[TASK] Update chart.js to 4.0.1

This patch updates chart.js to version 4.0.1, used in EXT:dashboard.
Due to breaking changes, a migration layer is in place to migrate known
and probably used settings.

Resolves: #99150
Releases: main
Change-Id: I2111d8c557416d113770ec68b8a3b7937d22e399
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76692
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Deprecation-99150-UpdatedChartLibraryInEXTdashboard.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-99150-1669026092:

============================================================
Deprecation: #99150 - Updated chart library in EXT:dashboard
============================================================

See :issue:`99150`

Description
===========

The library :js:`chart.js` used to render charts in an dashboard has been
updated to version 4.x, introducing some breaking changes. A migration layer is
in place to migrate known and used affected settings.


Impact
======

The CSS file :file:`EXT:dashboard/Resources/Public/Css/Contrib/chart.css` became
obsolete with the update of `chart.js` and was therefore removed without
replacement.

If a migration is executed, an entry will we written into the deprecation log.

Affected installations
======================

All plugins providing 3rd party chart widgets are affected.


Migration
=========

Migrate the configuration as mentioned in the table below.

================================   ============================
Old setting                        New setting
================================   ============================
graphConfig/options/scales/xAxes   graphConfig/options/scales/x
graphConfig/options/scales/yAxes   graphConfig/options/scales/y
================================   ============================

Also, please consult the migration guides available at

* https://www.chartjs.org/docs/latest/migration/v3-migration.html
* https://www.chartjs.org/docs/latest/migration/v4-migration.html

.. index:: Backend, JavaScript, NotScanned, ext:dashboard

```

</details>

**Comment by brotkrueml** [comment]
See : https://review.typo3.org/c/Packages/TYPO3.CMS/+/77282
