### ISSUE TITLE
[FEATURE] Introduce native JSON database field type support

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#270]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/e843fb1b076222994c84dd8a69d82ef74a4aae4b)
:busts_in_silhouette: Authored by Stefan Bürk stefan@buerk.tech
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] Introduce native JSON database field type support

The patch adds native JSON database field type.

This allows to define a JSON database field in extension
`ext_tables.sql` files, example:

CREATE TABLE tx_myextension_domain_model_book (
    title varchar(200) DEFAULT '',
    contents json
);

The methods `insert()`, `bulkInsert()` and `update()` in
class `\TYPO3\CMS\Core\Database\Connection` now
convert provided data values to their database counterpart
as define by doctrine/dbal. For json fields, values can be
provides as array and will be automatically json_encode()'ed.

The patch:
* Ensures php to database value conversion in fascade connection
  methods `insert()`, 'bulkInsert()` and `update()`
* Map JSON type from ext_tables.sql to doctrine/dbal JSON Type
* Remove platform specific automatic type determination in core
  DataHandler due to generic handling in Connection fascade class
* doctrine/dbal DateTimeType, DateType and TimeType are overriden
  to allow string as php value for converting to database

Resolves: #99062
Releases: main
Change-Id: Ib1d7b87db25c023c0a0d36edccb07392829eec4b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76553
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Feature-99062-NativeJSONDatabaseFieldSupportInDoctrineDBAL.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99062-1668170141:

=====================================================================
Feature: #99062 - Native JSON database field support in Doctrine DBAL
=====================================================================

See :issue:`99062`

Description
===========

TYPO3 Core's Database API based on Doctrine DBAL now supports the native
database field type `json`, which is already available for all supported DBMS
of TYPO3 v12.

JSON-like objects or array are automatically serialized during writing a
dataset to the database, when the native JSON type was used in the database
schema definition.


Impact
======

By using the native database field declaration `json` in e.g. :file:`ext_tables.sql`
files within an extension, TYPO3 now converts arrays or objects of type
:php:`\JsonSerializable` into a serialized JSON value in the database when
persisting such values via :php:`Connection->insert()` or
:php:`Connection->update()` if no explicit DB types are handed in as additional
method argument.

TYPO3 now utilizes the native type mapping of Doctrine to convert special types
such as JSON database field types automatically for writing.

Example ext_tables.sql:

.. code-block:: sql

    CREATE TABLE tx_myextension_domain_model_book (
        title varchar(200) DEFAULT '',
        contents json
    );

.. note::

    When reading a record from the database via QueryBuilder, it is still necessary
    though to transfer the serialized value to an array or Object doing custom
    serialization for the time being.


.. index:: Database, ext:core

```

</details>

**Comment by linawolf** [comment]
Is merged
