### ISSUE TITLE
[FEATURE] Reactions - Incoming WebHooks for TYPO3

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#280]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/bf65642f7afa24da3517977a024a7edc4f4c2d4a)
:busts_in_silhouette: Authored by Frank Naegler frank.naegler@typo3.org
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Reactions - Incoming WebHooks for TYPO3

This feature adds the possibility to receive incoming webhooks
into a TYPO3 instance.

This feature allows everybody to provide additional value for
any TYPO3 instance.

With the new system, a basic reaction is added, which allows
to create new records.

Extension authors are able to add their own reaction types
by implementing the ReactionInterface and adding corresponding
TCA configuration.

Used command(s)
  > composer req "symfony/uid:^6.2"
  > composer update typo3/testing-framework

Resolves: #98373
Releases: main
Change-Id: Ia0413c3951eca7cf05b6f28bb4743ce060639d5b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/75482
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Frank Nägler <frank.naegler@typo3.com>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Andreas Wolf <andreas.wolf@typo3.org>
Reviewed-by: Frank Nägler <frank.naegler@typo3.com>
Tested-by: Susanne Moog <look@susi.dev>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Susanne Moog <look@susi.dev>

## :heavy_plus_sign: Added files

<details>
<summary>12.1/Feature-98373-ReactionIncomingWebHooksforTYPO3.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-98373-1663587471:

=========================================================
Feature: #98373 - Reactions - Incoming WebHooks for TYPO3
=========================================================

See :issue:`98373`

Description
===========

This feature adds the possibility to send incoming webhooks to a TYPO3 instance.

With the new backend module, it is possible to configure the reactions triggered
by any webhook.

A webhook is defined as an authorized POST request to the backend.

The core provides a basic default reaction that can be used to create
records triggered and enriched by data from the caller.

Additionally, the core provides the :php:`\TYPO3\CMS\Reactions\Reaction\ReactionInterface`
to allow extension authors to add their own reaction types.

Any reaction record is defined by a unique uid and also requires a secret. Both
information are generated in the backend. The secret is only visible once and
stored in the database as an encrypted value like a backend user password.

Next to static field values does the "create record" reaction feature placeholders,
which can be used to dynamically set field values, by resolving the incoming
data from the webhooks' payload. The syntax to for those values is :code:`${key}`.
The key can be a simple string or a path to a nested value like :code:`${key.nested}`.

Definition of the placeholders in the record:
---------------------------------------------

.. code-block:: text

    ${title}
    ${description}
    ${key.nested}

Example payload for placeholders:
---------------------------------

.. code-block:: json

    {
        "title": "My title",
        "description": "My description",
        "key": {
            "nested": "bar"
        }
    }

Impact
======

This feature allows everybody to provide additional value for any TYPO3 instance.
By reacting to webhooks, TYPO3 can now be used to create records in the backend.
Furthermore, by implementing the :php:`ReactionInterface`, it is possible to
create any custom reaction.

.. index:: Backend, ext:reactions

```

</details>

**Comment by brotkrueml** [comment]
As this is a new system extension we should add the documentation there.

**Comment by linawolf** [comment]
Solved by https://review.typo3.org/c/Packages/TYPO3.CMS/+/76887

**Comment by brotkrueml** [comment]
Yes very, basic ;-) Will have a look.

**Comment by linawolf** [comment]
Oliver Bartsch asked me to not do more then that yet as They are still working on it
