### ISSUE TITLE
[TASK] Add event to intercept/adjust request-token

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#285]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/2469eef851d0d2124a71e3dd8401ef1d9ac8e1f4)
:busts_in_silhouette: Authored by Oliver Hader oliver@typo3.org
:heavy_check_mark: Merged by Oliver Hader oliver.hader@typo3.org

## Commit message

[TASK] Add event to intercept/adjust request-token

Add new BeforeRequestTokenProcessedEvent, allowing to intercept
or adjust a RequestToken during active user authentication process.

Resolves: #99232
Related: #97305
Releases: main
Change-Id: Iaa6cf7ca0ab2ab54fa1faa9a8fe6dcc76ef58ec9
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76868
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Feature-97305-IntroduceCSRF-likeRequest-tokenHandling.rst</summary>

```diff
@@ -142,6 +142,36 @@ needs to verify that the request-token has the expected `'my/process'` scope.
         }
     }
 
+Intercept & Adjust Request Token
+--------------------------------
+
+Scenarios that are not using a login callback without having the possibility to
+submit a request-token, :php:`\TYPO3\CMS\Core\Authentication\Event\BeforeRequestTokenProcessedEvent`
+can be used to generate the token individually.
+
+..  code-block:: php
+
+    use TYPO3\CMS\Core\Authentication\Event\BeforeRequestTokenProcessedEvent;
+    use TYPO3\CMS\Core\Security\RequestToken;
+
+    final class ProcessRequestTokenListener
+    {
+        public function __invoke(BeforeRequestTokenProcessedEvent $event): void
+        {
+            $user = $event->getUser();
+            $requestToken = $event->getRequestToken();
+            // fine, there is a valid request-token
+            if ($requestToken instanceof RequestToken) {
+                return;
+            }
+            // validate individual requirements/checks
+            // ...
+            $event->setRequestToken(
+                RequestToken::create('core/user-auth/' . $user->loginType);
+            );
+        }
+    }
+
 Impact
 ======
 
```

</details>

**Comment by brotkrueml** [comment]
The related feature: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/192
