### ISSUE TITLE
[FEATURE] Add Fluid TrimViewHelper

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#291]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/fafe38af2a48baf8dbca123ececea7a95602e38d)
:busts_in_silhouette: Authored by Benjamin Kott benjamin.kott@outlook.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Add Fluid TrimViewHelper

This adds a <f:format.trim> ViewHelper
that trims a string with the option
to trim characters off a string from
the end or from the start of the string.

Resolves: #99285
Releases: main
Change-Id: I78411d61c0f190df5b0925b0dd5a14df4c6f19e5
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76937
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Chris Müller <typo3@krue.ml>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Chris Müller <typo3@krue.ml>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>12.2/Feature-99285-AddFluidTrimViewhelper.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99285-1670321970:

==========================================
Feature: #99285 - Add Fluid TrimViewHelper
==========================================

See :issue:`99285`

Description
===========

Add a format trim view helper to trim strings.

Possible sides are:

* ``both`` Strip whitespace (or other characters) from the beginning and end of a string
* ``left`` Strip whitespace (or other characters) from the beginning of a string
* ``right`` Strip whitespace (or other characters) from the end of a string


Examples
--------

Trim from both sides
~~~~~~~~~~~~~~~~~~~~

..  code-block:: html

    #<f:format.trim>   String to be trimmed.   </f:format.trim>#

Results in the output:

..  code-block:: text

    #String to be trimmed.#

Trim only ony side
~~~~~~~~~~~~~~~~~~

..  code-block:: html

    #<f:format.trim side="right">   String to be trimmed.   </f:format.trim>#

Results in the output:

..  code-block:: text

    #   String to be trimmed.#

Trim special characters
~~~~~~~~~~~~~~~~~~~~~~~

..  code-block:: html

    #<f:format.trim characters=" St.">   String to be trimmed.   </f:format.trim>#

Results in the output:

..  code-block:: text

    #ring to be trimmed#


Impact
======

The new ViewHelper can be used in all new projects. There is no interference
with any part of existing code.

.. index:: Fluid, Frontend, ext:fluid

```

</details>

**Comment by brotkrueml** [comment]
See: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Format/Trim.html
