### ISSUE TITLE
[TASK] Allow custom tables in create record reaction

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#297]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/c3a101877734171e2fc9819f4cc3b8bf321ad6a4)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[TASK] Allow custom tables in create record reaction

Extension authors can now add tables to the create record
reaction via ExtensionManagementUtility::addTcaSelectItem().

Resolves: #99308
Related: #98373
Releases: main
Change-Id: I67ffff7b2e2888b6998b31bbcd3ce587d34a17c8
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76951
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Daniel Goerz <daniel.goerz@b13.com>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Daniel Goerz <daniel.goerz@b13.com>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Oliver Bartsch <bo@cedev.de>

## :heavy_division_sign: Modified files

<details>
<summary>12.1/Feature-98373-ReactionIncomingWebHooksforTYPO3.rst</summary>

```diff
@@ -55,6 +55,29 @@ Example payload for placeholders
         }
     }
 
+By default, only a few tables can be selected for external creation in the
+create record reaction. In case you want to allow your own tables to be
+available in the reactions' table selection, add the table in a coresponding TCA
+override file with:
+
+.. code-block:: php
+
+    if (\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::isLoaded('reactions')) {
+        \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addTcaSelectItem(
+            'sys_reaction',
+            'table_name',
+            [
+                'LLL:EXT:myext/Resources/Private/Language/locallang.xlf:my_table',
+                'my_table',
+                'myext-my_table-icon',
+            ]
+        );
+    }
+
+In case your extension depends on EXT:reactions the :php:`isLoaded()` check
+might be skipped. Please note that tables with :php:`adminOnly` set are not
+allowed.
+
 Impact
 ======
 
```

</details>

**Comment by brotkrueml** [comment]
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/81608
