### ISSUE TITLE
Breaking: #97358 - Removed eval=int from TCA type “datetime”

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#30]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-97358-RemovedEvalintFromTCATypeDatetime.html

**Comment by linawolf** [comment]
@nhovratov would you like to take care of this one?

**Comment by nhovratov** [comment]
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/pull/596
