### ISSUE TITLE
[FEATURE] Use password policy for new admin users created in ext:install

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#315]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/6b5c4dabe43d0712b4c099c46458d2c646053586)
:busts_in_silhouette: Authored by Torben Hansen derhansen@gmail.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Use password policy for new admin users created in ext:install

The password for a new administrative backend user created using the
install extension does now consider the configurable password policy
introduced in #97388

Resolves: #97392
Releases: main
Change-Id: I711071acdd7c8bcf10b04a1ca46b7d486c742f6e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77233
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>12.2/Feature-97392-UsePasswordPolicyForNewAdminUsersCreatedInExtinstall.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-97392-1672220371:

================================================================================
Feature: #97392 - Use password policy for new admin users created in ext:install
================================================================================

See :issue:`97392`

Description
===========

The password for a new administrative backend user created using the install
extension does now consider the configurable password policy introduced in
:ref:`#97388 <feature-97388>`.


Impact
======

The globally configured password policy is now taken into account when a
new administrative backend user is created using the install extension.
Password policy requirements are shown below the password field and a message
is shown, if the new password does not meet the password policy requirements.

.. index:: Backend, ext:install

```

</details>

**Comment by brotkrueml** [comment]
Already available in password policies chapter (more generic written as "Creating a backend user during installation") - previously through CLI command.
