### ISSUE TITLE
[FEATURE] Allow to provide name for new admin users in ext:install

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#316]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/e97bd18fd3fda073b79ca8b440802421d62405e7)
:busts_in_silhouette: Authored by Torben Hansen derhansen@gmail.com
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] Allow to provide name for new admin users in ext:install

The field `realName` has been added to the "Create Administrative User"
modal in ext:install, so it is possible to provide the name of a new
admin user.

The notice in the header of the model has been removed, since it is
superfluous now.

Resolves: #99584
Releases: main
Signed-off-by: Torben Hansen <derhansen@gmail.com>
Change-Id: I6732bfe4d664f200b2bcc3471c6f0ffd9859365b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77455
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>12.2/Feature-99584-AllowToProvideRealNameForNewAdminUsersInExtinstall.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99584-1673985938:

==========================================================================
Feature: #99584 - Allow to provide name for new admin users in ext:install
==========================================================================

See :issue:`99584`

Description
===========

The field `realName` has been added to the "Create Administrative User" modal
in ext:install, so it is possible to provide the name of a new admin user.

The notice in the header of the model has been removed, since it is
superfluous now.

Impact
======

It is now possible to provide the field `realName`, when a new admin user
is created in ext:install.

.. index:: Backend, ext:install

```

</details>

**Comment by linawolf** [comment]
Does not need to be documented
