### ISSUE TITLE
Feature: #97326 - Open backend page from admin panel

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#32]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-97326-OpenBackendPageFromAdminPanel.html

**Comment by linawolf** [comment]
does not need to be documented

**Comment by brotkrueml** [comment]
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77287
