### ISSUE TITLE
[TASK] Define explicit routes for Extbase Backend Modules

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#340]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/836007411cd2b8d37faee12da7ae4194b6b90b09)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[TASK] Define explicit routes for Extbase Backend Modules

Previously, the controller / action pairs of an Extbase Backend
Module were defined via corresponding GET parameters. Thanks to
the new Module Registration API and the support for individual
sub routes, it's now also possible to define explicit routes
for each controller / action pair. This is done automatically,
as long as the "enableNamespacedArgumentsForBackend" feature
toggle is turned off, which is the default.

This therefore results in following change:

http://example.com/typo3/module/system/BeuserTxBeuser?controller=BackendUser&action=filemounts

becomes

http://example.com/typo3/module/system/BeuserTxBeuser/BackendUser/filemounts

Resolves: #99704
Related: #99647
Related: #96733
Releases: main
Change-Id: Ie7bbf70793f7e3da17db3ab1a322ba8ad7bcc5b8
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77508
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Benni Mack <benni@typo3.org>

## :heavy_division_sign: Modified files

<details>
<summary>12.2/Feature-99647-SpecificRoutesForBackendModules.rst</summary>

```diff
@@ -62,10 +62,60 @@ sub route could therefore look like this:
 
     UriBuilder->buildUriFromRoute('my_module.edit')
 
+Extbase modules
+^^^^^^^^^^^^^^^
+
+Also Extbase Backend Modules are enhanced and do now automatically
+define explicit routes for each controller / action combination,
+as long as the :typoscript:`enableNamespacedArgumentsForBackend`
+feature toggle is turned off, which is the default. This means,
+the following module configuration
+
+..  code-block:: php
+
+    return [
+        'web_ExtkeyExample' => [
+            'parent' => 'web',
+            'position' => ['after' => 'web_info'],
+            'access' => 'admin',
+            'workspaces' => 'live',
+            'iconIdentifier' => 'module-example',
+            'path' => '/module/web/ExtkeyExample',
+            'labels' => 'LLL:EXT:beuser/Resources/Private/Language/locallang_mod.xlf',
+            'extensionName' => 'Extkey',
+            'controllerActions' => [
+                MyModuleController::class => [
+                    'list',
+                    'detail'
+                ],
+            ],
+        ],
+    ];
+
+now leads to following URLs:
+
+- `https://example.com/typo3/module/web/ExtkeyExample`
+- `https://example.com/typo3/module/web/ExtkeyExample/MyModuleController/list`
+- `https://example.com/typo3/module/web/ExtkeyExample/MyModuleController/detail`
+
+The route identifier of corresponding routes is registered with similar syntax
+as standard backend modules: :php:`<module_identifier>.<controller>_<action>`.
+Above configuration will therefore register the following routes:
+
+- `web_ExtkeyExample`
+- `web_ExtkeyExample.MyModuleController_list`
+- `web_ExtkeyExample.MyModuleController_detail`
+
 Impact
 ======
 
 It's now possible to configure specific routes for a module, which all can
 target any controller / action combination.
 
+As long as :typoscript:`enableNamespacedArgumentsForBackend` is turned off
+for Extbase Backend Modules, all controller / action combinations are explicitly
+registered as individual routes. This effectively means human-readable URLs,
+since the controller / action combinations are no longer defined via query
+parameters but are now part of the path.
+
 .. index:: Backend, PHP-API, ext:backend
```

</details>

**Comment by brotkrueml** [comment]
This is an enhancement of https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/327
