### ISSUE TITLE
[TASK] Update note about new TypoScript parser

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#351]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/5d27b2ae3b33dbf30b57f7b42dfd8ebc192c8eda)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[TASK] Update note about new TypoScript parser

Resolves: #99818
Related: #97816
Releases: main
Change-Id: Ibc3e5dd98d75d1c1cb4de6e8fad1f7b662d3de75
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77694
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Breaking-97816-TypoScriptSyntaxChanges.rst</summary>

```diff
@@ -11,12 +11,6 @@ See :issue:`97816`
 Description
 ===========
 
-.. note::
-
-    The new TypoScript parser is currently not or only partially active
-    in the system. The full implementation should be finished until v12 LTS.
-    This note should be removed later.
-
 TYPO3 v12 comes with a new TypoScript syntax parser that is more performant,
 more robust and allows better tooling in the Backend.
 
```

</details>

<details>
<summary>12.0/Feature-97816-TypoScriptSyntaxImprovements.rst</summary>

```diff
@@ -11,12 +11,6 @@ See :issue:`97816`
 Description
 ===========
 
-.. note::
-
-    The new TypoScript parser is currently not or only partially active
-    in the system. The full implementation should be finished until v12 LTS.
-    This note should be removed later.
-
 TYPO3 v12 comes with a new TypoScript syntax parser that is more performant,
 more robust and allows better tooling in the Backend.
 
```

</details>

**Comment by brotkrueml** [comment]
Related: #116
