### ISSUE TITLE
[TASK] Streamline setup command

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#356]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/b8038e092c57d24347172ff19b7c25b3dee0a857)
:busts_in_silhouette: Authored by Jochen Roth jochen.roth@b13.com
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[TASK] Streamline setup command

Additional warning about password set via cli has been
added. Also the logic was changed to always prompt
for password (db password and admin user password) if
not set via variable/option.

Resolves: #99836
Releases: main
Change-Id: Ic47e100ecb328ac62b58296bc00feff9a84213aa
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77707
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_division_sign: Modified files

<details>
<summary>12.1/Feature-99221-AddCliInstallSetupCommand.rst</summary>

```diff
@@ -36,16 +36,22 @@ Automated setup:
 
     TYPO3_DB_DRIVER=mysqli \
     TYPO3_DB_USERNAME=db \
-    TYPO3_DB_PASSWORD=db \
     TYPO3_DB_PORT=3306 \
     TYPO3_DB_HOST=db \
     TYPO3_DB_DBNAME=db \
-    TYPO3_SETUP_ADMIN_EMAIL=admin@email.com \
+    TYPO3_SETUP_ADMIN_EMAIL=admin@example.com \
     TYPO3_SETUP_ADMIN_USERNAME=admin \
-    TYPO3_SETUP_PASSWORD=password \
+    TYPO3_SETUP_CREATE_SITE="https://your-typo3-site.com/" \
     TYPO3_PROJECT_NAME="Automated Setup" \
-    TYPO3_CREATE_SITE="https://your-typo3-site.example.com/" \
     ./bin/typo3 setup --force
 
+.. warning::
+    Variable `TYPO3_DB_PASSWORD` (option `--password`) can be used to provide a
+    password for the database and `TYPO3_SETUP_ADMIN_PASSWORD`
+    (option `--admin-user-password`) for the admin user password.
+    Using this can be a security risk since the password may end up in shell
+    history files. Prefer the interactive mode. Additionally, writing a command
+    to shell history can be suppressed by prefixing the command with a space
+    when using `bash` or `zsh`.
 
 .. index:: ext:install
```

</details>

**Comment by brotkrueml** [comment]
This topic was only added to "Getting Started" with a stub:
https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/283

We should explain also the details of this command in "TYPO3 Explained" then.
