### ISSUE TITLE
[FEATURE] Allow resources to be moved/copied with drag and drop in filelist

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#371]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/b56b6e387d3f0623b2e7e75e480a8fda6459a832)
:busts_in_silhouette: Authored by Benjamin Kott benjamin.kott@outlook.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Allow resources to be moved/copied with drag and drop in filelist

This patch enables drag-and-drop for resources within the file list.
It is now possible to transfer files and folders with drag operations to
folders visible in the current view.

Resolves: #100027
Releases: main
Change-Id: Ie46e68e637dad69ae2a49e0b8d80c5bc91b39fc5
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77931
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>12.3/Feature-100027-CopyFilesAndFoldersWithinTheFileListModule.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-100027-1677251094:

=====================================================================
Feature: #100027 - Copy Files and Folders within the File List module
=====================================================================

See :issue:`100027`

Description
===========

With TYPO3 v12.2, the feature to drag+drop files and folders between the tree
structure was added. Now it is also possible to copy or move resources within
the actual file listing (tile view or list view) into e.g. a different subfolder
by selecting them, and using the mouse to drop them on to a target folder.

Impact
======

TYPO3 file list is now fully usable with drag+drop between the tree and within
the listing itself.

All features make it easier for editors to manage and organize the digital
assets used within TYPO3.

.. index:: Backend, ext:filelist

```

</details>

**Comment by linawolf** [comment]
No need to document
