### ISSUE TITLE
Deprecation: #96996 - Deprecate TypoScriptFrontendController->checkEnableFields

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#39]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-96996-DeprecateTypoScriptFrontendController-checkEnableFields.html

**Comment by brotkrueml** [comment]
Haven't found any occurrence of the `checkEnableFields` method in docs beside the changelog. Can be closed I assume.
