### ISSUE TITLE
[FEATURE] Add password policy action to exclude validators in SU mode

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#408]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/90d26842717ae748915ad9feb9cc9f531e5ba7cf)
:busts_in_silhouette: Authored by Torben Hansen derhansen@gmail.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Add password policy action to exclude validators in SU mode

The new password policy action `UPDATE_USER_PASSWORD_SWITCH_USER_MODE`
has been added in order to allow exclusion of a password policy
validator, if the current user is in switch user mode.

Additionally, the new password policy action is now used in the
global default password policy for the `NotCurrentPasswordValidator`.

Resolves: #99608
Releases: main
Signed-off-by: Torben Hansen <derhansen@gmail.com>
Change-Id: I3e410a7d9ac4fac553d85f2465b4fbab938bd84c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77476
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Markus Klein <markus.klein@typo3.org>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Georg Ringer <georg.ringer@gmail.com>

## :heavy_plus_sign: Added files

<details>
<summary>12.3/Feature-99608-AddPasswordPolicyActionToExcludeValidatorsInSUMode.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99608-1674053552:

=============================================================================
Feature: #99608 - Add password policy action to exclude validators in SU mode
=============================================================================

See :issue:`99608`

Description
===========

The new password policy action `UPDATE_USER_PASSWORD_SWITCH_USER_MODE` has been
added in order to allow administrators to exclude a password policy validator,
if the current user is in switch user mode.

The new password policy action is used in the global default password policy for
the `NotCurrentPasswordValidator`.


Impact
======

When the current backend user is in switch user mode, it is not validated,
if the new password equals the current user password in ext:setup.

.. index:: Backend, ext:core

```

</details>

**Comment by linawolf** [comment]
No need to document
