### ISSUE TITLE
Deprecation: #97027 - ContentObjectRenderer->getTreeList()

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#41]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97027-ContentObjectRenderer-getTreeList.html

**Comment by brotkrueml** [comment]
Haven't found any occurrence of `getTreeList` in the docs beside the changelog. Can be closed I assume.
