### ISSUE TITLE
Deprecation: #97016 - Deprecate usage of RegularExpressionValidator in form editor

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#42]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97016-DeprecateUsageOfRegularExpressionValidatorInFormEditor.html

**Comment by brotkrueml** [comment]
Haven't found any occurrence mentioning the validator besides the changelog. Can be closed I assume.
