### ISSUE TITLE
[FEATURE] AdminPanel: Add SQL and memory metrics to toolbar

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#424]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/5315e5a7905f8929a4039fde8dd7c9629257cfe2)
:busts_in_silhouette: Authored by Christoph Lehmann christoph.lehmann@networkteam.com
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] AdminPanel: Add SQL and memory metrics to toolbar

This extends the AdminPanel toolbar with more important metrics:

* Peak memory usage
* Amount of SQL queries
* Time spent doing SQL queries

Resolves: #100167
Releases: main
Change-Id: I40dc57491188ea65656bde66cb181f134085b308
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77007
Tested-by: core-ci <typo3@b13.com>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>12.3/Feature-100167-AdminPanelAddSQLAndMemoryInfosToToolbar.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-100167-1679005733:

====================================================================
Feature: #100167 - AdminPanel: Add SQL and memory metrics to toolbar
====================================================================

See :issue:`100167`

Description
===========

This extends the AdminPanel toolbar with more important metrics:

* Peak memory usage
* Amount of SQL queries
* Time spent doing SQL queries


Impact
======

The AdminPanel toolbar now shows more important information.

.. index:: Frontend, ext:adminpanel

```

</details>

**Comment by brotkrueml** [comment]
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79053
