### ISSUE TITLE
Deprecation: #97201 - Unused Interface for new content element wizard hook

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#43]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97201-UnusedInterfaceForNewContentElementWizardHook.html

**Comment by brotkrueml** [comment]
Haven't found any occurrence mentioning the interface or the hook besides of the superseding PSR 14 events. Can be closed I assume.
