### ISSUE TITLE
[FEATURE] Add CKEditor Inspector for backend RTE forms

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#430]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/dc583bbcb518603e7ede4c250bbfc6369d85a3ac)
:busts_in_silhouette: Authored by Andreas Nedbal andy@pixelde.su
:heavy_check_mark: Merged by Andreas Fernandez a.fernandez@scripting-base.de

## Commit message

[FEATURE] Add CKEditor Inspector for backend RTE forms

This feature adds the CKEditor Inspector to backend RTE forms in
Development context with $GLOBALS['TYPO3_CONF_VARS']['BE']['debug']
or the CKEditor configuration `editor.config.debug` being set.

The Inspector aids plugin developers in debugging the intermediate
CKEditor model.

Resolves: #100284
Releases: main
Change-Id: Ie18cd6c0b9854304fd3cbea521f5a434d4520a0e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/78243
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>12.3/Feature-100284-AddCKEditorInspectorForBackendRTEForms.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-100284-1679681558:

===============================================================
Feature: #100284 - Add CKEditor Inspector for backend RTE forms
===============================================================

See :issue:`100284`

Description
===========

This feature introduces the ability to show the CKEditor Inspector for backend RTE forms.

With CKEditor 5 and the introduction of the intermediate CKEditor model, knowing
the internals is a requirement to build plugins. The best way to debug plugin
development is the `CKEditor Inspector <https://ckeditor.com/docs/ckeditor5/latest/framework/development-tools.html#ckeditor-5-inspector>`_.

For regular pages, there is a simple bookmarklet that can be included to show
the Inspector, but in the TYPO3 backend the usage of frames does not allow this
option. Giving developers a config option in the RTE simplifies this process.

The Inspector can be enabled in two different ways:
* By having :php:`$GLOBALS['TYPO3_CONF_VARS']['BE']['debug']` enabled and being in the `Development` context
* By setting the option :yaml:`editor.config.debug` to :yaml:`true` in your CKEditor configuration

Example for setting the CKEditor configuration:

..  code-block:: yaml

    editor:
      config:
        debug: true


Impact
======

By being in the right context or enabling the given option, it's now possible to easier debug CKEditor instances for plugin development.

.. index:: Backend, RTE, YAML, ext:rte_ckeditor

```

</details>

**Comment by brotkrueml** [comment]
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79022
