### ISSUE TITLE
Deprecation: #97217 - Moved TypoLinkCodecService to EXT:core

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#44]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97217-MovedTypoLinkCodecServiceToEXTcore.html

**Comment by brotkrueml** [comment]
Haven't found any reference to `TypoLinkCodecService` searching the docs. So can be closed I assume.
