### ISSUE TITLE
[BUGFIX] Prevent exception using getTSFE() in backend context

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#447]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/490d53d05b197e63c3fb3dbc30d2fa221421722c)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[BUGFIX] Prevent exception using getTSFE() in backend context

In case the "getTSFE()" expression function is called
in backend context - having no TSFE available-, the
function returned "FALSE" since  #100237. This however
prevents to properly check such state in the expression
itself. This is now fixed by returning "NULL" instead,
as it's the case for similar functions, e.g. "site()" or
"siteLanguage()").

This allows to properly use the null-safe operator ("?").

Example usage: `[getTSFE()?.id = 123]`

Resolves: #100563
Related: #100237
Releases: main
Change-Id: I9fbf4950df65dcd17be21a4c312b34e2548be698
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/78622
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Jochen <rothjochen@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Jochen <rothjochen@gmail.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_division_sign: Modified files

<details>
<summary>12.3/Deprecation-100237-TypoScriptRelatedExceptions.rst</summary>

```diff
@@ -46,4 +46,13 @@ Migration
 
 No direct migration available.
 
+.. note::
+
+    Using the :typoscript:`getTSFE()` function, developers have to ensure
+    that "TSFE" is available before accessing its properties. A missing "TSFE",
+    e.g. in backend context, does no longer automatically evaluate the whole
+    condition to :php:`FALSE`. Instead, the function returns :php:`NULL`,
+    which can be checked using either :typoscript:`getTsfe() && getTsfe().id`
+    or the null-safe operator :typoscript:`getTsfe()?.id`.
+
 .. index:: PHP-API, FullyScanned, ext:core
```

</details>

**Comment by brotkrueml** [comment]
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/450
