### ISSUE TITLE
Deprecation: #97231 - Unused Interface for inline element hook

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#45]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-97231-UnusedInterfaceForInlineElementHook.html

**Comment by brotkrueml** [comment]
Haven't found any occurrence mentioning the hook besides of the superseding PSR 14 events or the interface. Can be closed I assume.
