### ISSUE TITLE
[DOCS] Fix AccessLifetime cases

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#471]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/fc0c0becf42b62d8ebe8e3f9d1bd45c108d8ac93)
:busts_in_silhouette: Authored by Oliver Hader oliver@typo3.org
:heavy_check_mark: Merged by Oliver Hader oliver.hader@typo3.org

## Commit message

[DOCS] Fix AccessLifetime cases

The cases of \TYPO3\CMS\Backend\Security\SudoMode\Access\AccessLifetime
are not correctly documented, e.g. `XS` became `veryShort` during the
development for #94246.

Resolves: #100722
Releases: main
Change-Id: If6cef5a4840b0d0d0e94575b45a2d0cc3b30858e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/78801
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>

## :heavy_division_sign: Modified files

<details>
<summary>12.4/Important-94246-GenericSudoModeConfiguration.rst</summary>

```diff
@@ -51,7 +51,7 @@ In general the configuration for a particular route or module looks like this:
     // ...
     'sudoMode' => [
         'group' => 'individual-group-name',
-        'lifetime' => AccessLifetime::XS,
+        'lifetime' => AccessLifetime::veryShort,
     ],
 
 * `group` (optional): if given, grants access to other objects of the same `group`
@@ -61,8 +61,8 @@ In general the configuration for a particular route or module looks like this:
   grants access to the other automatically.
 * `lifetime`: enum value of :php:`\TYPO3\CMS\Backend\Security\SudoMode\Access\AccessLifetime`,
   defining the lifetime of a sudo mode verification, afterwards users have to go through
-  the process again - cases are `XS` (5 minutes), `S` (10 minutes), `M` (15 minutes),
-  `L` (30 minutes), `XL` (60 minutes)
+  the process again - cases are `veryShort` (5 minutes), `short` (10 minutes),
+  `medium` (15 minutes), `long` (30 minutes), `veryLong` (60 minutes)
 
 
 For backend routes declared via :file:`Configuration/Backend/Routes.php`, the
@@ -77,7 +77,7 @@ relevant configuration would look like this:
             'target' => MyHandler::class . '::process',
             'sudoMode' => [
                 'group' => 'mySudoModeGroup',
-                'lifetime' => AccessLifetime::S,
+                'lifetime' => AccessLifetime::short,
             ],
         ],
     ];
@@ -95,7 +95,7 @@ relevant configuration would look like this:
             'routeOptions' => [
                 'sudoMode' => [
                     'group' => 'systemMaintainer',
-                    'lifetime' => AccessLifetime::M,
+                    'lifetime' => AccessLifetime::medium,
                 ],
             ],
         ],
```

</details>

**Comment by brotkrueml** [comment]
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/470
