### ISSUE TITLE
[BUGFIX] Allow untrusted query arguments in ViewHelpers

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#473]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/1a7fecd10aa1714355277c860ad8f018901178ce)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[BUGFIX] Allow untrusted query arguments in ViewHelpers

With #98488, the typolink option "addQueryString" changed
the behaviour to only add mapped query arguments by default.
To add all - even "untrusted" - arguments to the generated
URL, the new "untrusted" keyword has to be used.

This now adds the possibility to set the new keyword in
all related ViewHelpers. Therefore, the "addQueryString"
property of the extbase UriBuilder is adjusted as well.

Resolves: #100583
Related: #98488
Releases: main
Change-Id: I3a4b62ec734b13e6f3cd721f4a6acefe9877b72b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/78804
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Breaking-98488-TypolinkOptionAddQueryStringOnlyIncludesResolvedQueryArguments.rst</summary>

```diff
@@ -15,7 +15,9 @@ The Typolink option :typoscript:`typolink.addQueryString` previously set all giv
 GET parameters to a generated URL that were handed in to the request.
 
 This option is also used under the hood for the  Fluid ViewHelpers
-:html:`<f:link.typolink>` and :html:`<f:uri.typolink>`.
+:html:`<f:link.typolink>`, :html:`<f:uri.typolink>`, :html:`<f:link.page>`,
+:html:`<f:uri.page>`, :html:`<f:link.action>`, :html:`<f:link.action>` and
+:html:`<f:form>`.
 
 With TYPO3 v9 and routing, this option now only adds the query arguments that
 have been resolved during the routing process. This way, additional query arguments
@@ -46,6 +48,8 @@ However, to ensure the previous behaviour, the option
 :typoscript:`typolink.addQueryString` can be set to `untrusted` to add all given.
 
 The same value is also possible for the Fluid ViewHelpers
-:html:`<f:link.typolink>` and :html:`<f:uri.typolink>`.
+:html:`<f:link.typolink>`, :html:`<f:uri.typolink>`, :html:`<f:link.page>`,
+:html:`<f:uri.page>`, :html:`<f:link.action>`, :html:`<f:link.action>` and
+:html:`<f:form>`.
 
 .. index:: Fluid, TypoScript, NotScanned, ext:frontend
```

</details>

<details>
<summary>12.0/Feature-98488-AdditionalSettingForTypolinkOptionAddQueryString.rst</summary>

```diff
@@ -15,7 +15,9 @@ The Typolink option :typoscript:`typolink.addQueryString` now also accepts
 the value `untrusted` to be used to retrieve all GET parameters of the current request.
 
 This value can also used in the Fluid ViewHelpers
-:html:`<f:link.typolink>` and :html:`<f:uri.typolink>`.
+:html:`<f:link.typolink>`, :html:`<f:uri.typolink>`, :html:`<f:link.page>`,
+:html:`<f:uri.page>`, :html:`<f:link.action>`, :html:`<f:link.action>` and
+:html:`<f:form>`.
 
 Impact
 ======
```

</details>

**Comment by linawolf** [comment]
The ViewHelper Reference regenerates automatically
