### ISSUE TITLE
[!!!][TASK] Remove old TypoScript parser

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#491]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/13f96698f19cf38c57c5ef47d423861aecb0c95e)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Remove old TypoScript parser

Remove old TypoScriptParser, TemplateService
and supporting classes.

Resolves: #100998
Related: #100963
Related: #99075
Related: #97816
Related: #98503
Related: #99120
Releases: main
Change-Id: Ide8a1d7c7a505cd13f9a87149f71d7985ecd1f40
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79261
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Nikita Hovratov <nikita.h@live.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Nikita Hovratov <nikita.h@live.de>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-100963-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -13,7 +13,11 @@ Description
 
 The following PHP classes that have previously been marked as deprecated for v12 and were now removed:
 
-- :php:`\Full\Class\Name`
+- :php:`\TYPO3\CMS\Core\Configuration\Loader\PageTsConfigLoader`
+- :php:`\TYPO3\CMS\Core\Configuration\PageTsConfig`
+- :php:`\TYPO3\CMS\Core\Configuration\Parser\PageTsConfigParser`
+- :php:`\TYPO3\CMS\Core\TypoScript\Parser\TypoScriptParser`
+- :php:`\TYPO3\CMS\Core\TypoScript\TemplateService`
 
 The following PHP classes have been declared :php:`final`:
 
@@ -34,9 +38,11 @@ The following PHP class aliases that have previously been marked as deprecated f
 The following PHP class methods that have previously been marked as deprecated for v12 and were now removed:
 
 - :php:`\TYPO3\CMS\Core\Environment->getBackendPath`
+- :php:`\TYPO3\CMS\Frontend\Authentication\FrontendUserAuthentication->getUserTSconf`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->baseUrlWrap`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->checkEnableFields`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->doWorkspacePreview`
+- :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->getPagesTSconfig`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->initUserGroups`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->isBackendUserLoggedIn`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->isUserOrGroupSet`
@@ -57,6 +63,7 @@ The following public class properties have been dropped:
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->fileTarget`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->intTarget`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->spamProtectEmailAddresses`
+- :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->tmpl`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->xhtmlDoctype`
 - :php:`\TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->xhtmlVersion`
 
@@ -94,7 +101,7 @@ The following class constants have been dropped:
 
 The following global option handling have been dropped and are ignored:
 
-- :php:`$GLOBALS['TYPO3_CONF_VARS']['KEY']['subKey']`
+- :php:`$GLOBALS['TYPO3_CONF_VARS']['FE']['defaultUserTSconfig']`
 
 The following global variables have been removed:
 
@@ -112,9 +119,9 @@ The following single field configurations have been removed from :php:`$GLOBALS[
 
 - :php:`dummy`
 
-The following signals have been removed:
+The following events have been removed:
 
-- :php:`\Full\Class\Name::signalName`
+- :php:`\TYPO3\CMS\Core\Configuration\Event\ModifyLoadedPageTsConfigEvent`
 
 The following features are now always enabled:
 
@@ -128,9 +135,10 @@ The following database tables have been removed:
 
 - :sql:`table`
 
-The following database tabel fields have been removed:
+The following database table fields have been removed:
 
-- :sql:`table.field`
+- :sql:`fe_users.TSconfig`
+- :sql:`fe_groups.TSconfig`
 
 The following Backend route identifiers have been removed:
 
```

</details>

**Comment by linawolf** [comment]
Is it possible that with 13.4 the support of ext_typoscript_setup.typoscript is completely gone and this fact is neither mentioned in any changelogs nor the docs?!
Here it's still mentioned as if it's still a thing: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ExtensionArchitecture/FileStructure/ExtTyposcriptSetupTyposcript.html

yes, kicked out with this change

**Comment by brotkrueml** [comment]
Hmm, the content seems to be applied. I provide in EXT:form_rate_limit an `ext_typoscript_setup.typoscript` file. In it is a reference to the form yaml definition:
https://github.com/brotkrueml/typo3-form-rate-limit/blob/main/ext_typoscript_setup.typoscript

When I rename that `ext_typoscript_setup.typoscript` file, the finisher is not available anymore in the form GUI, therefore the file is taken into account.

But the configuration is not visible in the `Active Typoscript` module.

Tested with TYPO3 v13.4.0.

**Comment by linawolf** [comment]
See https://typo3.slack.com/archives/C028JEPJL/p1731401720219799
