### ISSUE TITLE
[!!!][TASK] Remove deprecated chart.js code from ext:hashboard

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#538]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/bdfcaf0b179f163b876636eaee1d94667c7a0048)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Anja Leichsenring aleichsenring@ab-softlab.de

## Commit message

[!!!][TASK] Remove deprecated chart.js code from ext:hashboard

Resolves: #101060
Related: #100963
Related: #99150
Releases: main
Change-Id: Ie0672b9eefeb52ef1266630dc45eff3f8c53617e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79375
Tested-by: core-ci <typo3@b13.com>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-100963-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -286,6 +286,7 @@ The following fallbacks have been removed:
 
 - Usage of the :file:`ext_icon.*` file locations for extension icons
 - Usage of the result property :php:`additionalJavaScriptPost` of the form engine result array
+- Using chart.js v3 compatible widgets in ext:dashboard
 
 The following features are now always enabled:
 
```

</details>

**Comment by brotkrueml** [comment]
See: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79457
