### ISSUE TITLE
[!!!][TASK] Remove deprecated file reference functionality

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#554]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/7d9f6190051a1c9bb0ba711e8877a15b55bf7911)
:busts_in_silhouette: Authored by Stefan Bürk stefan@buerk.tech
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[!!!][TASK] Remove deprecated file reference functionality

Removed class:

* TYPO3\CMS\Core\Resource\Service\UserFileInlineLabelService

Removed public method:

* TYPO3\CMS\Core\Resource\Filter\FileExtensionFilter
    ->filterInlineChildren

Removed public static method:

* TYPO3\CMS\Core\Utility\ExtensionManagementUtility
    ->getFileFieldTCAConfig

Resolves: #101082
Related: #100963
Related: #98479
Releases: main
Change-Id: I5a7519baa65a8296bd417b46a40b7ffe0d6e26c3
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79400
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Nikita Hovratov <nikita.h@live.de>
Tested-by: Nikita Hovratov <nikita.h@live.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-100963-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -29,6 +29,7 @@ The following PHP classes that have previously been marked as deprecated for v12
 - :php:`\TYPO3\CMS\Core\Exception\MissingTsfeException`
 - :php:`\TYPO3\CMS\Core\ExpressionLanguage\DeprecatingRequestWrapper`
 - :php:`\TYPO3\CMS\Core\Resource\Service\MagicImageService`
+- :php:`\TYPO3\CMS\Core\Resource\Service\UserFileInlineLabelService`
 - :php:`\TYPO3\CMS\Core\TypoScript\Parser\TypoScriptParser`
 - :php:`\TYPO3\CMS\Core\TypoScript\TemplateService`
 - :php:`\TYPO3\CMS\Core\Utility\ResourceUtility`
@@ -127,6 +128,7 @@ The following PHP class methods that have previously been marked as deprecated f
 - :php:`\TYPO3\CMS\Core\Database\Query\QueryBuilder->execute`
 - :php:`\TYPO3\CMS\Core\Domain\Repository\PageRepository->getExtURL`
 - :php:`\TYPO3\CMS\Core\Environment->getBackendPath`
+- :php:`\TYPO3\CMS\Core\Resource\Filter\FileExtensionFilter->filterInlineChildren`
 - :php:`\TYPO3\CMS\Core\Session\UserSessionManager->createFromGlobalCookieOrAnonymous`
 - :php:`\TYPO3\CMS\Dashboard\DashboardInitializationService->getRequireJsModules`
 - :php:`\TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager->getContentObject`
@@ -196,6 +198,7 @@ The following PHP static class methods that have previously been marked as depre
 - :php:`\TYPO3\CMS\Core\Utility\DebugUtility::debugRows`
 - :php:`\TYPO3\CMS\Core\Utility\DebugUtility::printArray`
 - :php:`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addLLrefForTCAdescr`
+- :php:`\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::getFileFieldTCAConfig`
 - :php:`\TYPO3\CMS\Core\Utility\GeneralUtility::_GET`
 - :php:`\TYPO3\CMS\Core\Utility\GeneralUtility::_GP`
 - :php:`\TYPO3\CMS\Core\Utility\GeneralUtility::_GPmerged`
```

</details>

**Comment by brotkrueml** [comment]
Two issues were opened to tackle with this in the according manuals:

- https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TCA/issues/727
- https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/3174

So this can be closed for now.
