### ISSUE TITLE
Important: #93635 - Add mail configuration for setting smtp domain

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#56]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/11.5.x/Important-93635-AddMailConfigurationForSettingSmtpDomain.html

**Comment by brotkrueml** [comment]
Already available: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/Configuration/Typo3ConfVars/MAIL.html#globals-typo3-conf-vars-mail-transport-smtp-domain
