### ISSUE TITLE
[!!!][TASK] Remove deprecated TS in ext:felogin

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#575]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f7f35ffa4f92fca22de63b72eae5e0c96d33b64f)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[!!!][TASK] Remove deprecated TS in ext:felogin

Removed the following TypoScript option in ext:felogin:
* plugin.tx_felogin_login.settings.passwordValidators

Resolves: #101097
Related: #100963
Related: #97390
Releases: main
Change-Id: Iae23d36e7cfb7ab1907544550cf11e0cb008cbf6
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79435
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-100963-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -364,6 +364,7 @@ The following TypoScript options have been dropped or adapted:
 - :typoscript:`[loginUser()]` condition function removed
 - :typoscript:`[usergroup()]` condition function removed
 - :typoscript:`constants` setup top-level-object and :typoscript:`constants` property of :typoscript:`parseFunc`
+- :typoscript:`plugin.tx_felogin_login.settings.passwordValidators` has been removed
 
 The following constants have been dropped:
 
```

</details>

**Comment by brotkrueml** [comment]
For EXT:felogin docs, see https://review.typo3.org/c/Packages/TYPO3.CMS/+/79464
