### ISSUE TITLE
[!!!][TASK] Remove deprecated code in SiteLanguage

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#584]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f5558dea76b85eef33756628349f00d85abc419c)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[!!!][TASK] Remove deprecated code in SiteLanguage

Removed the following public methods:
* \TYPO3\CMS\Core\Site\Entity\SiteLanguage->getTwoLetterIsoCode
* \TYPO3\CMS\Core\Site\Entity\SiteLanguage->getDirection

Resolves: #101112
Related: #100963
Related: #99905
Related: #99908
Releases: main
Change-Id: I15374e397a3fd3ebb2bede2d02d2f835104bcb0c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79451
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-100963-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -158,7 +158,9 @@ The following PHP class methods that have previously been marked as deprecated w
 - :php:`\TYPO3\CMS\Core\Page\PageRenderer->enableDebugMode`
 - :php:`\TYPO3\CMS\Core\Resource\Filter\FileExtensionFilter->filterInlineChildren`
 - :php:`\TYPO3\CMS\Core\Session\UserSessionManager->createFromGlobalCookieOrAnonymous`
-- :php:`TYPO3\CMS\Core\Type\DocType->getXhtmlDocType`
+- :php:`\TYPO3\CMS\Core\Site\Entity\SiteLanguage->getTwoLetterIsoCode`
+- :php:`\TYPO3\CMS\Core\Site\Entity\SiteLanguage->getDirection`
+- :php:`\TYPO3\CMS\Core\Type\DocType->getXhtmlDocType`
 - :php:`\TYPO3\CMS\Dashboard\DashboardInitializationService->getRequireJsModules`
 - :php:`\TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager->getContentObject`
 - :php:`\TYPO3\CMS\Extbase\Configuration\BackendConfigurationManager->setContentObject`
```

</details>

**Comment by brotkrueml** [comment]
- https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/SiteHandling/AddLanguages.html
- https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Conditions/Index.html
- https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Data.html
