### ISSUE TITLE
[FEATURE] Let Extbase handle native enums

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#608]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/431a6f25e877212066cf993b078644bdca7d779f)
:busts_in_silhouette: Authored by Alexander Schnitzler git@alexanderschnitzler.de
:heavy_check_mark: Merged by Stefan B�rk stefan@buerk.tech

## Commit message

[FEATURE] Let Extbase handle native enums

With PHP 8.1, native support for enums has been introduced.
This is quite handy if a database field has a specific set
of values which can be represented by a PHP enum.

Extbase does now support using native enums as entity
properties.

Releases: main
Resolves: #101396
Change-Id: Ic1d846224e05ab7026a01dd3e82b147bcc8264a4
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80099
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Stefan B�rk <stefan@buerk.tech>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Stefan B�rk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-101396-LetExtbaseHandleNativeEnums.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-101396-1689843367:

==================================================
Feature: #101396 - Let Extbase handle native enums
==================================================

See :issue:`101396`

Description
===========

With PHP 8.1, native support for enums has been introduces. This is quite handy
if a database field has a specific set of values which can be represented by a
PHP enum.

It is now possible to use those enums in entities like this:

..  code-block:: php

    <?php

    declare(strict_types=1);

    namespace Vendor\Extension\Domain\Model\Enum;

    enum Level: string
    {
        case INFO = 'info';
        case ERROR = 'error';
    }

..  code-block:: php

    <?php

    declare(strict_types=1);

    namespace Vendor\Extension\Domain\Model;

    class LogEntry extends AbstractEntity
    {
        protected Enum\Level $level;
    }

Impact
======

To implement enums, it is no longer necessary to extend the TYPO3 core class
:php:`\TYPO3\CMS\Core\Type\Enumeration`.

.. index:: PHP-API, ext:extbase

```

</details>

**Comment by brotkrueml** [comment]
Before adding this change to the docs, check if the Enumerations class is used in Extbase for that in older versions. And if yes, document it in a pre-patch.
