### ISSUE TITLE
 [FEATURE] Add getEnv value modifier to TS parser

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#63]
https://docs.typo3.org/c/typo3/cms-core/10.4/en-us/Changelog/9.4/Feature-85146-ReadEnvironmentVariablesInTypoScript.html

https://review.typo3.org/c/Packages/TYPO3.CMS/+/57115/

**Comment by brotkrueml** [comment]
Already available: https://docs.typo3.org/m/typo3/reference-typoscript/11.5/en-us/Functions/GetEnv.html
