### ISSUE TITLE
[!!!][FEATURE] Add UriBuilder->buildUriFromRequest

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#630]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/48d47274ab9e5c168f78e153a881fdd84df5fa51)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Stefan B�rk stefan@buerk.tech

## Commit message

[!!!][FEATURE] Add UriBuilder->buildUriFromRequest

This change adds a new method buildUriFromRequest
inside TYPO3's Backend UriBuilder in order to
generate links to the current (or any) request
with additional parameters.

This is quite helpful to link to the same module
/route when a request is given, thus reducing
code duplication and unifies link generation.

In addition, the determineScriptUrl() and
getScriptUrl() methods inside LinkBrowsers
and ElementBrowsers are removed, and have been
removed from the LinkParameterProviderInterface
as well.

Resolves: #101612
Releases: main
Change-Id: Ibaa2d2872178374e4553cf5899ee8ae19168480b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80433
Reviewed-by: Stefan B�rk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Stefan B�rk <stefan@buerk.tech>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Breaking-101612-LinkParameterProviderInterfaceChanged.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-101612-1691447955:

===========================================================
Breaking: #101612 - LinkParameterProvider Interface changed
===========================================================

See :issue:`101612`

Description
===========

The PHP interface :php:`TYPO3\CMS\Backend\Tree\View\LinkParameterProviderInterface`
has changed. The interface is used to generate URLs with query parameters for links
within Element Browsers or Link Browsers in the TYPO3 Backend.

The methods :php:`getScriptUrl()` and :php:`isCurrentlySelectedItem()` have been removed
from the interface, as the implementing Link Browsers do not need this information anymore
due to simplification in routing.

The method :php:`getUrlParameters()` now has a native return type :php:`array`, whereas
previously this was only type-hinted.


Impact
======

When accessing implementing PHP objects, it should be noted that these methods do not
exist anymore. When called this might result in fatal PHP errors.

When implementing the PHP interface, the implementing code will fail due to missing return
types.


Affected installations
======================

TYPO3 installations with custom implementations of this interface.


Migration
=========

For extensions implementing the interface, the return type for  :php:`getUrlParameters()`
can be added in order to be TYPO3 v12+ compatible. For v13-only compatibility,
it is recommended to remove the superfluous methods.

.. index:: PHP-API, PartiallyScanned, ext:backend
```

</details>

<details>
<summary>13.0/Feature-101612-UriBuilder-buildUriFromRequest.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-101612-1691425003:

==================================================
Feature: #101612 - UriBuilder->buildUriFromRequest
==================================================

See :issue:`101612`

Description
===========

A new method within :php:`TYPO3\CMS\Backend\Routing\UriBuilder` named `buildUriFromRequest` is added which allows to generate a URL to a backend route of this
request.


Impact
======

This is typically useful when linking to the current route or module in the TYPO3 Backend for
extension authors to avoid internals with any PSR-7 Request Attribute.

Usage within a PHP module controller in the TYPO3 Backend Context

: :php:`$this->uriBuilder->buildUriFromRequest($request, ['id' => $id]);`

.. index:: Backend, PHP-API, ext:backend
```

</details>

**Comment by brotkrueml** [comment]
See: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Backend/BackendRouting.html#generating-backend-urls
