### ISSUE TITLE
[FEATURE] Auto DB fields from TCA for type "file"

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#632]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/32eae43dd5e3f8eeea768a63dbed55d17e3a7213)
:busts_in_silhouette: Authored by Oliver Wand wand@itaw.de
:heavy_check_mark: Merged by Stefan B�rk stefan@buerk.tech

## Commit message

[FEATURE] Auto DB fields from TCA for type "file"

Tables with TCA columns set to type="file" do not
need an ext_tables.sql entry anymore. The core now
creates this field automatically.

This is the first patch in this area: The v13 goal
is to obsolete ext_tables.sql in most cases by
creating default "business" fields of TCA tables
automatically.

The patch adds the main magic in class DefaultTcaSchema
and removes own ext_tables.sql definitions having
type=file.
It goes through various functional test related .csv
fields, and adapts a broken TCA configuration in the
blog_example fixture extension revealed by this change.

Resolves: #101571
Related: #101553
Releases: main
Change-Id: Iae2c4bad2a0dc54628a8862b0c39f4913b0c5892
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80374
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Stefan B�rk <stefan@buerk.tech>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Stefan B�rk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-101553-Auto-createDBFieldsFromTCAColumns.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-101553-1691166389:

=========================================================
Feature: #101553 - Auto-create DB fields from TCA columns
=========================================================

See :issue:`101553`

Description
===========

The TYPO3 v13 core strives to auto-create database columns derived from
:php:`TCA` :php:`columns` definitions without explicitly declaring them in
:file:`ext_tables.sql`.

Creating "management" fields like :sql:`uid`, :sql:`pid` automatically derived
from :php:`TCA` :php:`ctrl` settings is available for a couple of core versions
already, the core now extends this to single :php:`TCA` :php:`columns`.

As a goal, extension developers should not need to maintain a
:file:`ext_tables.sql` definition for casual table columns anymore, the file can
vanish from extensions and the core takes care of creating fields with sensible
defaults.

Of course, it is still possible for extension authors to override single
definitions in :file:`ext_tables.sql` files in case they feel the core does
not define them in a way the extension author wants: Explicit definition in
:file:`ext_tables.sql` always take precedence over auto-magic.


Impact
======

Extension authors should start removing single column definitions from
:file:`ext_tables.sql` for extensions being compatible with TYPO3 v13 and up.

If all goes well, the database analyzer will not show any changes since the core
definition is identical to what has been defined in :file:`ext_tables.sql` before.

In various cases though, the responsible class :php:`DefaultTcaSchema` may come
to different conclusions than the extension author. Those cases should be reviewed
by extension authors one-by-one: Most often, the core declares a more restricted
field, which is often fine. In some cases though, the extension author may
know the particular field definition better than the core default, and may decide
to keep the field definition within :file:`ext_tables.sql`.

Columns are auto-created for these :php:`TCA` :php:`columns` types:

* :php:`type = 'category'` - core v12 already
* :php:`type = 'datetime'` - core v12 already
* :php:`type = 'slug'` - core v12 already
* :php:`type = 'json'` - core v12 already
* :php:`type = 'uuid'` - core v12 already
* :php:`type = 'file'` - new with core v13

.. index:: TCA, ext:core, NotScanned

```

</details>

**Comment by brotkrueml** [comment]
Possible places to add this information:

- https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ExtensionArchitecture/FileStructure/ExtTablesSql.html
- https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/File/Index.html

See also for an example:
- https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Slug/Examples.html

**Comment by brotkrueml** [comment]
For now on hold, will provide pre-patches to streamline the according chapters before tackling this one.

**Comment by brotkrueml** [comment]
Pre-patches merged. "onhold" removed.
