### ISSUE TITLE
[FEATURE] Add BeforeLoadedPageTsConfigEvent

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#645]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/e9907829d7a44e498d0fc4a875754a79f66f740d)
:busts_in_silhouette: Authored by Nikita Hovratov nikita.h@live.de
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] Add BeforeLoadedPageTsConfigEvent

With the recent deprecation of adding page TSconfig via ext_localconf
as a string, the need for a new PSR-14 event arose. This event can be
used to add global static page TSconfig before the global page.tsconfig
files are loaded. This allows extensions to add basic config, which
still can be overridden with page.tsconfig.

Resolves: #101818
Releases: main
Change-Id: Ic6fc0bff5e19c6c097c123386452b0e2bba0e17e
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80814
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-101818-BeforeLoadedPageTsConfigEvent.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-101818-1693570608:

================================================
Feature: #101818 - BeforeLoadedPageTsConfigEvent
================================================

See :issue:`101818`

Description
===========

The PSR-14 event :php:`\TYPO3\CMS\Core\TypoScript\IncludeTree\Event\BeforeLoadedPageTsConfigEvent`
can be used to add global static page TSconfig before anything else is loaded.
This is especially useful, if page TSconfig is generated automatically as a
string from a PHP function.

It is important to understand that this config is considered static and thus
should not depend on runtime / request.

Example
-------

.. code-block:: php

    <?php

    namespace Vendor\MyExtension\EventListener;

    use TYPO3\CMS\Core\Attribute\AsEventListener;
    use TYPO3\CMS\Core\TypoScript\IncludeTree\Event\BeforeLoadedPageTsConfigEvent;

    #[AsEventListener(identifier: 'vendor/my-extension/global-pagetsconfig')]
    final class AddGlobalPageTsConfig
    {
        public function __invoke(BeforeLoadedPageTsConfigEvent $event): void
        {
            $event->addTsConfig('global = a global setting');
        }
    }


Impact
======

Developers are able to define an event listener which is dispatched before any
other page TSconfig is loaded.

.. index:: Backend, PHP-API, ext:core

```

</details>

**Comment by brotkrueml** [comment]
<del>On hold until https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/3395 is merged.</del>
