### ISSUE TITLE
[FEATURE] Add BeforeLoadedUserTsConfigEvent

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#646]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f98fcd794d3624866a00f678ba3a0598e32e3e53)
:busts_in_silhouette: Authored by Nikita Hovratov nikita.h@live.de
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] Add BeforeLoadedUserTsConfigEvent

With the recent deprecation of adding user TSconfig via ext_localconf
as a string, the need for a new PSR-14 event arose. This event can be
used to add global static user TSconfig before the global user.tsconfig
files are loaded. This allows extensions to add basic config, which
still can be overridden with user.tsconfig.

Resolves: #101818
Related: #101807
Releases: main
Change-Id: I11c54682dc1ddfcf76e241a76384c9ff6cf71460
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80854
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-101838-BeforeLoadedUserTsConfigEvent.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-101838-1693834389:

================================================
Feature: #101838 - BeforeLoadedUserTsConfigEvent
================================================

See :issue:`101838`

Description
===========

The PSR-14 event :php:`\TYPO3\CMS\Core\TypoScript\IncludeTree\Event\BeforeLoadedUserTsConfigEvent`
can be used to add global static user TSconfig before anything else is loaded.
This is especially useful, if user TSconfig is generated automatically as a
string from a PHP function.

It is important to understand that this config is considered static and thus
should not depend on runtime / request.


Example
-------

..  code-block:: php

    <?php

    namespace Vendor\MyExtension\EventListener;

    use TYPO3\CMS\Core\Attribute\AsEventListener;
    use TYPO3\CMS\Core\TypoScript\IncludeTree\Event\BeforeLoadedUserTsConfigEvent;

    #[AsEventListener(identifier: 'vendor/my-extension/global-usertsconfig')]
    final class AddGlobalUserTsConfig
    {
        public function __invoke(BeforeLoadedUserTsConfigEvent $event): void
        {
            $event->addTsConfig('global = a global setting');
        }
    }


Impact
======

Developers are able to define an event listener which is dispatched before any
other user TSconfig is loaded.

.. index:: Backend, PHP-API, TSConfig, ext:core

```

</details>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Feature-101818-BeforeLoadedPageTsConfigEvent.rst</summary>

```diff
@@ -22,7 +22,7 @@ should not depend on runtime / request.
 Example
 -------
 
-.. code-block:: php
+..  code-block:: php
 
     <?php
 
@@ -47,4 +47,4 @@ Impact
 Developers are able to define an event listener which is dispatched before any
 other page TSconfig is loaded.
 
-.. index:: Backend, PHP-API, ext:core
+.. index:: Backend, PHP-API, TSConfig, ext:core
```

</details>

**Comment by brotkrueml** [comment]
<del>On hold until https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/3395 is merged.</del>
