### ISSUE TITLE
[FEATURE] Add "Edit Metadata" button to element information view

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#658]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/3b6d493125dd642b21cbed35ba0e796b305b5932)
:busts_in_silhouette: Authored by Stefan Froemken froemken@gmail.com
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] Add "Edit Metadata" button to element information view

This introduces a new "Edit Metadata" button
to the element information view of files,
allowing to directly edit the file's
Metadata without losing the context.

Resolves: #99165
Releases: main
Change-Id: Ie32d3bdb31013c195f0efc58cb830c35c6d64a9c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76769
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-99165-AddEditButtonToElementInformation.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99165-1669201746:

========================================================================
Feature: #99165 - Add "Edit Metadata" button to element information view
========================================================================

See :issue:`99165`

Description
===========

A new button "Edit Metadata" has been added to the element information view
of files. It allows to directly edit corresponding Metadata without leaving
the context. The element information view for files can be accessed via the
context menu or via the secondary action of files in any file listing,
e.g. in the :guilabel:`Filelist` module or the :guilabel:`File selector`.

Impact
======

It's now possible to edit a file's Metadata directly in the element information
view, which improves the UX as the context is not lost.

.. index:: Backend, ext:backend

```

</details>

**Comment by linawolf** [comment]
No need to document
