### ISSUE TITLE
[FEATURE] Allow updating online media assets

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#659]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f4b1d41caa259836edd883ce4b59f24f17cb6236)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[FEATURE] Allow updating online media assets

A new controller is added, which allows
to update Metadata of online media assets.

This basically updates the preview image
and some basic data like author and the
assets dimensions.

To trigger the update, a new action is
available in the context menu and the
secondary dropdown of online media assets.

The functionality can be extended in the
future to update further information like
the asset's title. However, this needs some
more considerations, because an editor might
already changed the title intentionally.

Resolves: #82855
Releases: main
Change-Id: Iba82400c582de0d4e7b2d4eab219a86bc4830be6
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81083
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Jochen Roth <rothjochen@gmail.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Andreas Nedbal <andy@pixelde.su>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Andreas Nedbal <andy@pixelde.su>
Tested-by: Jochen Roth <rothjochen@gmail.com>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Sebastian Tittel <sebastiantittel@mail.de>
Reviewed-by: Oliver Bartsch <bo@cedev.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-82855-UpdateMetadataOfOnlineMediaAssets.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-82855-1695120648:

=========================================================
Feature: #82855 - Update Metadata of online media assets
=========================================================

See :issue:`82855`

Description
===========

A new action :guilabel:`Reload Metadata` has been added to the secondary
options dropdown of online media assets, such as youtube and vimeo videos,
in the :guilabel:`Filelist` module. Additonally also the context menu of
such files has been extended for the new action.

The action allows to reload the corresponding information from the external
service. Those information are e.g. the preview image, the author or the
dimensions of the online media asset.

Impact
======

It's now possible to reload the Metadata of an online media asset using the
new :guilabel:`Reload Metadata` action.

.. index:: Backend, FAL, ext:filelist

```

</details>

**Comment by linawolf** [comment]
No need to document
