### ISSUE TITLE
[FEATURE] AJAX API accepts native `URL` and `URLSearchParams` objects as arguments

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#665]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/e2416fa3eb90ab4acefe04e4a87a0b6e4eaf3257)
:busts_in_silhouette: Authored by Andreas Fernandez a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Andreas Fernandez a.fernandez@scripting-base.de

## Commit message

[FEATURE] AJAX API accepts native `URL` and `URLSearchParams` objects as arguments

The AJAX API (`@typo3/core/ajax/ajax-request`) has been enhanced to
accept native URL-related objects, making usage of the API for
developers a little bit easier.

Resolves: #101970
Releases: main
Change-Id: Ica7c8d5ded7184c5aad6355dbdfa5c4f1f82b0ce
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81100
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Tested-by: Andreas Fernandez <a.fernandez@scripting-base.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-101970-AJAXAPIAcceptsNativeURLAndURLSearchParamsObjectsAsArguments.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-101970-1695205584:

=======================================================================================
Feature: #101970 - AJAX API accepts native URL and URLSearchParams objects as arguments
=======================================================================================

See :issue:`101970`

Description
===========

The AJAX API (:js:`@typo3/core/ajax/ajax-request`) has been enhanced to accept
native URL-related objects.


Impact
======

The constructor now accepts a :js:`URL` object as argument, along with the
already established `string` type. Also, the :js:`withQueryString()` method
accepts an object of type :js:`URLSearchParams` as argument.

Example
-------

.. code-block:: javascript

    import AjaxRequest from '@typo3/core/ajax/ajax-request.js';

    const url = new URL('https://example.com/page/1/2/');
    const queryArguments = new URLSearchParams({
        foo: 'bar',
        baz: 'bencer'
    });

    const request = new AjaxRequest(url).withQueryArguments(queryArguments);
    request.get().then(/* ... */);


.. index:: JavaScript, ext:core

```

</details>

**Comment by brotkrueml** [comment]
https://docs.typo3.org/m/typo3/reference-coreapi/12.4/en-us/ApiOverview/Backend/AjaxClientSide.html
