### ISSUE TITLE
[!!!][FEATURE] Dispatch AfterUserLoggedInEvent for frontend user login

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#669]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/2cf9e4f7aff597f8e9a6464439cc692ddb0b82bb)
:busts_in_silhouette: Authored by Torben Hansen derhansen@gmail.com
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[!!!][FEATURE] Dispatch AfterUserLoggedInEvent for frontend user login

The `AfterUserLoggedInEvent` introduced with TYPO3 12.3 is currently
only triggered for a successful backend login.

With this change, the `AfterUserLoggedInEvent` is now also dispatched,
when a successful frontend user login is performed.

Resolves: #101933
Releases: main
Signed-off-by: Torben Hansen <derhansen@gmail.com>
Change-Id: Iab3361032697fc214040a1cd4d2b54e5a91ac496
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81033
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Breaking-101933-DispatchAfterUserLoggedInEventForFrontendUserLogin.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-101933-1695472624:

===========================================================================
Breaking: #101933 - Dispatch AfterUserLoggedInEvent for frontend user login
===========================================================================

See :issue:`101933`

Description
===========

The :php:`AfterUserLoggedInEvent` PSR-14 event is now also dispatched for
a successful frontend user login.


Impact
======

Listeners to the :php:`AfterUserLoggedInEvent` event should evaluate the
implementation type of the :php:`$user` property, if custom functionality
after a user login should be executed for backend login only.


Affected installations
======================

Installations with an event listener to the php:`AfterUserLoggedInEvent` PSR-14
event.


Migration
=========

If custom functionality in a listener to the :php:`AfterUserLoggedInEvent`
event should be executed for the backend user login only, a type check for the
:php:`$user` property must be added.

.. code-block:: php

   // Before
   public function __invoke(AfterUserLoggedInEvent $afterUserLoggedInEvent): void
   {
       // custom logic after backend user login
   }

   // After
   public function __invoke(AfterUserLoggedInEvent $afterUserLoggedInEvent): void
   {
       if ($afterUserLoggedInEvent->getUser() instanceof BackendUserAuthentication) {
           // custom logic after backend user login
       }
   }

.. index:: Backend, NotScanned, ext:backend

```

</details>

<details>
<summary>13.0/Feature-101933-DispatchAfterUserLoggedInEventForFrontendUserLogin.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-101933-1694883742:

==========================================================================
Feature: #101933 - Dispatch AfterUserLoggedInEvent for frontend user login
==========================================================================

See :issue:`101933`

Description
===========

The :php:`AfterUserLoggedInEvent` PSR-14 event, which has been introduced
with TYPO3 12.3, is now also triggered, when a frontend user has successfully
been authenticated.


Impact
======

It is now possible to modify and adapt user functionality based on successful
frontend user login.

.. index:: Frontend, PHP-API, ext:frontend

```

</details>

**Comment by brotkrueml** [comment]
On hold until https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/3395 is merged.
