### ISSUE TITLE
[BUGFIX] Add CKEditor5 migrator for {extraA,disa,a}llowedContent

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#686]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/4f99a8d15715404fea7304788e7a75e0061169a1)
:busts_in_silhouette: Authored by Benjamin Franzke ben@bnf.dev
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[BUGFIX] Add CKEditor5 migrator for {extraA,disa,a}llowedContent

Allowed content in CKEditor5 is to be configured via the
General HTML Support plugin option config.htmlSupport.
CKEditor4 style configs are now parsed and migrated.

Note that this config.htmlSupport only applies to elements that
are "known" to CKEditor5. Tags like "svg" or custom elements like
"<foo-bar>" are not configurable this way as `htmlSupport.(dis)allow`
can only handle elements that are defined in the CKEditor5 schema. [1]

Also reintroduce the default configuration that allows any class
and any attribute that starts with data- to be specified/preserved on
known tags. This was removed with #96874.

[1] https://ckeditor.com/docs/ckeditor5/latest/features/html/general-html-support.html#enabling-custom-elements

Resolves: #99738
Releases: main, 12.4
Change-Id: Idaadfc09328efa4d1f21171a400dc45d29ed5904
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81316
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Feature-96874-CKEditor5.rst</summary>

```diff
@@ -61,7 +61,7 @@ The following options are not needed anymore in CKEditor 5:
 *    editor.config.removeDialogTabs
 *    editor.config.entities_latin
 *    editor.config.entities
-*    editor.config.extraAllowedContent (covered via GeneralHTMLSupport plugin)
+*    editor.config.extraAllowedContent (migrated to editor.config.htmlSupport, covered via GeneralHTMLSupport plugin)
 *    :php:`$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['rte_ckeditor']['plugins']['TYPO3Link']['additionalAttributes']`
 
 More migration options can be found here:
```

</details>

**Comment by brotkrueml** [comment]
See:
81383: [DOCS] Document usage of "htmlSupport" option in EXT:rte_ckeditor | https://review.typo3.org/c/Packages/TYPO3.CMS/+/81383
