### ISSUE TITLE
[!!!][TASK] Simplify adminPanel forceTemplateParsing

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#741]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/57b5ef2cfe89005b30c89501c6f0503645e4bef6)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Simplify adminPanel forceTemplateParsing

EXT:adminpanel class TypoScriptWaterfall sets both
'no_cache' and the typoscript context aspect
'forcedTemplateParsing' to true when the admin
panel related option 'Force template parsing' is
enabled.

This setting is "on" by either using the admin panel
FE interface (which stores settings in BE user "uc"),
or using BE user UserTsConfig
admPanel.override.tsdebug.forceTemplateParsing = 1.

All consumers of the forcedTemplateParsing aspect
property (namely in TypoScriptFrontendController)
always check both 'no_cache' and 'forcedTemplateParsing',
so that's duplicate information.

The patch removes the 'typoscript' context aspect
altogether and simplifies consumers to rely on the
'no_cache' flag only.

Resolves: #102583
Releases: main
Change-Id: I33599ff7c23ce48102f9473d74ae1358f343c36c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82066
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Breaking-102583-RemovedContextAspectTyposcript.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-102583-1701510037:

=====================================================
Breaking: #102583 - Removed context aspect typoscript
=====================================================

See :issue:`102583`

Description
===========

The :php:`TYPO3\CMS\Core\Context\Context` aspect :php:`typoscript` has been
removed without direct substitution. This aspect was implemented by now removed
class :php:`TYPO3\CMS\Core\Context\TypoScriptAspect`, handling the EXT:adminpanel
related property :php:`forcedTemplateParsing`.


Impact
======

The following calls with throw PHP exceptions:

.. code-block:: php

    /** @var \TYPO3\CMS\Core\Context\Context $context */
    $context->getPropertyFromAspect('typoscript', 'forcedTemplateParsing');
    $context->getAspect('typoscript');
    // Returns false
    $context->hasAspect('typoscript');

Affected installations
======================

Extensions typically do not use this context aspect since it only carried an
EXT:adminpanel related information.


Migration
=========

No direct migration possible. There should be little reason for extensions to
work with this EXT:adminpanel related detail.


.. index:: Frontend, PHP-API, PartiallyScanned, ext:core

```

</details>

**Comment by brotkrueml** [comment]
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Context/Index.html#typoscript-aspect
