### ISSUE TITLE
[FEATURE] Provide full userdata in password recovery email

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#743]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/9e1e9493ff5e0b615e4921b2612226c684759d3f)
:busts_in_silhouette: Authored by Torben Hansen derhansen@gmail.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Provide full userdata in password recovery email

Currently, the variables `receiverName`, `url` and `validUntil` are
available in the template of the password recovery email. If more
user related data is required in the recovery email, integrators
have to use the PSR-14 event `SendRecoveryEmailEvent` to add
additional variables to the email object.

To simplify customization of the password recovery email for
frontend users, this patch adds the new variable `userData` to
the FluidEmail object, which contains all userdata of the
affected frontend user.

Resolves: #100268
Releases: main
Signed-off-by: Torben Hansen <derhansen@gmail.com>
Change-Id: I032f775e01003a5a276f8e2d0310925ea1592dc7
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/81605
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Guido Schmechel <guido.schmechel@brandung.de>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-100268-ProvideFullUserdataInPasswordRecoveryEmail.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-100268-1698511146:

===================================================================
Feature: #100268 - Provide full userdata in password recovery email
===================================================================

See :issue:`100268`

Description
===========

A new array variable :php:`{userData}` has been added to the password
recovery FluidEmail object. It contains the values of all fields belonging
to the affected frontend user.


Impact
======

It is now possible to use the :php:`{userData}` variable in the password
recovery FluidEmail to access data from the affected frontend user.

.. index:: Frontend, ext:felogin

```

</details>

**Comment by brotkrueml** [comment]
The new possibility should be mentioned on the event page:

https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Events/Events/FrontendLogin/SendRecoveryEmailEvent.html

as a hint that the user information is now also available in the Fluid template directly.
