### ISSUE TITLE
[!!!][TASK] Avoid TSFE->applicationData

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#745]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/d893dd72d2c0a9cc6d0f5fa352479aa0aab928c4)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Avoid TSFE->applicationData

Property applicationData of TypoScriptFrontendController
is unfortunate: It is meant as an extension place to park
and communicate state using the just so convenient global
$GLOBALS['TSFE'] object.

Such things should of course be modeled differently, for
instance by adding own PSR-7 request attributes using a
custom middleware, or by firing own events for other
extensions to listen on.

In order to continue with our works on TSFE, the patch
removes that property.

The single use of that property in is ext:indexed_search:
It is used in combination with the crawler extension to
"force indexing". indexed_search now dispatches a proper
event instead.

Resolves: #102600
Releases: main
Change-Id: I2fdcbee8c196761670245cd90cb99414fc9beea7
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82085
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Breaking-102600-TSFE-applicationDataRemoved.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-102600-1701707508:

=================================================
Breaking: #102600 - TSFE->applicationData removed
=================================================

See :issue:`102600`

Description
===========

Frontend related property :php:`TypoScriptFrontendController->applicationData`
has been removed without substitution.

This property has been used by a few rather old-school extensions to park and
communicate state using this global "extension specific state array".

When looking at the TYPO3 Frontend rendering chain, class :php:`TypoScriptFrontendController`
is by far the biggest technical debt: It mixes a lot of concerns and carries tons of state
and functionality that should be modeled differently, which leads to easier to understand
and more flexible code. The class is shrinking since various major versions already and will
ultimately dissolve entirely at some point. Changes in this area are becoming more aggressive
with TYPO3 v13. Any code using the class will need adaptions at some point, single patches
will continue to communicate alternatives.

In case of the :php:`applicationData` property, this is simply a misuse of the
class instance to park arbitrary state in a global object. This is why it needs to
fall and why there is no direct substitution.


Impact
======

Using :php:`TypoScriptFrontendController->applicationData` (or
:php:`$GLOBALS['TSFE']->applicationData`) will raise a PHP fatal error.


Affected installations
======================

Instances with extensions that use :php:`applicationData` to store and communicate
state.


Migration
=========

There are various solutions to communicate state to avoid :php:`applicationData`:

In some cases, an extension could establish a Frontend middleware and attach a
Request attribute that carries the state.

In other cases an event could be fired to gather information from other extensions.
One example is the indexed_search extension which dispatches the new event
:php:`EnableIndexingEvent` to get know if indexing should be performed. The 3rd
party crawler extension should use this instead of setting that information
on :php:`$GLOBALS['TSFE']`.


.. index:: Frontend, PHP-API, FullyScanned, ext:frontend

```

</details>

**Comment by brotkrueml** [comment]
The newly added event "EnableIndexingEvent" is not mentioned in a feature RST as it is intended not to be documented according to Lolli.
