### ISSUE TITLE
[!!!][TASK] Avoid TSFE->fe_user

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#747]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/e7204abb37de4be40ef1ce0a209d30ccd4c24ab6)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Avoid TSFE->fe_user

TypoScriptFrontendController->fe_user is the current
FrontendUserAuthentication object. It is set when
constructing the instance.

Since TypoScriptFrontendController is also still set
as $GLOBALS['TSFE'], some extensions tend to fetch
the current FE user from this global state, and
sometimes even inject that into other classes like
repositories. Extension felogin is a victim here: It
models some state of FrontendUserAuthentication in the
service object 'UserService', to then inject this into
repositories and other classes. This indirection is an
anti-pattern.

The current Frontend user is already available either
as Request attribute 'frontend.user', and a limited
list of user details is also available as context
aspect.

The patch removes TSFE->fe_user entirely and dissolves
the offending felogin class. Various other core usages
are adapted as well to avoid fetching this state from
TypoScriptFrontendController.

Resolves: #102605
Releases: main
Change-Id: Ibc33cefa2b24658406a7c0f7ce8fd80eaf7c9f3b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82089
Reviewed-by: Sascha Nowak <sascha.nowak@netlogix.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Breaking-102605-TSFE-fe_userRemoved.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-102605-1701772495:

=========================================
Breaking: #102605 - TSFE->fe_user removed
=========================================

See :issue:`102605`

Description
===========

Frontend related property :php:`TypoScriptFrontendController->fe_user` has been removed.

When looking at the TYPO3 Frontend rendering chain, class :php:`TypoScriptFrontendController`
is by far the biggest technical debt: It mixes a lot of concerns and carries tons of state
and functionality that should be modeled differently, which leads to easier to understand
and more flexible code. The class is shrinking since various major versions already and will
ultimately dissolve entirely at some point. Changes in this area are becoming more aggressive
with TYPO3 v13. Any code using the class will need adaptions at some point, single patches
will continue to communicate alternatives.

In case of the :php:`fe_user` property, two alternatives exist: The frontend user
can be retrieved from the :php:`Request` attribute :php:`frontend.user`, and basic frontend user
information is available using the :php:`Context` aspect :php:`frontend.user`.

Note accessing TypoScript :typoscript:`TSFE:fe_user` details continues to work for now, using
for example :typoscript:`lib.foo.data = TSFE:fe_user|user|username` to retrieve the username of a
logged in user is still ok.


Impact
======

Using :php:`TypoScriptFrontendController->fe_user` (or
:php:`$GLOBALS['TSFE']->fe_user`) will raise a PHP fatal error.


Affected installations
======================

Instances with extensions dealing with frontend user details may be affected, typically
custom login extensions or extensions consuming detail data of logged in users.


Migration
=========

There are two possible migrations.

First, a limited information list of frontend user details can be retrieved using the :php:`Context`
aspect :php:`frontend.user` in Frontend calls. See class :php:`TYPO3\CMS\Core\Context\UserAspect` for a
full list. The current context can retrieved using dependency injection. Example:

.. code-block:: php

    use TYPO3\CMS\Core\Context\Context;

    final class MyExtensionController {
        public function __construct(
            private readonly Context $context,
        ) {}

        public function myAction() {
            $frontendUserUsername = $this->context->getPropertyFromAspect('frontend.user', 'username', ''));
        }
    }

Additionally, the full :php:`TYPO3\CMS\Frontend\Authentication\FrontendUserAuthentication` object is
available as request attribute :php:`frontend.user` in the frontend. Note some details of that object
are marked :php:`@internal`, using the context aspect is thus the preferred way. Example of an extension
using the extbase :php:`ActionController`:

.. code-block:: php

    final class MyExtensionController extends ActionController {
        public function myAction() {
            // Note the 'user' property is marked @internal.
            $frontendUserUsername = $this->request->getAttribute('frontend.user')->user['username'];
        }
    }


.. index:: Frontend, PHP-API, FullyScanned, ext:frontend

```

</details>

**Comment by brotkrueml** [comment]
For example, mentioned here: https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/AppendixA/Index.html#internal-variables-in-the-main-frontend-object-tsfe

Also other places have to be checked.
