### ISSUE TITLE
[!!!][TASK] Clean up Context

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#767]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/2c30be8afbbe75ee517e82f40c66c405f42444f5)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Clean up Context

The constructor of class Context is unfortunate: It
needs to be registered in DI container to be injectable.
If an extension uses GU::makeInstance() with manual
constructor arguments of this class, it could shortcut
the container lookup and would create an own instance
not registered in the container, which could lead to
a second instance when Context is injected. The
constructor is only used in tests, tests are adapted
and constructor removed with the patch.

Also, the two classes ContextAwareInterface and
ContextAwareTrait look as if they are general things
that can be used similar to the PSR-3 LoggerAwareInterface
which is handled directly in DI / makeInstance(), but in
fact it is just a detail of the core routing aspect
handling. In those cases, DI / makeInstance() can be used
directly. We drop both classes to avoid confusion. Note
this also makes AspectFactory stateless.

Resolves: #102645
Releases: main
Change-Id: Ice0d4063bcfc8ff0c267f1b8155eab576d7d6772
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82159
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Breaking-102645-MoreStrictContextHandling.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-102645-1702194379:

================================================
Breaking: #102645 - More strict Context handling
================================================

See :issue:`102645`

Description
===========

Class :php:`TYPO3\CMS\Core\Context\Context` is a stateful singleton class set up
pretty early by the Frontend or Backend application after the Request object has been created.
Its state is then further changed by various Frontend and Backend middlewares. It can
be retrieved using dependency injection or :php:`GeneralUtility::makeInstance()` in consuming
classes.

To clean up Context related code a bit, the following changes have been made:

* Method :php:`__construct()` removed from :php:`TYPO3\CMS\Core\Context\Context`
* Class :php:`TYPO3\CMS\Core\Context\ContextAwareInterface` removed
* Trait :php:`TYPO3\CMS\Core\Context\ContextAwareTrait` removed


Impact
======

Handing over manual arguments to the constructor of :php:`__construct()` does not have
an effect anymore, and using the interface or the trait will raise a fatal PHP error.


Affected installations
======================

Most likely, not too many instances are affected: An instance of :php:`Context` is
typically created by core bootstrap and retrieved using dependency injection, extensions
usually do not need to create own instances.

There are also not many routing aspects with context dependencies that may use the
interface or the trait. If so, they can adapt easily and stay compatible with older
versions.


Migration
=========

The constructor of the Context class was bogus. Since the class is an injectable singleton
that should be available through the container, it must not have manual constructor arguments
since this would shut down the container registration. Extensions typically did not create
own instances of :php:`Context`, using the constructor argument was - if at all - only done
in tests. Unit tests should typically create own instances using :php:`new` and hand them
over to classes that get the context injected.

Adaption to the interface and trait removal is straight forward as well: Get the
context injected into the aspect, or retrieve the instance using :php:`GeneralUtility::makeInstance()`.


.. index:: PHP-API, PartiallyScanned, ext:core

```

</details>

**Comment by brotkrueml** [comment]
Another trait should be used here:
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Reference/Code/Phpdomain.html#namespace-TYPO3\CMS\Core\Context
