### ISSUE TITLE
[!!!][TASK] Set PHP 8.2 as minimum required version

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#781]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/cf787275af6e8df3f6f7c4032ad655c57da8a61d)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[!!!][TASK] Set PHP 8.2 as minimum required version

TYPO3 v13 will require PHP 8.2 as minimum
PHP version to be used.

Used commands:
> composer config platform.php 8.2.0
> composer req "php:^8.2" --no-update
> composer update --lock

Resolves: #102779
Releases: main
Change-Id: I4765cd4421ad3d6311f8e2a2411e15725ca45de8
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82371
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Breaking-102779-TYPO3V13SystemRequirements.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-102779-1704721008:

=================================================
Breaking: #102779 - TYPO3 v13 System Requirements
=================================================

See :issue:`102779`

Description
===========

The minimum PHP version required to run TYPO3 version v13 has been defined as 8.2.

TYPO3 v13 supports these database products and versions:

* MySQL 8.0.17 or higher
* MariaDB 10.4.3 or higher
* PostgresSQL 10.0 or higher
* SQLite 3.8.3 or higher


Impact
======

The TYPO3 Core codebase and extensions tailored for v13 and above can use
features implemented with PHP up to and including 8.2. Running TYPO3 v13 with
older PHP versions or database engines will trigger fatal errors.


Affected installations
======================

Hosting a TYPO3 instance based on version 13 may require an update of the
PHP platform and the database engine.


Migration
=========

TYPO3 v11 / v12 supports PHP 8.2 and database engines required by v13. This
allows upgrading the platform in a first step and upgrading to TYPO3 v13 in a
second step.

.. index:: PHP-API, NotScanned, ext:core

```

</details>

## :heavy_division_sign: Modified files

<details>
<summary>Changelog/Howto.rst</summary>

```diff
@@ -166,7 +166,7 @@ Like other documentation, changelog files are done in ReST, see
 -   Types "Deprecation" and "Breaking" contain an "Affected installations"
     section that describes when and if a TYPO3 instance is affected by a change.
     Example: "Extension xy is in use" or "TypoScript functionality xy is used"
-    or "System is based on PHP 8.1".
+    or "System is based on PHP 8.2".
 
 -   Types "Deprecation" and "Breaking" contain a "Migration" section to
     describe best practices on how to cope with a specific change.
```

</details>

**Comment by brotkrueml** [comment]
We can introduce rector to migrate our code examples for main (v13) to PHP 8.2 features for TYPO3 Explained. However, this should be done later in 2024, maybe around September/Octorber - so backports to v12 are easier for the time being.

Same for EXT:examples and EXT:blog_example.
