### ISSUE TITLE
[FEATURE] Add ApplicationContext to TypoScript data

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#790]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/3b93e0e27bbc412d4988ba47b8882b9bbe2d4b0a)
:busts_in_silhouette: Authored by Daniel Siepmann daniel.siepmann@typo3.org
:heavy_check_mark: Merged by Anja Leichsenring aleichsenring@ab-softlab.de

## Commit message

[FEATURE] Add ApplicationContext to TypoScript data

The current application context was already available within conditions.
It now is also added to data. That way it can be inserted via
insertData, dataWrap and data.

Resolves: #102815
Releases: main
Change-Id: I4cd25d89a0c020ccade5497570f1b4338b65b41a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82431
Reviewed-by: Nikita Hovratov <nikita.h@live.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Nikita Hovratov <nikita.h@live.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-102815-SupportApplicationContextInTypoScriptData.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-102815-1704964154:

================================================================
Feature: #102815 - Support ApplicationContext in TypoScript data
================================================================

See :issue:`102815`

Description
===========

The new key :typoscript:`applicationcontext` is added for TypoScript's data
function.

The application context is now available through:

.. code-block:: typoscript

   if {
       value.data = applicationcontext
       equals = Production
   }

Impact
======

It is now possible to fetch the current application context as full blown
string from TypoScript's :typoscript:`data` function.

.. index:: TypoScript, ext:frontend

```

</details>

**Comment by Christobal79** [comment]
On it.

**Comment by brotkrueml** [comment]
On this page: https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Data.html
