### ISSUE TITLE
[!!!][TASK] Remove ConsumableNonce->b64

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#791]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/946154488808f219194697cf7b2178f70daebf52)
:busts_in_silhouette: Authored by Simon Schaufelberger simonschaufi+typo3@gmail.com
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[!!!][TASK] Remove ConsumableNonce->b64

It has been deprecated with TYPO3 v12.4.8 and is now removed.

Resolves: #102754
Related: #101751
Related: #100963
Releases: main
Change-Id: I71580e01dc74f0fdf085141104b981ac6d215c2b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82311
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-100963-DeprecatedFunctionalityRemoved.rst</summary>

```diff
@@ -277,6 +277,7 @@ The following public class properties have been dropped:
 - :php:`\TYPO3\CMS\Backend\Tree\View\AbstractTreeView->BE_USER`
 - :php:`\TYPO3\CMS\Backend\Tree\View\AbstractTreeView->thisScript`
 - :php:`\TYPO3\CMS\Core\Localization\LanguageService->debugKey`
+- :php:`\TYPO3\CMS\Core\Security\ContentSecurityPolicy\ConsumableNonce->b64`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->lastTypoLinkLD`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->lastTypoLinkTarget`
 - :php:`\TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->lastTypoLinkUrl`
```

</details>

**Comment by brotkrueml** [comment]
First, this one has to be included into the docs:
https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/712
