### ISSUE TITLE
[TASK] Add localRootLine and sysTemplateRows to PageInformation

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#797]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/e5535d5e50d04548e64b72371fc1bcca765219ca)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[TASK] Add localRootLine and sysTemplateRows to PageInformation

FE knows two root lines: TSFE->rootLine, which is the
'full' path to pid 0, and TSFE->config['rootLine'], which
is only the 'local' path to the 'root' sys_template record.

The full root line is already PageInformation->getRootLine(),
created by 'TypoScriptFrontendInitialization' middleware.
The very next middleware 'PrepareTypoScriptFrontendRendering'
then gets sys_template records and calculates the local
root line.

The patch relocates sys_template fetching and calculation
of the local root line to 'TypoScriptFrontendInitialization',
now additionally handled in PageInformationFactory.

Both sys_template rows and the local root line are now
modeled in PageInformation, which is already attached
as 'frontend.page.information' Request attribute.

Both root lines are now parellal to each other in the
same object, making the entire thing hopefully more easy
to understand. Usages are adapted accordingly, further
reducing dependencies to TSFE.

Note the sys_template row getter is marked @internal since
extensions usually don't need to mess around with this.

As a side effect, the local root line is no longer cached
in page cache: Caching this was duplicate data since
sys_template rows need to be fetched for *every* call,
and deriving local root line is quick and trivial.
This slightly reduces the size of the page cache for a
calculation that happens anyway.

Resolves: #102873
Releases: main
Change-Id: I79c1c138c6ae43fb67dca0d056f67c3c24266f5f
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82517
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Sascha Nowak <sascha.nowak@netlogix.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Benni Mack <benni@typo3.org>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-102621-MostTSFEMembersMarkedInternalOrRead-only.rst</summary>

```diff
@@ -55,6 +55,7 @@ The following public class properties have been marked "read only":
 * :php:`TypoScriptFrontendController->config` - Reading :php:`$tsfe->config['config']` and :php:`$tsfe->config['rootLine']` is allowed
 * :php:`TypoScriptFrontendController->absRefPrefix`
 * :php:`TypoScriptFrontendController->cObj`
+* :php:`TypoScriptFrontendController->config['rootLine']` - Use :php:`$request->getAttribute('frontend.page.information')->getLocalRootLine()` instead
 
 The following public class properties have been marked :php:`@internal` - in general
 all properties not listed above:
```

</details>

**Comment by brotkrueml** [comment]
Related to #752
