### ISSUE TITLE
[FEATURE] Introduce class to generate/validate HMAC hashes

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#807]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/496c4303bee0e1c9fe56619e9b1f05560748e20c)
:busts_in_silhouette: Authored by Torben Hansen derhansen@gmail.com
:heavy_check_mark: Merged by Oliver Hader oliver.hader@typo3.org

## Commit message

[FEATURE] Introduce class to generate/validate HMAC hashes

The `GeneralUtility::hmac()` function is used in several places
to create HMAC hashes for a given string and optional additional
secret.

Extbase has the class `HashService`, which also provides the
ability to create a HMAC for a given string, but without the
possibility to add an additional secret. The missing possibility
to use an additional secret is suboptimal in terms of security,
since generated HMAC hashes will be equal for the same input
in different contexts.

This change introduces a new class, which combines the
functionality of `GeneralUtility::hmac()` and Extbase
`HashService` but with the requirement, that an additional
secret is always mandatory.

The class will be used in follow up patches, where
`GeneralUtility::hmac()` and Extbase `HashService` will be
deprecated.

Resolves: #102761
Releases: main
Signed-off-by: Torben Hansen <derhansen@gmail.com>
Change-Id: Ibf0be09f4dffe076ddd0d3a31323ccd05693f7c1
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80394
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Andreas Kienast <a.fernandez@scripting-base.de>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-102761-IntroduceClassToGeneratevalidateHMACHashes.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-102761-1704532036:

===================================================================
Feature: #102761 - Introduce class to generate/validate HMAC hashes
===================================================================

See :issue:`102761`

Description
===========

A new class  :php:`TYPO3\CMS\Core\Crypto\HashService` has been introduced to
enhance the security and flexibility in generating Hash-based Message
Authentication Codes (HMACs). This class combines the functionality of
:php:`GeneralUtility::hmac()` and the Extbase :php:`HashService`, while
enforcing the use of an additional, mandatory secret for HMAC generation and
HMAC string validation.


Impact
======

Using the new class  :php:`TYPO3\CMS\Core\Crypto\HashService`, it is now
possible to mitigate the risk of HMAC reuse in unauthorized scenarios for the
same input.

.. index:: ext:core

```

</details>

**Comment by linawolf** [comment]
It is already mentioned in the places where GU::hmac() was used before
