### ISSUE TITLE
Feature: #83912 - Specify Section in Redirect Finisher

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#81]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Feature-83912-SpecifySectionRedirectFinisher.html

**Comment by brotkrueml** [comment]
The fragment option (section) is already documented:
https://docs.typo3.org/c/typo3/cms-form/main/en-us/D/FinisherOptions/Index.html#fragment
