### ISSUE TITLE
[!!!][TASK] Require doctrine/dbal 4.x

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#811]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/8af1c49dc1e4f43e1c255de07f83682e205e917a)
:busts_in_silhouette: Authored by Stefan Bürk stefan@buerk.tech
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[!!!][TASK] Require doctrine/dbal 4.x

TYPO3 v13 requires Doctrine DBAL 4 and will be subsequently updated.

Doctrine DBAL 4 is shipping with a few breaking changes, where
most breaking stuff is coped and handled by the TYPO3 core and placed
in internal API implementation and wrappings. However, minor breaking
things on extended and provided API's are included and requires proper
adoption by extensions.

* [1] `AbstractPlatform::getName()` has been removed and `instance of`
  checks are required to be used instead. TYPO3 adopted this removal
  in the extended platform classes and does not provide a b/c for it.

* [2] Doctrine DBAL dropped support for older RDBMS version, aligned
  the Platform class extend chain and removed not-supported version
  for PostgreSQL and MariaDB. TYPO3 extended platform implementation
  are aligned and platform replacement in the replacement driver
  middleware modified.

* [3] Doctrine DBAL switched the casing (renaming) of some
  of the Platform classes, where the new casing has already been
  used for the extended classes. Due to the fact that aliased
  `use` import statement has been used, adjusting these casing
  is minimized to these places.

* [4] `Connection::lastInsertId()` no longer accepts a sequence
  name. TYPO3 core `Connection::getLastInsertId()` implementation
  is aligned to match this and core usages has been replaced with
  a pre-patch except one oversight which is done now.

* [5] Doctrine DBAL introducing replacement methods for the removed
  methods `QueryBuilder::resetQueryParam()` and `resetQueryParams()`,
  which are replaced at required places. Methods are removed on TYPO3
  QueryBuilder to be aligned with Doctrine DBAL.

* [6] Doctrine DBAL made QueryBuilder's state internal and therefore
  removed the QueryBuilder methods `getQueryParts()`, `getQueryPart()`,
  `getType()` and `getState()` along with the public class constants.
  Methods are removed from the TYPO3 QueryBuilder to align here with
  Doctrine DBAL. TYPO3 requires access to this internal state, mainly
  for the Extbase ORM handling and the ContentObjectRenderer. This is
  solved by introducing a internal `ConcreteQueryBuilder` ensuring a
  state duplication and adding internal marked public getter to the
  outer TYPO3 QueryBuilder.

* [7] Doctrine DBAL removed schema compare APIs not taking the
  DB connection into account and suggest to use connection aware
  comparator instead. `TYPO3\CMS\Install\Database\PermissionsCheck`
  is modified to respect this change.

* [8] Doctrine DBAL removed table renaming by using the `TableDiff`
  object and not creating corresponding DDL statements anymore. To
  compensate for this, the already extended `TableDiff` object get
  the `new name` information reintroduced, and the renaming SQL DDL
  is directly created at the required place in `ConnectionMigrator`.

* [9] Deprecated `SchemaDiff::toSql()` and `toSaveSql()` are replaced
  with `AbstractPlatform::getAlterSchemaSQL()`.

* [10] TYPO3 SchemaMigrator, ConnectionMigrator and Comparator are
  modified to cope with some modifications in Doctrine DBAL 4.
  This leads to the requirement that additional normalisation from the
  MySQL variant (ext_tables.sql) towards the target platform. SQLite
  autoincrement normalization is moved from SchemaMigrator into the
  connection migrator and additional MySQL/MariaDB, generic identifier
  and PostgreSQL normalization is added to cope with this fact.

* [11] Due to dropped PostgreSQL 9.6 support Doctrine DBAL switched
  from `SERIAL` to `GENERATED IDENTITY COLUMN` as virtual autoincrement
  handling still using sequence tables under the hood. The implemented
  schema change created by Doctrine DBAL will not migrate the sequence
  relation correctly and leads to really bad issues. The suggested and
  documented way is to create and use a procedure to migrate this. This
  is not suitable for the TYPO3 way of doing the database changes, and
  the `ConnectionMigrator` is modified to create the update statements
  taken from the procedure and replacing the normal alter statements.
  Due to the lack of a good entry point to combine data migration with
  required DDL changes, this has been implemented as a hackish merged
  statement for the meanwhile.

* \TYPO3\CMS\Core\Database\Platform\PlatformSaveAlterSchemaSQLTrait is
  removed as "not used anymore" and already mitigated.

The required work on the database analyser involved classes revealed
badly, that a complete overhaul and restructuring of the code in this
area is mandatory but exceeds the scope if this change. Multiple todo
comments have been added to make this clear and will be done later. This
is possible because the code in this area is considerable internal versus
the need to make the breaking change until the dot-zero sprint release.

Used command(s):

> \
  composer req --no-update --no-install \
    -d typo3/sysext/redirects \
    "doctrine/dbal":"4.0.x-dev@dev" ; \
  composer req --no-update --no-install \
    -d typo3/sysext/core \
    "doctrine/dbal":"4.0.x-dev@dev" ; \
  composer req --no-update --no-install \
    -d typo3/sysext/install \
    "doctrine/dbal":"4.0.x-dev@dev" ; \
  composer req -W \
    "doctrine/dbal":"4.0.x-dev@dev" ; \
  COMPOSER=composer.dist.json composer req --no-update \
    -d Build/composer \
    "doctrine/dbal":"4.0.x-dev@dev"

>  Build/Scripts/runTests.sh -s phpstanGenerateBaseline

[1]  https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-doctrinedbaldrivergetname-removed
     https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-removed-support-for-postgresql-93-and-older
[2]  https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-removed-support-for-mariadb-100-and-older
     https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-removed-support-for-mysql-56-and-older
[3]  https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-renamed-sqlite-platform-classes
[4]  https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#removed-support-for-connectionlastinsertidname
[5]  https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#deprecated-reset-methods-from-querybuilder
[6]  https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#deprecated-getting-query-parts-from-querybuilder
     https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#deprecated-querybuilder-methods-and-constants
[7]  https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-removed-schema-comparison-apis-that-dont-account-for-the-current-database-connection-and-the-database-platform
[8]  https://github.com/doctrine/dbal/blob/3.7.x/UPGRADE.md#deprecated-renaming-tables-via-tablediff-and-abstractplatformaltertable
[9]  https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#deprecated-schemadifftosql-and-schemadifftosavesql
[10] https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-changes-in-handling-string-and-binary-columns
[11] https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md#bc-break-auto-increment-columns-on-postgresql-are-implemented-as-identity-not-serial
     https://github.com/doctrine/dbal/blob/4.0.x/docs/en/how-to/postgresql-identity-migration.rst

Resolves: #102875
Related: #102589
Related: #102402
Releases: main
Change-Id: I547928b5ebba55e574d3a992e864784d8f594653
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77709
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Breaking-102875-ChangedConnectionMethodSignaturesAndBehaviour.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-102875-1705944556:

======================================================================
Breaking: #102875 - Changed Connection method signatures and behaviour
======================================================================

See :issue:`102875`

Description
===========

Signature and behaviour of following methods has been changed:

*   :php:`lastInsertId()` no longer accepts the sequence and field name.
*   :php:`quote()` no longer has a type argument and the value must be a string.

Public :php:`Connection::PARAM_*` class constants has been replaced with the
Doctrine DBAL 4 ParameterType and ArrayParameterType enum definitions.

..  note::
    Doctrine DBAL dropped the support for using the `\PDO::PARAM_*` constants in
    favour of the enum types on several methods. Be aware of this and use the
    `Connection::PARAM_*` constants to reduce required work on upgrading.

Impact
======

Calling :php:`quote()` with a non-string as first argument will result in a
PHP error. Still providing the second argument will not emit an error, but
may be detected by static code analysers.

Calling :php:`lastInsertId()` not directly after the record insert or inserting
records in another table in between will return the incorrect value.

Affected installations
======================

Only installations calling :php:`quote()` with a non-string as first argument
or not using :php:`lastInsertId()` directly after the record insert.

Migration
=========

:php:`lastInsertId()`
---------------------

Returns the last inserted id (auto-created) on the connection. If a record is
inserted and the identity value given, for example when

..  note::
    That means, that the `last inserted id` needs to be retrieved directly before
    inserting a record to another table. That should be the usual workflow used
    in the wild - but be aware of this.

**BEFORE**

..  code-block:: php

    use TYPO3\CMS\Core\Database\Connection as Typo3Connection;
    use TYPO3\CMS\Core\Database\ConnectionPool;
    use TYPO3\CMS\Core\Utility\GeneralUtility;

    /** @var Typo3Connection $connection */
    $connection = GeneralUtility::makeInstance(ConnectionPool::class)
        ->getConnectionForTable('tx_myextension_mytable');

    $connection->insert(
        'tx_myextension_mytable',
        [
            'pid' => $pid,
            'some_string' => $someString,
        ],
        [
            Connection::PARAM_INT,
            Connection::PARAM_STR,
        ]
    );
    $uid = $connection->lastInsertId('tx_myextension_mytable');

**AFTER**

..  code-block:: php

    use TYPO3\CMS\Core\Database\Connection as Typo3Connection;
    use TYPO3\CMS\Core\Database\ConnectionPool;
    use TYPO3\CMS\Core\Utility\GeneralUtility;

    /** @var Typo3Connection $connection */
    $connection = GeneralUtility::makeInstance(ConnectionPool::class)
        ->getConnectionForTable('tx_myextension_mytable');

    $connection->insert(
        'tx_myextension_mytable',
        [
            'pid' => $pid,
            'some_string' => $someString,
        ],
        [
            Connection::PARAM_INT,
            Connection::PARAM_STR,
        ]
    );
    $uid = $connection->lastInsertId();


.. index:: Database, PHP-API, NotScanned, ext:core

```

</details>

<details>
<summary>13.0/Breaking-102875-ExpressionBuilderChanges.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-102875-1706013339:

=============================================
Breaking: #102875 - ExpressionBuilder changes
=============================================

See :issue:`102875`

Description
===========

Signature changes:

*   :php:`ExpressionBuilder::literal(string $value)`: Value must be a string now.

Impact
======

Calling any of the mentioned methods with invalid type will result in a PHP
error.

Affected installations
======================

Only those installations that use the mentioned method with wrong type.

Migration
=========

Extension author need to ensure that a string is passed to :php:`literal()`.

.. index:: Database, PHP-API, NotScanned, ext:core

```

</details>

<details>
<summary>13.0/Breaking-102875-QueryBuilderChanges.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-102875-1705944493:

========================================
Breaking: #102875 - QueryBuilder changes
========================================

See :issue:`102875`

Description
===========

Doctrine DBAL 4 removed methods from the :php:`QueryBuilder` which has been
adopted to extended the :php:`\TYPO3\CMS\Core\Database\Query\QueryBuilder`.

Removed methods:

*   :php:`QueryBuilder::add()`: Use new reset methods and normal set methods
    instead.
*   :php:`QueryBuilder::getQueryPart($partName)`: No replacement, internal state.
*   :php:`QueryBuilder::getQueryParts()`: No replacement, internal state.
*   :php:`QueryBuilder::resetQueryPart($partName)`: Replacement methods has been added,
    see list.
*   :php:`QueryBuilder::resetQueryParts()`: Replacement methods has been added,
    see list.
*   :php:`QueryBuilder::execute()`: Use :php:`QueryBuilder::executeQuery()` or
    :php:`QueryBuilder::executeStatement()` directly.
*   :php:`QueryBuilder::setMaxResults()`: Using `(int)0` as `max result` will
    no longer work and retrieve no records. Use `NULL` instead to allow all
    results.

Signature changes:

*   :php:`QueryBuilder::quote(string $value)`: Second argument has been dropped
    and the value must now be of type :php:`string`.

Impact
======

Calling any of the mentioned removed methods will result in a PHP error. Also
signature changes introducing type hint will result in a PHP error if called
with an invalid type.

Affected installations
======================

Only those installations that use the mentioned methods.

Migration
=========

Extension author need to replace the removed methods with the alternatives which


:php:`QueryBuilder::add('query-part-name')`
-------------------------------------------

Use the direct set/select methods instead:

..  csv-table:: Replacements
    :header: "before", "after"

    "->add('select', $array)", "->select(...$array)"
    "->add('where', $wheres)", "->where(...$wheres)"
    "->add('having', $havings)', "->having(...$havings)"
    "->add('orderBy', $orderBy)", "->orderBy($orderByField, $orderByDirection)->addOrderBy($orderByField2)"
    "->add('groupBy', $groupBy)", "->groupBy($groupField)->addGroupBy($groupField2)"

..  note::
    This can be done already in TYPO3 v12 with at least Doctrine DBAL 3.8.

:php:`QueryBuilder::resetQueryParts()` and :php:`QueryBuilder::resetQueryPart()`
--------------------------------------------------------------------------------

However, several replacements have been put in place depending on the
:php:`$queryPartName` parameter:

..  csv-table:: Replacements
    :header: "before", "after"

    "'select'", "Call `->select()` with a new set of Columns"
    "'distinct'", "->distinct(false)"
    "'where'", "->resetWhere()"
    "'having'", "->resetHaving()"
    "'groupBy'", "->resetGroupBy()"
    "'orderBy", "->resetOrderBy()"
    "'values'", "Call `->values()` with a new set of values."

..  note::
    This can be done already in TYPO3 v12 with at least Doctrine DBAL 3.8.

:php:`QueryBuilder::execute()`
------------------------------

Doctrine DBAL 4 removed :php:`QueryBuilder::execute()` in favour of of the two
methods :php:`QueryBuilder::executeQuery()` for select/count and :php:`QueryBuilder::executeStatement()`
for insert, delete and update queries.

**BEFORE**

..  code-block:: php

    use TYPO3\CMS\Core\Database\ConnectionPool;

    // select query
    $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
      ->getQueryBuilderForTable('pages');
    $rows = $queryBuilder
        ->select('*')
        ->from('pages')
        ->execute()
        ->fetchAllAssociative();

    // delete query
    $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
      ->getQueryBuilderForTable('pages');
    $deletedRows = (int)$queryBuilder
        ->delete('pages')
        ->where(
          $queryBuilder->expr()->eq('pid', $this->createNamedParameter(123),
        )
        ->execute();

**AFTER**

..  code-block:: php
    // select query
    $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
      ->getQueryBuilderForTable('pages');
    $rows = $queryBuilder
        ->select('*')
        ->from('pages')
        ->executeQuery()
        ->fetchAllAssociative();

    // delete query
    $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
      ->getQueryBuilderForTable('pages');
    $deletedRows = (int)$queryBuilder
        ->delete('pages')
        ->where(
          $queryBuilder->expr()->eq('pid', $this->createNamedParameter(123),
        )
        ->executeStatement();

:php:`QueryBuilder::quote(string $value)`
-----------------------------------------

:php:`quote()` uses :php:`Connection::quote()` and therefore adopts the changed
signature and behaviour.

**BEFORE**

..  code-block:: php

    use TYPO3\CMS\Core\Database\Connection as Typo3Connection;
    use TYPO3\CMS\Core\Database\ConnectionPool;
    use TYPO3\CMS\Core\Utility\GeneralUtility;

    // select query
    $pageId = 123;
    $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
      ->getQueryBuilderForTable('pages');
    $rows = $queryBuilder
        ->select('*')
        ->from('pages')
        ->where(
            $queryBuilder->expr()->eq(
                'uid',
                $queryBuilder->quote($pageId, Typo3Connection::PARAM_INT)
            ),
        )
        ->execute()
        ->fetchAllAssociative();

**AFTER**

..  code-block:: php

    use TYPO3\CMS\Core\Database\ConnectionPool;
    use TYPO3\CMS\Core\Utility\GeneralUtility;

    // select query
    $pageId = 123;
    $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
      ->getQueryBuilderForTable('pages');
    $rows = $queryBuilder
        ->select('*')
        ->from('pages')
        ->where(
            $queryBuilder->expr()->eq(
                'uid',
                $queryBuilder->quote((string)$pageId)
            ),
        )
        ->execute()
        ->fetchAllAssociative();

..  tip::
    To provide TYPO3 v12 and v13 with one code base, :php:`->quote((string)$value)`
    can be used to ensure dual core compatibility.

:php:`QueryBuilder::setMaxResults()`
------------------------------------

Using `(int)0` as `max result` will no longer work and retrieve no records.
Use `NULL` instead to allow all results.

**BEFORE**

..  code-block:: php

    use TYPO3\CMS\Core\Database\ConnectionPool;
    use TYPO3\CMS\Core\Utility\GeneralUtility;

    // select query
    $pageId = 123;
    $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
      ->getQueryBuilderForTable('pages');
    $rows = $queryBuilder
        ->select('*')
        ->from('pages')
        ->setFirstResult(0)
        ->setMaxResults(0)
        ->execute()
        ->fetchAllAssociative();

**AFTER**

..  code-block:: php

    use TYPO3\CMS\Core\Database\ConnectionPool;
    use TYPO3\CMS\Core\Utility\GeneralUtility;

    // select query
    $pageId = 123;
    $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
      ->getQueryBuilderForTable('pages');
    $rows = $queryBuilder
        ->select('*')
        ->from('pages')
        ->setFirstResult(0)
        ->setMaxResults(null)
        ->execute()
        ->fetchAllAssociative();


.. index:: Database, PHP-API, NotScanned, ext:core

```

</details>

<details>
<summary>13.0/Important-102875-UpdatedDependencyDoctrineDBAL4.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-102875-1705915392:

========================================================
Important: #102875 - Updated Dependency: Doctrine DBAL 4
========================================================

See :issue:`102875`

Description
===========

TYPO3 v13 ships with Doctrine DBAL with at least version 4.0.

TYPO3 extends some Doctrine DBAL classes, enriching behaviour and provide
these as public API surface, for example :php:`Connection`, :php:`QueryBuilder`
and the :php:`ExpressionBuilder` and are most likely used by extensions. Minor
signature changes and removed methods are not mitigated and passed as breaking
changes.

Custom extensions using low-level Doctrine DBAL API and functionality
directly need to adapt, see upgrade guides for Doctrine DBAL 4 on how
to migrate.

..  note::
    Doctrine DBAL 4.0 will be released slightly after the 13.0 and
    therefore it's raised to a development version for now. This will
    be changed to 4.0 after a release is out. As a intermediate solution
    it's required to use `composer require "doctrine/dbal":"4.0.x-dev@dev"`
    to add it or lower the minimum-stability in the root `composer.json`.

See `Doctrine DBAL 4.x Upgrade Guide <https://github.com/doctrine/dbal/blob/4.0.x/UPGRADE.md>`_
and `Doctrine DBAL 4.x Upgrade Guide <https://github.com/doctrine/dbal/blob/3.8.x/UPGRADE.md>`_
for further information about Doctrine DBAL API changes and how to mitigate them.

.. index:: Database, PHP-API, ext:core

```

</details>

**Comment by brotkrueml** [comment]
- <del>[ ] `quote()`</del>
- [x] `lastInsertId()`
- [x] PDO constants
- <del>[ ] ExpressionBuilder</del>
- [ ] QueryBuilder
