### ISSUE TITLE
[FEATURE] Show the redirect integrity status

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#816]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/422d4777cdc1a55f0ded75c28283de28dbc56eae)
:busts_in_silhouette: Authored by Guido Schmechel guido.schmechel@brandung.de
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] Show the redirect integrity status

The `ext:redirects` provides a integrity check
command to detect integrity issues of existing
redirects.

This change persists the integrity state to the
redirect records and extends the backend module
to make the integrity state of redirects visible
by colorizing them in the list. Additionally, a
new filter option for the integrity state is now
available.

Resolves: #99485
Releases: main
Change-Id: I03db4472f3e37594e33ab92a617a3787014e157a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/77285
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Feature-99485-ShowTheRedirectIntegrityStatus.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99485-1673115922:

====================================================
Feature: #99485 - Show the redirect integrity status
====================================================

See :issue:`99485`

Description
===========

The integrity check command checks redirects and displays the information in the
CLI or in the status report. This status information is now used and stored on
the redirect.

The command `redirects:cleanup` has been extended by the option "integrityStatus".
This allows you to remove specific redirects according to status.

The event :php:`TYPO3\CMS\Redirects\Event\ModifyRedirectManagementControllerViewDataEvent`
has been extended by two new functions:

-   :php:`setIntegrityStatusCodes()`: Allows to set integrityStatusCodes. Can be
    used to filter for integrityStatusCodes
-   :php:`getIntegrityStatusCodes()`: Returns all integrityStatusCodes.

Impact
======

In the redirect module, the conflicting redirects are now marked. In addition,
you can now filter for conflicting redirects.

In the `redirects:checkintegrity` command, the type of conflict is now displayed
in the table.

.. index:: Backend, ext:redirects

```

</details>

**Comment by brotkrueml** [comment]
EXT:redirects: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83633
