### ISSUE TITLE
Feature: #90919 - Skip translation of overridden form finisher options

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#82]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Feature-90919-SkipTranslationOfOverriddenFormFinisherOptions.html

**Comment by sypets** [comment]
Releated to EXT:form. Created forge issue: https://forge.typo3.org/issues/97905
