### ISSUE TITLE
[!!!][TASK] Switch the extbase domain models to strict mode

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#832]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/7fb2098437a7c54f0821fa55b3aa05efa7cdd657)
:busts_in_silhouette: Authored by Oliver Klee typo3-coding@oliverklee.de
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[!!!][TASK] Switch the extbase domain models to strict mode

Resolves: #102969
Related: #102879
Releases: main
Change-Id: I1da732b04b2522907f969b850924d3d04b3fae4f
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82688
Tested-by: Guido Schmechel <guido.schmechel@brandung.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Guido Schmechel <guido.schmechel@brandung.de>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Breaking-102632-UseStrictTypesInExtbase.rst</summary>

```diff
@@ -9,6 +9,7 @@ Breaking: #102632 - Use strict types in extbase
 See :issue:`102632`
 See :issue:`102879`
 See :issue:`102885`
+See :issue:`102969`
 
 Description
 ===========
@@ -29,8 +30,8 @@ In summary, the following classes have received strict types:
 - :php:`TYPO3\CMS\Extbase\TYPO3\CMS\Extbase\Annotation\Required\Validate`
 - :php:`TYPO3\CMS\Extbase\TYPO3\CMS\Extbase\Domain\Model\AbstractFileFolder`
 - :php:`TYPO3\CMS\Extbase\TYPO3\CMS\Extbase\Domain\Model\Category`
-- :php:`TYPO3\CMS\Extbase\TYPO3\CMS\Extbase\Domain\Model\File`
 - :php:`TYPO3\CMS\Extbase\TYPO3\CMS\Extbase\Domain\Model\FileReference`
+- :php:`TYPO3\CMS\Extbase\TYPO3\CMS\Extbase\Domain\Model\File`
 
 
 Impact
```

</details>

**Comment by linawolf** [comment]
No need to document
