### ISSUE TITLE
[!!!][TASK] Use full md5 hash for `indexed_search`

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#842]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/3ad5b4535b6d49758acc004e3202309e5479f642)
:busts_in_silhouette: Authored by Stefan Bürk stefan@buerk.tech
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[!!!][TASK] Use full md5 hash for `indexed_search`

For `ext:indexed_search` not only a cumbersome md5 to int
conversion has been used. The original md5 length has been
reduced by simply cutting off values from the end, combined
with a `hexdec` conversion, leading to a highly increased
conflict probability (duplicate keys) for several places.

To mitigate this, the raw md5 hash should be used instead
of the reduced integer representation.

This change modifies the database and the user land code
to use the full `md5()` hash without castrating them any
longer.

The following table fields are therefore changed from `int`
to `varchar`:

* index_phash: phash, phash_grouping, contentHash
* index_fulltext: phash
* index_rel: phash, wid
* index_words: wid
* index_section: phash, phash_t3
* index_grlist: phash, phash_x, hash_gr_list
* index_debug: phash

Note: The required table truncation is handled within
the database analyzer schema changes and not as an upgrade
wizard.

Recently added native php types are now changed to string
to cope with this change again. Also removed the now unused
internal `IndexedSearchUtility::md5inthash()` method.

Using `QueryBuilder::quoteArrayBasedValueListToStringList()`
instead of named placeholders for `IN()` conditions to reduce
the risk for exceeded placeholder limit. QuerySize limitation
may still occur, but can be increased by the responsible server
administrator.

Resolves: #102975
Resolves: #84541
Resolves: #90977
Resolves: #79802
Resolves: #87138
Releases: main
Change-Id: I8e1dcffccb351dc03b58f0d5bc5d4c8419bc307a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/74688
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>13.0/Breaking-102975-UseFullMd5HashesInIndexed_search.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _breaking-102975-1706525161:

===========================================================
Breaking: #102975 - Use full md5 hashes in `indexed_search`
===========================================================

See :issue:`102975`

Description
===========

For historical reasons an integer representation for castrated md5 hashes has
been used in several places for the `ext:indexed_search` provided database schema
and functionality. This led to conflicts that manifested as `duplicate key` errors.

Therefore, the database fields are transformed to varchar fields and the whole
indexed search codebase changed to work with full md5 hashes now.

Due to the database changes it is necessary to truncate the indexed search tables,
which is done within the database analyzer. Reindexing the data is therefore
required.

Field types of following table fields are changed now:

* `index_phash`: `phash`, `phash_grouping`, `contentHash`
* `index_fulltext`: `phash`
* `index_rel`: `phash`, `wid`
* `index_words`: `wid`
* `index_section`: `phash`, `phash_t3`
* `index_grlist`: `phash`, `phash_x`, `hash_gr_list`
* `index_debug`: `phash`

..  note::

    Remember to reindex your installation to fill the index again.

Impact
======

Installations using the `ext:indexed_search` need to apply a database schema
change which involves the truncation of the corresponding tables and reindex
the installation.

Affected installations
======================

All installations using `EXT:indexed_search` are affected.


Migration
=========

The database analyzer takes care of updating affected columns and truncates
index related tables to be ready for re-indexing.


.. index:: Database, NotScanned, ext:indexed_search

```

</details>

**Comment by brotkrueml** [comment]
https://review.typo3.org/c/Packages/TYPO3.CMS/+/83268
