### ISSUE TITLE
[BUGFIX] Avoid autocompletion in TCA type password

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#851]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/fd81d1bf1f926fea51cbdf0b50fc0149c8e5b25d)
:busts_in_silhouette: Authored by Benjamin Franzke ben@bnf.dev
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[BUGFIX] Avoid autocompletion in TCA type password

The autocomplete="off" parameter is ignored by current browsers,
autocomplete="new-password" is to be used for disable autocompletion.

The explicit request for autocompleting the password is
autocomplete="current-password", which is now used in case config TCA
autocomplete is set.

See following article for more information:
 * https://web.dev/articles/sign-in-form-best-practices#new-password
 * https://web.dev/articles/sign-in-form-best-practices#current-password

Resolves: #103067
Related: #97104
Releases: main, 12.4
Change-Id: Ice3c7a50020d7e17b14c51dc89c1c8e1700fe9a6
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/82830
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Tested-by: Benjamin Franzke <ben@bnf.dev>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Feature-97104-NewTCATypePassword.rst</summary>

```diff
@@ -21,9 +21,9 @@ TCA type :php:`password` has been added. It replaces the :php:`eval=password`
 and :php:`eval=saltedPassword` option of TCA type :php:`input`.
 
 TCA password fields will be rendered as input :php:`type=password` fields.
-By default, the :php:`autocomplete=off` attribute will be added to the
+By default, the :php:`autocomplete=new-password` attribute will be added to the
 resulting input field. If :php:`autocomplete=true` is configured in TCA, a
-:php:`autocomplete=new-fieldname` attribute will be added to the element.
+:php:`autocomplete=current-password` attribute will be added to the element.
 
 The TCA type :php:`password` features the following column configuration:
 
```

</details>

**Comment by brotkrueml** [comment]
https://docs.typo3.org/m/typo3/reference-tca/12.4/en-us/ColumnsConfig/Type/Password/Properties/Autocomplete.html

**Comment by Christobal79** [comment]
On it.

**Comment by linawolf** [comment]
@Christobal79 are you still working on this?
