### ISSUE TITLE
[BUGFIX] Add font plugin to CKEditor5

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#858]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f2c278686847919a3dd7c57cf0357c77303888a2)
:busts_in_silhouette: Authored by Johannes Nielsen johannes.nielsen@artundweise.de
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[BUGFIX] Add font plugin to CKEditor5

Add the configuration to the "Full" RTE preset, and also
include some modules that missed in Full preset since #102099.

npm install --save @ckeditor/ckeditor5-font@41.1.0
npm run build

Resolves: #100847
Releases: main, 12.4
Change-Id: Iaa56d48e043397aefb902b6c9a5afbfcc453ae74
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/79006
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Torben Hansen <derhansen@gmail.com>
Tested-by: David Bruchmann <david.bruchmann@gmail.com>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Guido Schmechel <guido.schmechel@brandung.de>
Reviewed-by: David Bruchmann <david.bruchmann@gmail.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: Torben Hansen <derhansen@gmail.com>
Reviewed-by: Guido Schmechel <guido.schmechel@brandung.de>

## :heavy_plus_sign: Added files

<details>
<summary>12.4.x/Important-100847-AddedFontPluginToCKEditor5.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-100847-1686218342:

===================================================
Important: #100847 - Added font plugin to CKEditor5
===================================================

See :issue:`100847`

Description
===========

The font plugin has been added to the CKEditor5.
In order to use the font plugin, the RTE configuration needs to be adapted:

.. code-block:: yaml

    editor:
      config:
        toolbar:
          items:
            # add button to select font family
            - fontFamily
            # add button to select font size
            - fontSize
            # add button to select font color
            - fontColor
            # add button to select font background color
            - fontBackgroundColor

        fontColor:
          colors:
            - { label: 'Orange', color: '#ff8700' }
            - { label: 'Blue', color: '#0080c9' }
            - { label: 'Green', color: '#209d44' }

        fontBackgroundColor:
          colors:
            - { label: 'Stage orange light', color: '#fab85c' }

        fontFamily:
          options:
            - 'default'
            - 'Arial, sans-serif'

        fontSize:
          options:
            - 'default'
            - 18
            - 21

        importModules:
          - { 'module': '@ckeditor/ckeditor5-font', 'exports': ['Font'] }


More information can be found in the official documentation_.


.. _documentation: https://ckeditor.com/docs/ckeditor5/latest/features/font.html

.. index:: RTE, ext:rte_ckeditor

```

</details>

**Comment by brotkrueml** [comment]
https://review.typo3.org/c/Packages/TYPO3.CMS/+/83267
