### ISSUE TITLE
[DOCS] Update CKEditor5 CSS styling limitations section

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#859]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/5aceacdf31ed7829e46204e999c9d4e0aee0b09b)
:busts_in_silhouette: Authored by Benjamin Franzke ben@bnf.dev
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[DOCS] Update CKEditor5 CSS styling limitations section

With #100768 the CKEeditor5 CSS scoping was migrated from server-side
SCSS preprocessing to a JavaScript based CSS prefixer. The Feature.rst
has not been updated and still referred to limitations caused by the
removed SCSS parser.

Resolves: #103151
Related: #100768
Releases: main, 12.4
Change-Id: I0f9e7d0c8c88c906b65290c29f2b2cc0e179058a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83035
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Markus Klein <markus.klein@typo3.org>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: Andreas Kienast <a.fernandez@scripting-base.de>
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>
Tested-by: Markus Klein <markus.klein@typo3.org>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Feature-96874-CKEditor5.rst</summary>

```diff
@@ -42,10 +42,11 @@ CSS Styling
 
 CKEditor 5 does not load its editor in a specific iframe anymore. Especially
 for adding custom styling and fonts, all CSS declarations now need to be prefixed
-with ".ck-content". This can be achieved via SCSS, which TYPO3 natively
-handles for custom CSS styles.
-However, <body> tag CSS declarations won't work, as the `<body>` tag does not
-apply to the editor HTML rendering anymore.
+with ".ck-content". This scoping is applied by TYPO3 automatically to all custom
+CSS styles.
+
+Please be aware that referenced CSS stylesheets need to be downloadable via
+:js:`fetch()` in order for the JavaScript based prefixing to work.
 
 Configuration Options
 ---------------------
```

</details>

**Comment by brotkrueml** [comment]
https://review.typo3.org/c/Packages/TYPO3.CMS/+/83265
