### ISSUE TITLE
[FEATURE] Introduce tree node status information

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#861]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/9cd9d05e4b44071fe3da4717c8725fe5da20cc10)
:busts_in_silhouette: Authored by Benjamin Kott benjamin.kott@outlook.com
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[FEATURE] Introduce tree node status information

We've enhanced the backend tree component by extending tree nodes to
incorporate status information. These details serve to indicate the
status of nodes and provide supplementary information.

For instance, if a page undergoes changes within a workspace, it will
now display an indicator on the respective tree node. Additionally,
the status is appended to the node's title. This enhancement not only
improves visual clarity but also enhances information accessibility.

Each node can accommodate multiple status information, prioritized by
severity and urgency. Critical messages take precedence over other
status notifications.

Resolves: #103186
Releases: main
Change-Id: Ia117c78f2bfde2fd8a2d0af35b3a2de021e866cb
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83086
Tested-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: Andreas Kienast <a.fernandez@scripting-base.de>
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.1/Feature-103186-IntroduceTreeNodeStatusInformation.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-103186-1708686767:

=========================================================
Feature: #103186 - Introduce tree node status information
=========================================================

See :issue:`103186`

Description
===========

We've enhanced the backend tree component by extending tree nodes to
incorporate status information. These details serve to indicate the
status of nodes and provide supplementary information.

For instance, if a page undergoes changes within a workspace, it will
now display an indicator on the respective tree node. Additionally,
the status is appended to the node's title. This enhancement not only
improves visual clarity but also enhances information accessibility.

Each node can accommodate multiple status information, prioritized by
severity and urgency. Critical messages take precedence over other
status notifications.

.. code-block:: php

    new TreeItem(
        ...
        statusInformation: [
            new StatusInformation(
                label: 'A warning message',
                severity: ContextualFeedbackSeverity::WARNING,
                priority: 0,
                icon: 'actions-dot',
                overlayIcon: ''
            )
        ]
    ),

Impact
======

Tree nodes can now have status information. Workspace changes are
now reflected in the title of the node in addition to the indicator.

.. index:: Backend, JavaScript, ext:backend

```

</details>

**Comment by brotkrueml** [comment]
https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Events/Events/Backend/AfterPageTreeItemsPreparedEvent.html
