### ISSUE TITLE
[DOCS] Make the reason why noopener was removed more visible

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#867]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/85d67068dc07da4dbccfaa798a428c76ff720788)
:busts_in_silhouette: Authored by Lina Wolf noreply@example.com
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[DOCS] Make the reason why noopener was removed more visible

Releases: main, 12.4
Resolves: #103262
Change-Id: I30f4c1c7fd0f27b1712bbead42ceea6bf5f5e0f5
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83190
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_division_sign: Modified files

<details>
<summary>10.1/Feature-78488-AddRelNoreferrerToExternalLinks.rst</summary>

```diff
@@ -17,6 +17,11 @@ All links processed by :typoscript:`typolink` with external links opening in a n
 Links opening in a new window are defined as those having an attribute :html:`target` which is either not empty,
 :html:`_self`, :html:`_top` or :html:`_parent`.
 
+..  note::
+
+    Initially this feature added :html:`rel="noopener noreferrer`. However :html:`noreferrer` also
+    implies the property :html:`noopener`. Therfore the later was removed.
+
 
 Impact
 ======
```

</details>

**Comment by brotkrueml** [comment]
https://docs.typo3.org/m/typo3/reference-typoscript/main/en-us/Functions/Typolink.html#parameter
