### ISSUE TITLE
[FEATURE] Allow creating backend user group presets

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#877]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/bcea6ec014f57a262c49f13387910d74d1ce0b83)
:busts_in_silhouette: Authored by Marcin Sągol marcin@soee.pl
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[FEATURE] Allow creating backend user group presets

When installing TYPO3, the final step (5) has
been updated to include an additional checkbox.
This checkbox will allow the user to decide if
they want to have 2 default backend groups,
Editor and Advanced Editor, installed.

These groups will be created with predefined
permission presets defined through YAML files
in `EXT:install/Configuration/PermissionPreset/`:

- be_groups_editor.yaml
- be_groups_advanced_editor.yaml

In these files, access is defined to to modules,
dashboard widgets, table listings and editing,
allowed exclude fields, etc.

A new dedicated CLI command is also introduced
to create these groups later if they were skipped
during the TYPO3 installation process.

The command can be executed by calling:

  ./bin/typo3 setup:begroups:default

It supports both interactive and non-interactive
modes and allows the creation of both groups or
only one selected group.

Resolves: #103187
Releases: main
Change-Id: Ifd42e2e59acd6eb5808d6c754b0a2c8f6daa7c28
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83087
Tested-by: core-ci <typo3@b13.com>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>13.1/Feature-103187-AddCliCreateBeUserGroupCommand.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-103187-1708943723:

======================================================================
Feature: #103187 - Introduce CLI command to create backend user groups
======================================================================

See :issue:`103187`

Description
===========

A new CLI command :bash:`./bin/typo3 setup:begroups:default` has been
introduced as an alternative to the existing backend module. This command
automates the creation of backend user groups, enabling the creation of
two pre-configured backend user groups with permission presets applied.

..  note::

    The pre-configured backend user group permissions are subject to be
    further changed and adjusted and defines a first set. Also possible
    that additional groups may be added or made configurable. That means,
    that the :bash:`./bin/typo3 setup:begroups:default` command and the
    pre-defined permissions are considerable `experimental` during the
    TYPO3 v13 development cycle.

Impact
======

You can now use :bash:`./bin/typo3 setup:begroups:default` to create
pre-configured backend user groups without touching the GUI.

Example
-------

Interactive / guided setup (questions/answers):

..  code-block:: bash
    :caption: Basic command

    ./bin/typo3 setup:begroups:default

The backend user group can be set via the :bash:`--groups|-g` option. Allowed
values for groups are :bash:`Both`, :bash:`Editor` and :bash:`Advanced Editor`):

..  code-block:: bash
    :caption: Command examples

    ./bin/typo3 setup:begroups:default --groups Both
    ./bin/typo3 setup:begroups:default --groups Editor
    ./bin/typo3 setup:begroups:default --groups "Advanced Editor"

When using the :bash:`--no-interaction` option, this defaults to :bash:`both`.

..  note::

    At the moment, the command does not support the creation of backend user
    groups with custom names or permissions (they can be modified later through
    the backend module). It is limited to creating two pre-configured backend
    user groups with permission presets applied.

.. index:: Backend, CLI, ext:backend

```

</details>

**Comment by brotkrueml** [comment]
https://docs.typo3.org/m/typo3/tutorial-getting-started/12.4/en-us/Installation/Install.html#initialize
