### ISSUE TITLE
[FEATURE] Introduce CLI command to create backend user groups

### ISSUE THREAD

**Issue by brotkrueml** [TYPO3-Documentation/Changelog-To-Doc#881]
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.1/Feature-103187-AddCliCreateBeUserGroupCommand.html

**Comment by linawolf** [comment]
Duplicate of https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/877
