### ISSUE TITLE
[FEATURE] Add keyboard shortcut in FormEngine for Save & Close

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#887]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/107a432d181e4fb246f0a51cb11d01b142477667)
:busts_in_silhouette: Authored by Andreas Kienast a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Andreas Kienast a.fernandez@scripting-base.de

## Commit message

[FEATURE] Add keyboard shortcut in FormEngine for Save & Close

A new hotkey is introduced in the FormEngine scope that lets editors
invoke "Save and Close" via `Ctrl/Cmd+Shift+S`.

Resolves: #103529
Releases: main
Change-Id: I530a1df54707eb69033c8a03ccf58517facf162a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83642
Tested-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Andreas Kienast <a.fernandez@scripting-base.de>
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.1/Feature-103529-IntroduceHotkeyForSaveAndClose.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-103529-1712154338:

========================================================
Feature: #103529 - Introduce hotkey for "Save and Close"
========================================================

See :issue:`103529`

Description
===========

A new hotkey is introduced in the FormEngine scope that lets editors invoke
"Save and Close" via :kbd:`Ctrl`/:kbd:`Cmd` + :kbd:`Shift` + :kbd:`S`.


Impact
======

Next to the existing :kbd:`Ctrl`/:kbd:`Cmd` + :kbd:`s` hotkey (Save), the
hotkey :kbd:`Ctrl`/:kbd:`Cmd` + :kbd:`Shift` + :kbd:`S` (Save and Close)
became available.

.. index:: Backend, JavaScript, ext:backend

```

</details>

**Comment by sfinnerWco** [comment]
on it

**Comment by sfinnerWco** [comment]
issue should be solved
