### ISSUE TITLE
[FEATURE] Add Page TSconfig provider for sites and sets

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#891]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/b90a46308b95c40223a8a84abe997874ce5cc28b)
:busts_in_silhouette: Authored by Benjamin Franzke ben@bnf.dev
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[FEATURE] Add Page TSconfig provider for sites and sets

TYPO3 sites have been enhanced to be able to provide Page TSconfig on
a per site basis.

Releases: main
Resolves: #103522
Change-Id: I1558ca9265fcd0fd9bef83cb47ec9c54a7a0d59c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83586
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: Benjamin Kott <benjamin.kott@outlook.com>
Reviewed-by: Benjamin Kott <benjamin.kott@outlook.com>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>

## :heavy_plus_sign: Added files

<details>
<summary>13.1/Feature-103522-PageTSconfigProviderForSitesAndSets.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-103522-1712323334:

============================================================
Feature: #103522 - Page TSconfig provider for Sites and Sets
============================================================

See :issue:`103522`

Description
===========

TYPO3 sites have been enhanced to be able to provide Page TSconfig on a per site
basis.

Site Page TSconfig is loaded from :file:`page.tsconfig` if placed next to
site configuration file :file:`config.yaml` and is scoped to pages within that
site.


Impact
======

Sites and sets can ship Page TSconfig without the need for database entries or
by polluting global scope when registering Page TSconfig globally via
:file:`ext_localconf.php` or :file:`Configuration/page.tsconfig`.
Dependencies can expressed via sets, allowing for automatic ordering and
deduplication.


.. index:: Backend, Frontend, PHP-API, TypoScript, YAML, ext:core

```

</details>

**Comment by linawolf** [comment]
Resolved with https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/506 and https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/505
