### ISSUE TITLE
[TASK] Fix misleading example in #103437 Feature.rst

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#893]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ab5aa2c6a9151eb4e8029ec3fb287a277034753d)
:busts_in_silhouette: Authored by Benjamin Franzke ben@bnf.dev
:heavy_check_mark: Merged by Andreas Kienast a.fernandez@scripting-base.de

## Commit message

[TASK] Fix misleading example in #103437 Feature.rst

The site sets example referenced TYPO3-provided sets
that are not yet available, since the respective implementations
(#103034, #103556) have not be merged yet.

Use generic examples to avoid confusion.

Resolves: #103557
Related: #103437
Releases: main
Change-Id: I008d60167a692ec601b89683bf582233b228ab12
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83697
Tested-by: Benjamin Kott <benjamin.kott@outlook.com>
Reviewed-by: Benjamin Kott <benjamin.kott@outlook.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Andreas Kienast <a.fernandez@scripting-base.de>
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>

## :heavy_division_sign: Modified files

<details>
<summary>13.1/Feature-103437-IntroduceSiteSets.rst</summary>

```diff
@@ -40,9 +40,8 @@ follows:
 
     # Load TypoScript, TSconfig and settings from dependencies
     dependencies:
-      - typo3/fluid-styled-content
-      - typo3/felogin
-      - typo3/seo-xml-sitemap
+      - some-namespace/slider
+      - other-namespace/fancy-carousel
 
 
 Sets are applied to sites via `dependencies` array in site configuration:
@@ -53,7 +52,7 @@ Sets are applied to sites via `dependencies` array in site configuration:
     base: 'http://example.com/'
     rootPageId: 1
     dependencies:
-      - typo3/styleguide
+      - my-vendor/my-set
 
 Site sets can also be edited via the backend module `Site Management > Sites`.
 
```

</details>

**Comment by linawolf** [comment]
Aready documented
