### ISSUE TITLE
[FEATURE] Introduce hotkeys to scheduler task editing

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#895]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/8f0662e9a98feaa9ab300b85b9b96b4a262e3b0e)
:busts_in_silhouette: Authored by Andreas Kienast a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Andreas Kienast a.fernandez@scripting-base.de

## Commit message

[FEATURE] Introduce hotkeys to scheduler task editing

Similar to editing regular content elements, it is now possible to save
scheduler tasks being edited via keyboard shortcuts as well.

Resolves: #103563
Releases: main
Change-Id: Ia159293670f3f3dc762f3c23da35e0e71d5541fd
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83702
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Andreas Kienast <a.fernandez@scripting-base.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.1/Feature-103563-AddSaving-relatedHotkeysToSchedulerBackendModule.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-103563-1712569921:

=========================================================================
Feature: #103563 - Add saving-related hotkeys to scheduler backend module
=========================================================================

See :issue:`103563`

Description
===========

Similar to editing regular content elements, it is now possible to save
scheduler tasks being edited via keyboard shortcuts as well.


Impact
======

It is possible to invoke the :kbd:`Ctrl`/:kbd:`Cmd` + :kbd:`s` hotkey to save a
scheduler task, altogether with the hotkey :kbd:`Ctrl`/:kbd:`Cmd` + :kbd:`Shift` + :kbd:`S`
to save and close a scheduler task.

.. index:: Backend, JavaScript, ext:scheduler

```

</details>

**Comment by linawolf** [comment]
Solved in https://review.typo3.org/c/Packages/TYPO3.CMS/+/85666
