### ISSUE TITLE
Important: #97411 - Align SystemEnvironment checks to changed requirements

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/Changelog-To-Doc#91]
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/12.0/Important-97411-AlignSystemEnvironmentChecksToChangedRequirements.html

**Comment by sypets** [comment]
specific PHP version requirements or Microsoft SQL server is not not listed on [System requirements](https://docs.typo3.org/m/typo3/tutorial-getting-started/main/en-us/SystemRequirements/Index.html) page, user is referred to get.typo3.org, nothing to do here.
