### ISSUE TITLE
[DOCS] Add hint about console command for listing site sets in changelog

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#912]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/8194b5c44e74bce26e8a27960ddb83c610a9df36)
:busts_in_silhouette: Authored by Chris Müller typo3@brotkrueml.dev
:heavy_check_mark: Merged by Benjamin Franzke ben@bnf.dev

## Commit message

[DOCS] Add hint about console command for listing site sets in changelog

With the introduction of site sets also a console command
was made available which lists all available site sets.
Knowing this command makes it easier for integrators to set
the dependencies.

Resolves: #103771
Related: #103437
Releases: main
Change-Id: I86e45c1a63fc3ddc5aaf8a2b1b72da7b24febe08
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84098
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Tested-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>13.1/Feature-103437-IntroduceSiteSets.rst</summary>

```diff
@@ -57,6 +57,8 @@ Sets are applied to sites via `dependencies` array in site configuration:
 Site sets can also be edited via the backend module
 :guilabel:`Site Management > Sites`.
 
+A list of available site sets can be retrieved with the console command
+:bash:`bin/typo3 site:sets:list`.
 
 Settings definitions
 --------------------
```

</details>

**Comment by linawolf** [comment]
Related #889
