### ISSUE TITLE
[TASK] Deprecate `MathUtility::convertToPositiveInteger()`

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#913]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/041497c946cb658ff25d2d42967b5c5b1929a840)
:busts_in_silhouette: Authored by Andreas Kienast a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Andreas Kienast a.fernandez@scripting-base.de

## Commit message

[TASK] Deprecate `MathUtility::convertToPositiveInteger()`

TYPO3 has a method to ensure an integer is always positive:
`MathUtility::convertToPositiveInteger()`. However, the method is
rather "heavy" as it internally calls `MU::forceIntegerInRange()` and
therefore misuses a clamp mechanism to convert the integer to a
positive number.

Also, the method name doesn't reflect what it actually does. Negative
numbers are not converted to their positive counterpart, but are
swapped with `0`. Due to the naming issue and the fact that the method
can be superseded by a simple `max()` call, the method is therefore
deprecated.

Resolves: #103785
Releases: main
Change-Id: I4fd0548ec6bc7289008057ade4e64f9437c2da7b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84141
Tested-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Torben Hansen <derhansen@gmail.com>
Tested-by: Torben Hansen <derhansen@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Oliver Klee <typo3-coding@oliverklee.de>
Reviewed-by: Benjamin Franzke <ben@bnf.dev>
Tested-by: Andreas Kienast <a.fernandez@scripting-base.de>
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.2/Deprecation-103785-DeprecateMathUtilityConvertToPositiveInteger.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-103785-1714720280:

========================================================================
Deprecation: #103785 - Deprecate MathUtility::convertToPositiveInteger()
========================================================================

See :issue:`103785`

Description
===========

TYPO3 has a method to ensure an integer is always positive:
:php:`MathUtility::convertToPositiveInteger()`. However, the method is rather
"heavy" as it internally calls :php:`MathUtility::forceIntegerInRange()` and
therefore misuses a clamp mechanism to convert the integer to a positive number.

Also, the method name doesn't reflect what it actually does. Negative numbers
are not converted to their positive counterpart, but are swapped with `0`. Due
to the naming issue and the fact that the method can be superseded by a simple
:php:`max()` call, the method is therefore deprecated.

Impact
======

Calling :php:`MathUtility::convertToPositiveInteger()` will trigger a PHP
deprecation warning.


Affected installations
======================

All installations using :php:`MathUtility::convertToPositiveInteger()` are
affected.


Migration
=========

To recover the original behavior of the deprecated method, its call can be
replaced with :php:`max(0, $number)`. To actually convert negative numbers to
their positive counterpart, call :php:`abs($number)`.

.. index:: PHP-API, FullyScanned, ext:core

```

</details>

**Comment by linawolf** [comment]
The method was not mentioned anywhere in the docs
