### ISSUE TITLE
[BUGFIX] Respect TCA "check" default for auto-create DB fields

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#923]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f397539ef5b3ce1ffb6a57b2c2a74f081031aeb7)
:busts_in_silhouette: Authored by Garvin Hicking gh@faktor-e.de
:heavy_check_mark: Merged by Georg Ringer georg.ringer@gmail.com

## Commit message

[BUGFIX] Respect TCA "check" default for auto-create DB fields

Change #101653 introduced the auto-creation of DB fields for TCA
type "check", but used a hardcoded "0" as default.

Since TCA definitions might define a different default, and
records may not always be created using the DataHandler to
respect TCA defaults, this can lead to DB entries getting
created with an unexpected default setting.

IMPORTANT: This patch only fixes the root cause of the bug.
If an existing v13 installation has already created new
records after the DB migration wizard update in 13.0, all
records may have wrong defaults. Check the contents of
your database for the fields listed below and apply
manual adjustments as needed (for example, record storages
having "auto_extract_metadata"=1 instead of 0).

An example symptom of this is the auto-creation of a
file storage record, which uses the QueryBuilder to
create a record, without specifying the whole list
of all possible fields. For example then leading to
added YouTube media files not auto-creating metadata
records.

This patch uses the proper evaluation of the TCA
"default" setting of an auto-created field.

In TYPO3 Core this only affected `be_users.options` and
`sys_file_storage.auto_extract_metadata` default record
creation. The latter field has now been included
to the default record creation as a fixed value like
the others. A follow-up patch could rewrite this
functionality using the DataHandler or QueryBuilder
default value injection.

Tests have been created to verify this regression,
existing tests for be_user creation have been
adapted for the proper default values.

Executing the DB schema analyzer will now
adjust the following fields:

* be_users.options                                 (0->3)
* sys_file_storage.is_browsable                    (0->1)
* sys_file_storage.is_writable                     (0->1)
* sys_file_storage.is_online                       (0->1)
* sys_file_storage.auto_extract_metadata           (0->1)
* sys_file_metadata.visible                        (0->1)
* tt_content.sectionIndex                          (0->1)
* tx_styleguide_palette.palette_1_1                (0->1)
* tx_styleguide_palette.palette_1_3                (0->1)
* tx_styleguide_valuesdefault.checkbox_1           (0->1)
* tx_styleguide_valuesdefault.checkbox_2           (0->1)
* tx_styleguide_valuesdefault.checkbox_3           (0->5)
* tx_styleguide_valuesdefault.checkbox_4           (0->5)
* sys_workspace.edit_allow_notificaton_settings    (0->3)
* sys_workspace.edit_notification_preselection     (0->2)
* sys_workspace.publish_allow_notificaton_settings (0->3)
* sys_workspace.publish_notification_preselection  (0->1)
* sys_workspace.execute_allow_notificaton_settings (0->3)
* sys_workspace.execute_notification_preselection  (0->3)
* sys_workspace_stage.allow_notificaton_settings   (0->3)
* sys_workspace_stage.notification_preselection    (0->8)

Resolves: #103915
Related: #101653
Releases: main
Change-Id: Ia42e00b03d1369efe319e41e2b406b5303804854
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84402
Tested-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Anja Leichsenring <aleichsenring@ab-softlab.de>
Reviewed-by: Oliver Wand <wand@itaw.de>
Tested-by: core-ci <typo3@b13.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.2/Important-103915-AutoDBCreationForTCATypeCheck.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-103915-1716666919:

=========================================================================
Important: #103915 - Adjust database field defaults for "check" TCA types
=========================================================================

See :issue:`103915`

Description
===========

TYPO3 v13.0 introduced the automatic database field creation for TCA
fields configured as type "check" (if not explicitly defined in
:file:`ext_tables.sql`), via
`https://review.typo3.org/c/Packages/TYPO3.CMS/+/80513`__.

This conversion applied a :sql:`default 0` to all fields, and did not
evaluate the actual TCA definition for the
:php:`['config']['default']` setting.

This bug has been fixed, and the DB schema analyzer will now convert
all the following fields to their proper default settings:

* :sql:`be_users.options`                                 (0->3)
* :sql:`sys_file_storage.is_browsable`                    (0->1)
* :sql:`sys_file_storage.is_writable`                     (0->1)
* :sql:`sys_file_storage.is_online`                       (0->1)
* :sql:`sys_file_storage.auto_extract_metadata`           (0->1)
* :sql:`sys_file_metadata.visible`                        (0->1)
* :sql:`tt_content.sectionIndex`                          (0->1)
* :sql:`tx_styleguide_palette.palette_1_1`                (0->1)
* :sql:`tx_styleguide_palette.palette_1_3`                (0->1)
* :sql:`tx_styleguide_valuesdefault.checkbox_1`           (0->1)
* :sql:`tx_styleguide_valuesdefault.checkbox_2`           (0->1)
* :sql:`tx_styleguide_valuesdefault.checkbox_3`           (0->5)
* :sql:`tx_styleguide_valuesdefault.checkbox_4`           (0->5)
* :sql:`sys_workspace.edit_allow_notificaton_settings`    (0->3)
* :sql:`sys_workspace.edit_notification_preselection`     (0->2)
* :sql:`sys_workspace.publish_allow_notificaton_settings` (0->3)
* :sql:`sys_workspace.publish_notification_preselection`  (0->1)
* :sql:`sys_workspace.execute_allow_notificaton_settings` (0->3)
* :sql:`sys_workspace.execute_notification_preselection`  (0->3)
* :sql:`sys_workspace_stage.allow_notificaton_settings`   (0->3)
* :sql:`sys_workspace_stage.notification_preselection`    (0->8)

All these records created via :php:`DataHandler` calls actually
interpret the TCA default for record insertion and do not rely
on SQL database field defaults.

Only if records were created using the :php:`QueryBuilder` or
other "raw" database calls, this would cause applying wrong
values.

An example for this is
:php:`TYPO3\CMS\Core\Resource\StorageRepository->createLocalStorage()`
which creates the default :file:`fileadmin` storage record, and would do
that via the :php:`QueryBuilder` and then setting this storage with
the field :sql:`auto_extract_metadata` to :sql:`0` instead of the
TCA expectation of `1`. This would then cause inserted
YouTube files to not automatically fetch metadata on creation.

This means, for all custom extension code that

* removed the column definition in :file:`ext_tables.sql`
  to enforce automatic database field creation,
* *and* did not use the recommended :php:`DataHandler` for
  record insertion (so, any code that is not executed in
  backend context, using :php:`QueryBuilder` or Extbase
  repository methods),
* *and* expects a different default than :sql:`0` for newly
  created records,
* *and* relied on the database field definition default

may have created wrong database records when used between
TYPO3 v13.0 and 13.2.

For TYPO3 core code, this has only affected:

* Default file storage creation, field :sql:`sys_file_metadata.auto_extract_metadata`
* Default backend user creation (admin) property :sql:`be_users.options`

In this rare case, the database record integrity needs to be
manually evaluated, because there is no automation available
to see if a record has used SQL default values or specifically
defined values.

.. index:: Database, ext:core

```

</details>

**Comment by garvinhicking** [comment]
I would argue we shouldn't document this in main, and doesnt affect v12.
