### ISSUE TITLE
[TASK] Deprecate namespaced shorthand validator usage in extbase

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#924]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/d10e1bc04b31d863b1fb20c733c80f87f9cece74)
:busts_in_silhouette: Authored by Torben Hansen derhansen@gmail.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[TASK] Deprecate namespaced shorthand validator usage in extbase

It is possible to use the namespaced shorthand notation in extbase
to add validators for properties or arguments. As an example,
`TYPO3.CMS.Extbase:NotEmpty` will be resolved as
`TYPO3\CMS\Extbase\Validation\Validator\NotEmptyValidator` or
`Vendor.Extension:Custom` will be resolved as
`\Vendor\MyExtension\Validation\Validator\CustomValidator`.

The namespaced shorthand notation for extbase validators has
however never been documented and is rarely used in extensions.

This change deprecates the usage of the namespaced shorthand
notation for validators in extbase.

Resolves: #103965
Releases: main
Change-Id: I787401cc3271cc54fed5c875a27cfde545b4e6dc
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84477
Tested-by: core-ci <typo3@b13.com>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Benni Mack <benni@typo3.org>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>13.2/Deprecation-103965-DeprecateNamespacedShorthandValidatorUsageInExtbase.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-103965-1717335369:

================================================================================
Deprecation: #103965 - Deprecate namespaced shorthand validator usage in extbase
================================================================================

See :issue:`103965`

Description
===========

It is possible to use the undocumented namespaced shorthand notation in extbase
to add validators for properties or arguments. As an example,
:php:`TYPO3.CMS.Extbase:NotEmpty` will be resolved as
:php:`TYPO3\CMS\Extbase\Validation\Validator\NotEmptyValidator` or
:php:`Vendor.Extension:Custom` will be resolved as
:php:`\Vendor\MyExtension\Validation\Validator\CustomValidator`.

The namespaced shorthand notation for extbase validators has been marked as
deprecated and will be removed in TYPO3 v14.


Impact
======

Using namespaced shorthand notation in extbase will trigger a PHP deprecation
warning.


Affected installations
======================

All installations using namespaced shorthand notation in extbase are affected.


Migration
=========

Extensions using the namespaced shorthand notation must use the FQCN of the
validator instead. In case of extbase core validators, the well known
shorthand validator name can be used.

Before
------

..  code-block:: php

    /**
     * @Extbase\Validate("TYPO3.CMS.Extbase:NotEmpty")
     */
    protected $myProperty1;

    /**
     * @Extbase\Validate("Vendor.Extension:Custom")
     */
    protected $myProperty2;


After
-----

..  code-block:: php

    /**
     * @Extbase\Validate("NotEmpty")
     */
    protected $myProperty1;

    /**
     * @Extbase\Validate("Vendor\Extension\Validation\Validator\CustomValidator")
     */
    protected $myProperty2;

or

..  code-block:: php

    #[Extbase\Validate(['validator' => \TYPO3\CMS\Extbase\Validation\Validator\NotEmptyValidator::class])]
    protected $myProperty1;

    #[Extbase\Validate(['validator' => \Vendor\Extension\Validation\Validator\CustomValidator::class])]
    protected $myProperty2;

.. index:: Frontend, NotScanned, ext:extbase

```

</details>

**Comment by linawolf** [comment]
This was never documented
