### ISSUE TITLE
[TASK] Render meta tag twitter:card only if required

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#935]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f896c3df6a75ca35ce5da69f5ddb30dc75d6d768)
:busts_in_silhouette: Authored by Georg Ringer georg.ringer@gmail.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[TASK] Render meta tag twitter:card only if required

Instead of rendering the tag meta tag `twitter:card` always it is now
only rendered if either one of the twitter fields is filled or
the twitter card attribute is selected in the page record.

Additionally the default value is now set to an empty string

This leads to one markup line less for most of the pages.

Resolves: #101621
Releases: main
Change-Id: I55061debc4425d8c2207efec7ee5c5d376a83ca3
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84622
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>13.2/Important-101621-ChangedDefaultValueForTwitter_cardField.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-101621-1718125029:

=================================================================
Important: #101621 - Changed default value for twitter_card field
=================================================================

See :issue:`101621`

Description
===========

The default value of the field `twitter_card` of a page is now an empty string instead of `summary`.

Only if one of the following fields is filled, the meta tag :html:`<meta name="twitter:card">` is rendered.

- `twitter_title`
- `twitter_description`
- `twitter_image`
- `twitter_card`

If no twitter card is selected, the fallback value is `summary`.

.. index:: Frontend, ext:seo

```

</details>

**Comment by linawolf** [comment]
Not menutioned
