### ISSUE TITLE
[FEATURE] Auto create DB fields from TCA for type "input"

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#937]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/ee2d3c6db3e193c2ff8c22e6f20d5519c51ae4d2)
:busts_in_silhouette: Authored by Christian Kuhn lolli@schwarzbu.ch
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[FEATURE] Auto create DB fields from TCA for type "input"

Tables with TCA columns set to type="input" do not
need an ext_tables.sql entry anymore. The core now
creates this field automatically.

This is one of many patches in this area: The v13 goal
is to obsolete ext_tables.sql in most cases by
creating default "business" fields of TCA tables
automatically.

The patch adds the main magic in class DefaultTcaSchema
and removes own ext_tables.sql definitions having
type=input.

Resolves: #102279
Related: #101553
Releases: main
Change-Id: Ia371638bb10d0521cec01542e3a5fc7a364609f1
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83183
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_division_sign: Modified files

<details>
<summary>13.0/Feature-101553-Auto-createDBFieldsFromTCAColumns.rst</summary>

```diff
@@ -94,6 +94,7 @@ Columns are auto-created for these TCA :php:`columns` types:
 * :php:`type = 'inline'` - new with Core v13
 * :php:`type = 'number'` - new with Core v13
 * :php:`type = 'select'` - new with Core v13
+* :php:`type = 'input'` - new with Core v13
 
 See :ref:`Breaking: DateTime column definitions <breaking-99937-1691166389>`
 for a change in the :sql:`datetime` column definition calculation.
```

</details>

**Comment by brotkrueml** [comment]
Also consider https://review.typo3.org/c/Packages/TYPO3.CMS/+/84774
