### ISSUE TITLE
[TASK] Deprecate `Utility.updateQueryStringParameter()`

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#948]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/0b76d64760c24b3f4110df5ef5299cbbeb960797)
:busts_in_silhouette: Authored by Andreas Kienast a.fernandez@scripting-base.de
:heavy_check_mark: Merged by Andreas Kienast a.fernandez@scripting-base.de

## Commit message

[TASK] Deprecate `Utility.updateQueryStringParameter()`

The method `Utility.updateQueryStringParameter()` from the module
`@typo3/backend/utility.js` was introduced in TYPO3 v8 as a bugfix for
highlighting in the old ExtJS-based page tree. With removal of ExtJS in
TYPO3 v9, the method became unused since then.

Since a safe removal of the method cannot be guaranteed as this point,
it is therefore deprecated.

Resolves: #104154
Related: #74180
Releases: main
Change-Id: I90f0ff4c997ab31d690ff6f518f38ffb186058dd
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84786
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Jasmina Ließmann <minapokhalo+typo3@gmail.com>
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Andreas Kienast <a.fernandez@scripting-base.de>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Jasmina Ließmann <minapokhalo+typo3@gmail.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.2/Deprecation-104154-DeprecateUtilityupdateQueryStringParameter.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-104154-1718802119:

=====================================================================
Deprecation: #104154 - Deprecate Utility.updateQueryStringParameter()
=====================================================================

See :issue:`104154`

Description
===========

The method :js:`Utility.updateQueryStringParameter()` from the module
:js:`@typo3/backend/utility.js` was introduced in TYPO3 v8 as a bugfix for
highlighting in the old ExtJS-based page tree. With removal of ExtJS in TYPO3 v9,
the method became unused since then.

Since a safe removal of the method cannot be guaranteed as this point, it is
therefore deprecated.


Impact
======

Calling :js:`Utility.updateQueryStringParameter()` will result in a JavaScript
warning.


Affected installations
======================

All 3rd party extensions using the deprecated method are affected.


Migration
=========

Nowadays, JavaScript supports the :js:`URL` and its related :js:`URLSearchParams`
object that can be used to achieve the same result:

..  code-block:: javascript

    const url = new URL('http://localhost?baz=baz');
    url.searchParams.set('baz', 'bencer');
    const urlString = url.toString(); // http://localhost?baz=bencer

.. index:: JavaScript, NotScanned, ext:backend

```

</details>

**Comment by linawolf** [comment]
Was never mentioned
