### ISSUE TITLE
[TASK] Provide lib.parseFunc via ext:frontend

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#954]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/a0797b5a5b4e6061ec17d2b28b7473c73c66153c)
:busts_in_silhouette: Authored by Benjamin Kott benjamin.kott@outlook.com
:heavy_check_mark: Merged by Benjamin Kott benjamin.kott@outlook.com

## Commit message

[TASK] Provide lib.parseFunc via ext:frontend

Move lib.parseFunc to EXT:frontend in order to allow
fluid_styled_content to become optional at some point.

Resolves: #103485
Releases: main
Change-Id: I8c60c15cea86d5fe784b213a5a2f4ae87ba6a06a
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83321
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benjamin Kott <benjamin.kott@outlook.com>
Reviewed-by: Benjamin Kott <benjamin.kott@outlook.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.2/Important-103485-ProvideLibparseFuncViaExtfrontend.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-103485-1718964758:

===========================================================
Important: #103485 - Provide lib.parseFunc via ext:frontend
===========================================================

See :issue:`103485`

Description
===========

The :typoscript:`lib.parseFunc` and :typoscript:`lib.parseFunc_RTE` functions
render HTML from Rich Text Fields of TYPO3. While direct interaction with these
libraries is now uncommon, they control output of the :html:`<f:format.html>`
ViewHelper.

Previously, the libraries were available only through content rendering definitions
like fluid_styled_content, the bootstrap_package or your own.

The :html:`<f:format.html>` ViewHelper requires a parseFunc to function and
will throw an exception if none is provided. With the shift towards
self-contained content elements, also known as content blocks, the need to
include a separate rendering definition is eliminated. The frontend now
provides a base version of the libraries, which are now always available in
the frontend context.

The libraries, are loaded early in the TypoScript chain, ensuring that all
existing overrides continue to work as before, without the need for a basic
parseFunc definition.

.. index:: Frontend, TypoScript, ext:frontend

```

</details>

**Comment by linawolf** [comment]
No need to document
