### ISSUE TITLE
[FEATURE] Update Fluid Standalone to 2.12

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#956]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/52ab3c4cafa37d61d19be04b0625072184d0cc51)
:busts_in_silhouette: Authored by Simon Praetorius simon@praetorius.me
:heavy_check_mark: Merged by Simon Praetorius simon@praetorius.me

## Commit message

[FEATURE] Update Fluid Standalone to 2.12

This patch updates Fluid to the latest version. It also
adds a RST file which describes the new ViewHelper capabilities
that were added with 2.12.

Executed command: composer req typo3fluid/fluid:^2.12.0

Resolves: #103560
Releases: main
Change-Id: I24edbc6552e05779dfbea0157b0184799bff6f6b
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84931
Tested-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Simon Praetorius <simon@praetorius.me>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_plus_sign: Added files

<details>
<summary>13.2/Feature-104223-UpdateFluidStandaloneTo212.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-104223-1719417803:

==================================================
Feature: #104223 - Update Fluid Standalone to 2.12
==================================================

See :issue:`104223`

Description
===========

Fluid Standalone has been updated to version 2.12. This version adds new capabilities for
TagBasedViewHelpers as well as a new ViewHelper. The introduced XSD Schema Generator will
be adapted to TYPO3's Fluid integration in a separate patch.


Impact
======

All TagBasedViewHelpers (such as :html:`<f:image />` or :html:`<f:form.*>`) can now receive
arbitrary tag attributes which will be appended to the resulting HTML tag. In the past,
this was only possible for a small list of tag attributes, like class, id or lang.

.. code-block:: html

    <f:form.textfield inputmode="tel" />
    <f:image image="{image}" hidden="hidden" />

A :html:`<f:constant>` ViewHelper has been added to be able to access PHP constants from
Fluid templates:

.. code-block:: html

    {f:constant(value: 'PHP_INT_MAX')}
    {f:constant(value: '\Vendor\Package\Class::CONSTANT')}
    {f:constant(value: '\Vendor\Package\Enum::CASE')}

.. index:: Fluid, Frontend, ext:fluid

```

</details>

**Comment by linawolf** [comment]
Will be documented automatically
