### ISSUE TITLE
[FEATURE] Command to generate Fluid schema files

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#960]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/7f68e0a644c60b673db3cf2efa4667ca518f8a76)
:busts_in_silhouette: Authored by Simon Praetorius simon@praetorius.me
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[FEATURE] Command to generate Fluid schema files

The XSD schema generator, added with Fluid Standalone 2.12,
is applied to TYPO3's Fluid integration. This provides
autocompletion for supporting IDEs (like PhpStorm) by executing
the CLI command added with this patch.

Resolves: #104114
Releases: main
Change-Id: Id9f996820483e5af21506cdde2221b2be65a38d8
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/84720
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>13.2/Feature-104114-CommandToGenerateFluidSchemaFiles.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-104114-1719419341:

=========================================================
Feature: #104114 - Command to generate Fluid schema files
=========================================================

See :issue:`104114`

Description
===========

With Fluid Standalone 2.12, a new implementation of the XSD schema generator has
been introduced, which was previously a separate composer package. These XSD files
allow IDEs to provide autocompletion for ViewHelper arguments in Fluid templates,
provided that they are included in the template by using the xmlns syntax:

.. code-block:: html

    <html
        xmlns:f="http://typo3.org/ns/TYPO3/CMS/Fluid/ViewHelpers"
        xmlns:my="http://typo3.org/ns/Vendor/MyPackage/ViewHelpers"
        data-namespace-typo3-fluid="true"
    >

A new CLI command has been defined to apply Fluid's new schema generator to TYPO3's
Fluid integration. New Fluid APIs are used to find all ViewHelpers that exist in
the current project (based on the composer autoloader). Then, TYPO3's configuration
is checked for any merged Fluid namespaces (like `f:`, which consists of both
Fluid Standalone and EXT:fluid ViewHelpers which in some cases override each other).

After that consolidation, `*.xsd` files are created in `var/transient/` using another
API from Fluid Standalone. These files which will automatically get picked up by
supporting IDEs (like PhpStorm) to provide autocompletion in template files.


Impact
======

To get autocompletion for all available ViewHelpers in supporting IDEs, the following
CLI command can be executed in local development environments:

::
    vendor/bin/typo3 fluid:schema:generate

.. index:: CLI, Fluid, ext:fluid

```

</details>

**Comment by linawolf** [comment]
Does not need to be documented
