### ISSUE TITLE
[TASK] Deprecate BackendUtility::getTcaFieldConfiguration

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#964]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/5fc077b6fe86fc1815c7e9fbbdbf6f7f56f324fa)
:busts_in_silhouette: Authored by Benni Mack benni@typo3.org
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[TASK] Deprecate BackendUtility::getTcaFieldConfiguration

The method getTcaFieldConfiguration is the first
to fall in BackendUtility as we now have a new
API for accessing information from TCA.

The last pieces have been migrated.

Historical fun fact: This method was introduced
with TYPO3 4.x to add support for IRRE in Workspaces
in 2010 by ohader:
"Add feature #16374: Implement Inline Relational Record Editing (IRRE) in Workspaces"

Kudos for this tremendous effort.

Resolves: #104304
Related: #104002
Related: #16374
Releases: main
Change-Id: I5c38592777ca4ee64e5a9155e338e17322ae452c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85100
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Deprecation-104304-BackendUtilitygetTcaFieldConfiguration.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-104304-1720084447:

===============================================================
Deprecation: #104304 - BackendUtility::getTcaFieldConfiguration
===============================================================

See :issue:`104304`

Description
===========

The method :php:`BackendUtility::getTcaFieldConfiguration` was introduced back
in 2010 to add a simple abstraction to access "TCA" definitions of a field.

However, apart from the set up that it is not part of a flexible API without
knowing the context, it was used seldom in TYPO3 Core.

The method has now been deprecated, as one could and can easily write the same
PHP code with :php:`$GLOBALS['TCA']` in mind already (which Core already did
in several other places).

Now that Schema API was introduced, the last parts have been migrated to use
the new API.


Impact
======

Calling the PHP method :php:`BackendUtility::getTcaFieldConfiguration` will
trigger a PHP deprecation warning.


Affected installations
======================

TYPO3 installations with custom extensions using this method.


Migration
=========

Either access :php`$GLOBALS['TCA']` directly (in order to support TYPO3 v12 and TYPO3 v13),
or migrate to the new Schema API:

.. code-block:: php

    public function __construct(
        private readonly TcaSchemaFactory $tcaSchemaFactory
    ) {}

    private function getFieldConfiguration(string $table, string $fieldName): array
    {
        return $this->tcaSchemaFactory
            ->get($table)
            ->getField($fieldName)
            ->getConfiguration();
    }

.. index:: PHP-API, TCA, FullyScanned, ext:backend

```

</details>

**Comment by linawolf** [comment]
Was never mentioned
