### ISSUE TITLE
[DOCS] Add example for multiple RTE CSS classes

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#965]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/907449f107aee13e0c9e49eb2b6a510f345483b2)
:busts_in_silhouette: Authored by Guido Schmechel guido.schmechel@brandung.de
:heavy_check_mark: Merged by Georg Ringer georg.ringer@gmail.com

## Commit message

[DOCS] Add example for multiple RTE CSS classes

An example for the addition of multiple CSS classes to
editor.config.style will be added to the existing RST files.

Resolves: #104310
Releases: main, 12.4
Change-Id: I8a77aae8c402608857b3b7ea690da23f4f8134c6
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85107
Tested-by: Torben Hansen <derhansen@gmail.com>
Reviewed-by: Torben Hansen <derhansen@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Georg Ringer <georg.ringer@gmail.com>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Feature-96874-CKEditor5.rst</summary>

```diff
@@ -113,6 +113,7 @@ from `editor.config.wordcount` to `editor.config.wordCount`:
           definitions:
             # block level styles
             - { name: "Lead", element: "p", classes: ['lead'] }
+            - { name: "Multiple", element: "p", classes: ['first', 'second'] }
             - { name: "Small", element: "small", classes: [] }
             # Inline styles
             - { name: "Muted", element: "span", classes: ['text-muted'] }
```

</details>

**Comment by Alagts** [comment]
It is already documented here: https://docs.typo3.org/c/typo3/cms-rte-ckeditor/main/en-us/Configuration/Reference.html .
