### ISSUE TITLE
[FEATURE] Combine be_groups table permission read & write UI

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#966]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/6a172f676fda8284629b454b36804af0bd4c9853)
:busts_in_silhouette: Authored by Marcin Sągol marcin@soee.pl
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[FEATURE] Combine be_groups table permission read & write UI

The `tables_select` and `tables_modify` lists have the same
items listed, so instead of managing them through separate
views, the merges them into a single view.

The new (merged) table renders the three options "No Access",
"Read" and "Read & Write" for each table. Those options are
accompanied by the multi record selection options to
"Check All", "Uncheck All" and to "Toggle Selection".

To render this new table view and handle its behavior, a
dedicated form renderType `tablePermission` is introduced, which
is now set for the `tables_modify` column. The `tables_select`
column has been changed to TCA type `passthrough`.

The new form element is defined through:
`\TYPO3\CMS\Backend\Form\Element\TablePermissionElement`.
It uses a dedicated data provider defined in:
`\TYPO3\CMS\Backend\Form\FormDataProvider\TcaTablePermission`.
The JavaScript code is handled by a new web component:
`@typo3/backend/form-engine/element/table-permission-element.js`.

When the TcaTablePermission data provider handles the
configuration, it reads table lists from both the `tables_select`
and `tables_modify` columns and combines them into a single array
with unique table names.

Resolves: #103521
Releases: main
Change-Id: Iae468d9209d346ef09fd34053cdcd2d1a8ef1f2c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83743
Reviewed-by: Marcin Sągol <marcin@soee.pl>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Marcin Sągol <marcin@soee.pl>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Feature-103521-ChangeTableRestrictionsUiToCombineReadAndWritePermissions.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-103521-1718028096:

=====================================================================================
Feature: #103521 - Change table restrictions UI to combine read and write permissions
=====================================================================================

See :issue:`103521`

Description
===========

The `tables_select` and `tables_modify` fields of the `be_groups` table store
information about permissions to read and write into selected database tables.

Due to TYPO3's internal behavior, when write permissions are granted for some
tables, those tables are also automatically available for reading.

To make managing table permissions much easier and more efficient for
integrators, the separate form fields for `Tables (listing) [tables_select]` and
`Tables (modify) [tables_modify]` have been combined into a single UI element.
This field now offers separate radio buttons to define which tables the backend
user group should have permission to read and / or write. This is done by
selecting one of the "No Access", "Read" or "Read & Write" options.

To further improve the user experience, it's also possible to use the
"Check All", "Uncheck All" and "Toggle Selection" options for each permission.

Under the hood, when these permissions are processed, they are still saved
separately in the `tables_select` and `tables_modify` columns in the
`be_groups` table, as they were before.

To render this new table view and handle its behavior, a dedicated form
renderType `tablePermission` has been introduced, which is now set for
the `tables_modify` column. The `tables_select` column has been changed
to TCA type `passthrough`.

The new form element is defined through:
:php:`\TYPO3\CMS\Backend\Form\Element\TablePermissionElement`.
It uses a dedicated data provider defined in:
:php:`\TYPO3\CMS\Backend\Form\FormDataProvider\TcaTablePermission`.
The JavaScript code is handled by a new web component:
:js:`@typo3/backend/form-engine/element/table-permission-element.js`.

When the `TcaTablePermission` data provider handles the configuration, it
reads table lists from both the `tables_select` and `tables_modify`
columns and combines them into a single array with unique table names.

Impact
======

Managing table permissions for backend user groups has been improved by
visually combining the `Tables (listing) [tables_select]` and
`Tables (modify) [tables_modify]` options, as well as by adding the
multi record selection functionality.

.. note::

    These changes might affect custom integrations and modifications made to
    the `tables_select` or `tables_modify` columns in the `be_groups` TCA.
    Integrators who have modified the configuration for these fields should
    verify if their code works and adapt it if needed.

.. index:: Backend, JavaScript, PHP-API, TCA, ext:core

```

</details>

**Comment by linawolf** [comment]
No need to document
