### ISSUE TITLE
[DOCS] Properly refer to "loadJavaScriptModule" in Changelog

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#971]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/c688a76749ab677d4d94d34ba5a474716e778906)
:busts_in_silhouette: Authored by Garvin Hicking gh@faktor-e.de
:heavy_check_mark: Merged by Georg Ringer georg.ringer@gmail.com

## Commit message

[DOCS] Properly refer to "loadJavaScriptModule" in Changelog

The Changelog mistakenly referred to
"PageRenderer::loadJavaScriptModules"
(even though the example code itself was right).

To avoid confusion of the method not being static, the notation is
also changed from "::" to "->" to indicate a non-static class member
method.

Resolves: #104428
Releases: main, 12.4
Change-Id: I82827590ea2c852522b487986ff95159204b5b70
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85290
Tested-by: Andreas Kienast <a.fernandez@scripting-base.de>
Reviewed-by: Andreas Kienast <a.fernandez@scripting-base.de>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: core-ci <typo3@b13.com>

## :heavy_division_sign: Modified files

<details>
<summary>12.0/Deprecation-97057-DeprecateRequireJSSupport.rst</summary>

```diff
@@ -49,7 +49,8 @@ Migrate your JavaScript from the AMD module format to native ES6 modules and reg
         ],
     ];
 
-Then use :php:`TYPO3\CMS\Core\Page\PageRenderer::loadJavaScriptModules()` instead of :php:`TYPO3\CMS\Core\Page\PageRenderer::loadRequireJsModule()` to load the ES6 module:
+Then use :php:`TYPO3\CMS\Core\Page\PageRenderer->loadJavaScriptModule()` instead of
+:php:`TYPO3\CMS\Core\Page\PageRenderer->loadRequireJsModule()` to load the ES6 module:
 
 .. code-block:: php
 
```

</details>

<details>
<summary>13.0/Breaking-101266-RemoveRequireJS.rst</summary>

```diff
@@ -24,8 +24,8 @@ Impact
 
 Registering FormEngine JavaScript modules via :php:`'requireJsModules'` will
 have no effect. The PageRenderer endpoints
-:php:`\TYPO3\CMS\Core\Page\PageRenderer::loadRequireJs()` and
-:php:`\TYPO3\CMS\Core\Page\PageRenderer::loadRequireJsModule()`
+:php:`\TYPO3\CMS\Core\Page\PageRenderer->loadRequireJs()` and
+:php:`\TYPO3\CMS\Core\Page\PageRenderer->loadRequireJsModule()`
 have been removed and must no longer be called.
 The respective :html:`includeJavaScriptModules` property of the ViewHelper
 :html:`<f:be.pageRenderer>` ViewHelper has also been removed.
@@ -59,8 +59,8 @@ for more information:
         ],
     ];
 
-Then use :php:`\TYPO3\CMS\Core\Page\PageRenderer::loadJavaScriptModules()` instead
-of :php:`\TYPO3\CMS\Core\Page\PageRenderer::loadRequireJsModule()` to load the ES6 module:
+Then use :php:`\TYPO3\CMS\Core\Page\PageRenderer->loadJavaScriptModule()` instead
+of :php:`\TYPO3\CMS\Core\Page\PageRenderer->loadRequireJsModule()` to load the ES6 module:
 
 .. code-block:: php
 
```

</details>

**Comment by linawolf** [comment]
No need to document
