### ISSUE TITLE
[FEATURE] Allow static routes to assets

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#974]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/09f492cf44561238b35ce1578cff09ed118d88a8)
:busts_in_silhouette: Authored by Georg Ringer georg.ringer@gmail.com
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[FEATURE] Allow static routes to assets

Provide a new type of static routes `assets` to expose assets shipped
by extensions.

Resolves: #101472
Releases: main
Change-Id: I46d5b8af795b1037c6a3e2554454df6a6e7174ea
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85268
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Feature-101472-AllowStaticRoutesToAssets.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-101472-1721137289:

================================================
Feature: #101472 - Allow static routes to assets
================================================

See :issue:`101472`

Description
===========

It is now possible to configure static routes with the type `asset` to link to
resources which are typically located in the directory
:file:`EXT:my_extension/Resources/Public/`.

.. code-block:: yaml

    routes:
      -
        route: example.svg
        type: asset
        asset: 'EXT:backend/Resources/Public/Icons/Extension.svg'

Impact
======

Static routes to files shipped with extensions can now be configued in the site configuration.

.. index:: Frontend, YAML, ext:frontend

```

</details>

**Comment by garvinhicking** [comment]
Re-opening this one, if the followup https://review.typo3.org/c/Packages/TYPO3.CMS/+/85570 is merged, to document that site-specific assets are possible

**Comment by linawolf** [comment]
Follow-Up is merged and has its own ticket: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/988
