### ISSUE TITLE
[TASK] Use ext:core ViewInterface in extbase

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#976]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/66cdc96392548201209e4b042ea84902f41a54dc)
:busts_in_silhouette: Authored by Hannes Lau office@hanneslau.de
:heavy_check_mark: Merged by Benni Mack benni@typo3.org

## Commit message

[TASK] Use ext:core ViewInterface in extbase

TYPO3 v12 added a new ViewInterface to ext:core that allows
implementing *any* view as long as it sticks to this interface.

This interface has been put into use for all backend modules,
combined with a factory that allows to set custom stuff per module.

Extbase however has not been touched: Extbase is still
tailored towards ext:fluid and Fluid standalone.

The patch changes this by adapting the Extbase related views towards
ext:core ViewInterface. This allows implementing "own" views not
depending on Fluid standalone.

The patch has to hop through quite some loops to allow this:

ext:core FluidViewAdapter is a class implemented in v12 that
is a facade between core views and Fluid. Unfortunatly,
extbase uses some "specialities" like "renderPartial()" from
Fluid, which ext:core ViewInterface does not implement. We
can not get rid of those within extbase any time soon. As such,
FluidViewAdapter now implements all the nasty details that
Fluid provides: FluidViewAdapter is now the main class between
extbase and Fluid views - it implements both the Fluid view
interface, plus ext:core ViewInterface. FluidViewAdapter in
itself is rather simple: It only holds the Fluid view instance.
Historically, many further operations were possible on
Fluid view classes, those were only wrappers around
RenderingContext, though. To keep backwards compatibility,
FluidViewAdapter now re-implements all these methods, but
deprecates them.

In addition to ext:core ViewInterface, FluidViewAdapter will continue
to implement getRenderingContext(), setRenderingContext() (probably),
renderSection() and renderPartial(). All other methods that are
wrappers around details of RenderingContext are marked @deprecatded.
Systems that need to work with details of Fluid, now need to test
for an instance of FluidViewAdapter to manipulate setRenderingContext
if needed.

This strategy will allow us to phase out ext:fluid StandaloneView and
ext:fluid TemplateView with further patches, which will further
simplify the layer towards Fluid standalone.

Within Extabse, the main view interface is now ext:core ViewInterface,
which free's the dependency to Fluid. JsonView is now the primary
example for a view that has no relation to Fluid anymore.

TYPO3 v14 can continue with hardening various type hints related
to views, those have been marked accordingly.

Note the handling related to ServerRequestInterface will see
some additional patches in this area as well.

Resolves: #101559
Related: #96730
Related: #104463
Releases: main
Change-Id: I4be3e6be191b8bce599523a1055fc6136a86a879
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80329
Tested-by: Simon Praetorius <simon@praetorius.me>
Reviewed-by: Simon Praetorius <simon@praetorius.me>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Hannes Lau <office@hanneslau.de>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Benni Mack <benni@typo3.org>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Deprecation-101559-ExtbaseUsesExtcoreViewInterface.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-101559-1721761906:

==========================================================
Deprecation: #101559 - Extbase uses ext:core ViewInterface
==========================================================

See :issue:`101559`

Description
===========

The default view of ext:extbase now returns an view that implements
:php:`TYPO3\CMS\Core\View\ViewInterface` and not only
:php:`TYPO3Fluid\Fluid\View\ViewInterface` anymore. This allows
implementing any view that implements :php:`TYPO3\CMS\Core\View\ViewInterface`,
and free's the direct dependency to Fluid.

The default return object is an instance of
:php:`TYPO3\CMS\Core\View\FluidViewAdapter` which implements all
special methods tailored for Fluid. Extbase controllers should
check for instance of this object before calling these methods,
especially:

* :php:`getRenderingContext()`
* :php:`setRenderingContext()`
* :php:`renderSection()`
* :php:`renderPartial()`

Method calls not being part of :php:`TYPO3\CMS\Core\View\ViewInterface` or the above
listed method names have been marked as deprecated and will be removed in TYPO3 v14.

Impact
======

Extbase controllers that extend :php:`TYPO3\CMS\Extbase\Mvc\Controller\ActionController`
and call methods not part of :php:`TYPO3\CMS\Core\View\ViewInterface`, should
test for :php:`$view instanceof FluidViewAdapter` before calling
:php:`getRenderingContext()`, :php:`setRenderingContext()`, php:`renderSection()`
and :php:`renderPartial()`.

All other Fluid related methods called on :php:`$view` have been marked as
deprecated and will log a deprecation level error message.


Affected installations
======================

Instances with extbase based extensions that call :php:`$view` methods without
testing for :php:`FluidViewAdapter`.


Migration
=========

Methods on "old" Fluid instances were wrapper methods for
:php:`RenderingContext`. Controllers should call :php:`$view->getRenderingContext()`
to perform operations instead.


.. index:: Fluid, PHP-API, NotScanned, ext:extbase

```

</details>

**Comment by s2b** [comment]
Currently, these are only internal changes in the core that will make things possible in the future for other developers. Thus it makes sense to revisit this after the feature freeze if there are more changes in this area until then.

In the current state the core changes are not relevant for end users of the documentation.

**Comment by brotkrueml** [comment]
Closing it. If changes occur to this changelog which is relevant for end users another issue is opened and can then be tackled.
