### ISSUE TITLE
[DOCS] Adjust changelog of opacity option in color element

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#981]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/bfb5d3d5842147d0bb43eb0cb5b137e430c97a9d)
:busts_in_silhouette: Authored by Oliver Bartsch bo@cedev.de
:heavy_check_mark: Merged by Oliver Bartsch bo@cedev.de

## Commit message

[DOCS] Adjust changelog of opacity option in color element

Resolves: #104522
Releases: main
Change-Id: Ie6bac8a670e7c5e10e0b722d7dd8fb7effc469f5
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85438
Tested-by: core-ci <typo3@b13.com>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Oliver Bartsch <bo@cedev.de>
Tested-by: Oliver Bartsch <bo@cedev.de>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Tested-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_division_sign: Modified files

<details>
<summary>13.3/Feature-103576-AllowDefiningOpacityInColorElement.rst</summary>

```diff
@@ -11,8 +11,8 @@ See :issue:`103576`
 Description
 ===========
 
-A new property `opacity` has been added to the TCA configuration of a
-`color`type element to allow defining colors with an opacity using
+A new boolean property `opacity` has been added to the TCA configuration of
+a TCA type `color` element to allow defining colors with an opacity using
 the RRGGBBAA color notation.
 
 ..  code-block:: php
@@ -29,6 +29,7 @@ the RRGGBBAA color notation.
 Impact
 ======
 
-If enabled, editors can select not only a color but also its opacity in a color element.
+If `opacity` is enabled, editors can select not only a color but also its
+opacity in a corresponding color element.
 
 .. index:: TCA, ext:backend
```

</details>

**Comment by linawolf** [comment]
Already documented
