### ISSUE TITLE
[FEATURE] Add base64 attribute to f:image and f:uri.image

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#982]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/132ad7c74429349bf25c997740fddeb6dea3ee33)
:busts_in_silhouette: Authored by CONVERS Sébastien sebastien.convers@agrosupdijon.fr
:heavy_check_mark: Merged by Georg Ringer georg.ringer@gmail.com

## Commit message

[FEATURE] Add base64 attribute to f:image and f:uri.image

Add an option to return the base64 encoded contents of an
image embedded via f:image or f:uri.image, via the new
attribute `base64=true`.

This can be used to prevent additional HTTP calls or to
ease embedding in FluidEmail templates.

Resolves: #101391
Releases: main
Change-Id: I67219af6025f14b6f2859ce9d1951b686a9155da
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/80097
Tested-by: core-ci <typo3@b13.com>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Chris Müller <typo3@brotkrueml.dev>
Reviewed-by: Markus Klein <markus.klein@typo3.org>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Chris Müller <typo3@brotkrueml.dev>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Feature-101391-AddBase64OptionToImageViewHelper.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-101391-1689772689:

==========================================================
Feature: #101391 - Add base64 attribute to ImageViewHelper
==========================================================

See :issue:`101391`

Description
===========

The ViewHelpers :fluid:`<f:image>` and :fluid:`<f:uri.image>` now
support the attribute :xml:`base64="true"` that will provide
a possibility to return the value of the image's :html:`src` attribute
encoded in base64.

..  code-block:: html

    <f:image base64="true" src="EXT:backend/Resources/Public/Images/typo3_logo_orange.svg" height="20" class="pr-2" />
    <img src="{f:uri.image(base64: 'true', src:'EXT:backend/Resources/Public/Images/typo3_logo_orange.svg')}">

Will result in the according HTML tag providing the image encoded in base64.

.. code-block:: html

    <img class="pr-2" src="data:image/svg+xml;base64,PHN2...cuODQ4LTYuNzU3Ii8+Cjwvc3ZnPgo=" alt="" width="20" height="20">
    <img src="data:image/svg+xml;base64,PHN2...cuODQ4LTYuNzU3Ii8+Cjwvc3ZnPgo=">

This can be particularly useful inside `FluidEmail` or to prevent unneeded HTTP calls.

.. index:: Fluid, ext:fluid

```

</details>

**Comment by linawolf** [comment]
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/85664 and https://review.typo3.org/c/Packages/TYPO3.CMS/+/85665
