### ISSUE TITLE
[FEATURE] Enable recycler by default

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#983]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/bf2bd45a3f6eea56033bc834742226dfb2efd390)
:busts_in_silhouette: Authored by Christian Fries hallo@christian-fries.ch
:heavy_check_mark: Merged by Georg Ringer georg.ringer@gmail.com

## Commit message

[FEATURE] Enable recycler by default

Resolves: #99418
Releases: main
Change-Id: Idf1450dd9fe13b98e9f1d204bc1ea6a746f1719d
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85472
Tested-by: core-ci <typo3@b13.com>
Reviewed-by: Benni Mack <benni@typo3.org>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Benni Mack <benni@typo3.org>
Tested-by: Georg Ringer <georg.ringer@gmail.com>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Feature-99418-EnableRecyclerByDefault.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _feature-99418-1722544152:

============================================
Feature: #99418 - Enable recycler by default
============================================

See :issue:`99418`

Description
===========

The TYPO3 core extension `recycler` is now enabled by default for new TYPO3 installations.

Impact
======

New composer-based TYPO3 installations based on the TYPO3 CMS Base Distribution,
and new "classic mode" (tarball / zip download) installations have the core extension `recycler`
enabled by default.

.. index:: Backend, ext:recycler

```

</details>

**Comment by linawolf** [comment]
Must be documented in core: https://forge.typo3.org/issues/104647?

**Comment by linawolf** [comment]
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/85663
