### ISSUE TITLE
[TASK] Allow to disable CSP headers for a  particular site

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#989]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/acf70306c44f9817552bcaae45aafc46b03dc0bf)
:busts_in_silhouette: Authored by Oliver Hader oliver@typo3.org
:heavy_check_mark: Merged by Oliver Hader oliver.hader@typo3.org

## Commit message

[TASK] Allow to disable CSP headers for a  particular site

This change allows to disable CSP headers for a particular site
configured in `sites/<my-site>/csp.yaml` by using the assignment
`enable: false`.

Resolves: #104549
Releases: main, 12.4
Change-Id: I9e17b5658610e5d47915a5e45ca6a33a870e8d76
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85591
Reviewed-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Georg Ringer <georg.ringer@gmail.com>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Georg Ringer <georg.ringer@gmail.com>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>12.4.x/Important-104549-DisableContent-Security-PolicyHeadersForParticularSite.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _important-104549-1723461851:

================================================================================
Important: #104549 - Disable Content-Security-Policy headers for particular site
================================================================================

See :issue:`104549`

Description
===========

The feature flag :php:`$GLOBALS['TYPO3_CONF_VARS']['SYS']['features']['security.frontend.enforceContentSecurityPolicy']`
applies Content-Security-Policy headers to any frontend site. The dedicated :file:`sites/<my-site>/csp.yaml` can be used
to explicitly disable CSP for a particular site.

..  code-block:: yaml
    :caption: config/sites/<my-site>/csp.yaml

    # enables content-security-policy headers for this specific site (enabled per default)
    # (`enable: false` can be used to disable CSP for a particular site)
    enable: false

.. index:: Frontend, YAML, ext:frontend

```

</details>

**Comment by garvinhicking** [comment]
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/85632 - this might be changed later on. Wait a bit :)

**Comment by garvinhicking** [comment]
Was reverted, closing.
