### ISSUE TITLE
[TASK] Properly deprecate the check for the SiteLanguageAwareTrait

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#99]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/24c5372ad91412e1890f896a3bfce690227517ef)
:busts_in_silhouette: Authored by Oliver Klee typo3-coding@oliverklee.de
:heavy_check_mark: Merged by Stefan Bürk stefan@buerk.tech

## Commit message

[TASK] Properly deprecate the check for the SiteLanguageAwareTrait

In #87380, it was recommended to use the `SiteLanguageAwareInterface`
instead of the `SiteLanguageAwareTrait` for marking classes as site
language aware. The usage of the trait for this was never properly
deprecated - it was only marked as "at any time after TYPO3 v11",
which is not specific enough.

The proper deprecation is now done so the check for the trait can
be removed for TYPO3 v13.

Resolves: #97435
Related: #87380
Releases: main
Change-Id: I6e8d130b295d4dc3f69639b4fa0e13d6b73f1040
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/74361
Tested-by: core-ci <typo3@b13.com>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Stefan Bürk <stefan@buerk.tech>
Reviewed-by: Simon Schaufelberger <simonschaufi+typo3@gmail.com>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Stefan Bürk <stefan@buerk.tech>

## :heavy_plus_sign: Added files

<details>
<summary>12.0/Deprecation-97435-UsageOfSiteLanguageAwareTraitToDenoteSiteLanguageAwareness.rst</summary>

```rst
.. include:: /Includes.rst.txt

=======================================================================================
Deprecation: #97435 - Usage of SiteLanguageAwareTrait to denote site language awareness
=======================================================================================

See :issue:`97435`

Description
===========

The :php:`TYPO3\CMS\Core\Site\SiteLanguageAwareTrait` should not be used as
means to denote a class as aware of the site language anymore. Instead, the
:php:`TYPO3\CMS\Core\Site\SiteLanguageAwareInterface` should be implemented for
this purpose. The trait is an internal implementation and should not be used
in user land code.

Impact
======

If you are currently using the :php:`SiteLanguageAwareTrait` to denote a class
as aware of the site language, you should implement the
:php:`SiteLanguageAwareInterface` instead.

Affected Installations
======================

All installations where the :php:`SiteLanguageAwareTrait` is used to denote
a class as aware of the site language.

Migration
=========

Change classes that use the :php:`SiteLanguageAwareTrait` but not the
corresponding interface to implement the interface. Replace the usage of the
trait with an own trait, or implement the interface methods directly in the
class.

Example before the migration:

.. code-block:: php

    use TYPO3\CMS\Core\Site\SiteLanguageAwareTrait;

    class MyClass
    {
        use SiteLanguageAwareTrait;
    }

Example after the migration:

.. code-block:: php

    use TYPO3\CMS\Core\Site\SiteLanguageAwareInterface;
    use TYPO3\CMS\Core\Site\Entity\SiteLanguage;

    class MyClass implements SiteLanguageAwareInterface
    {

        protected SiteLanguage $siteLanguage;

        public function setSiteLanguage(SiteLanguage $siteLanguage)
        {
            $this->siteLanguage = $siteLanguage;
        }

        public function getSiteLanguage(): SiteLanguage
        {
            return $this->siteLanguage;
        }
    }

.. index:: PHP-API, ext:core, NotScanned

```

</details>

**Comment by linawolf** [comment]
The SiteLanguageAwareTrait was never mentioned
