### ISSUE TITLE
[TASK] Deprecate `BackendUserAuthentication::returnWebmounts()`

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#991]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/f8ccd5c5a298161260e762141fcdfbbf44db74f1)
:busts_in_silhouette: Authored by Thomas Hohn tho@gyldendal.dk
:heavy_check_mark: Merged by Christian Kuhn lolli@schwarzbu.ch

## Commit message

[TASK] Deprecate `BackendUserAuthentication::returnWebmounts()`

TYPO3 has a method to retrieve webmounts
`BackendUserAuthentication::returnWebmounts()`.
The method returns the uid's of the webmounts as an array
of strings. A more suitable representation is an array of
integers.

A new method `BackendUserAuthentication::getWebmounts()` has
been introduced with #104591 that returns a list of integers.
With #104614 it is additionally ensured that the call to the method
BackendUserAuthentication::getWebmounts() returns an unique list
of webmounts. Superfluous calls to array_unique() can be removed.

The patch deprecates `BackendUserAuthentication::returnWebmounts()`.

Resolves: #104607
Related: #104591
Related: #104614
Releases: main
Change-Id: Id9b870a85538a9aeb74de3034136c4e3076480ea
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85618
Reviewed-by: Christian Kuhn <lolli@schwarzbu.ch>
Tested-by: Garvin Hicking <gh@faktor-e.de>
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: core-ci <typo3@b13.com>
Tested-by: Christian Kuhn <lolli@schwarzbu.ch>

## :heavy_plus_sign: Added files

<details>
<summary>13.3/Deprecation-104607-BackendUserAuthenticationReturnWebmounts.rst</summary>

```rst
.. include:: /Includes.rst.txt

.. _deprecation-104607-1723556132:

==================================================================
Deprecation: #104607 - BackendUserAuthentication:returnWebmounts()
==================================================================

See :issue:`104607`

Description
===========

Method :php:`BackendUserAuthentication::returnWebmounts()` has
been marked as deprecated and will be removed with TYPO3 v14.

Method :php:`BackendUserAuthentication::getWebmounts()` was
introduced as substitution. It returns an unique list of integer uids
instead of a list of strings, which is more type safe.
Superfluous calls to array_unique() can be removed since the uniqueness
is now guaranteed by BackendUserAuthentication::getWebmounts().

Impact
======

Calling :php:`BackendUserAuthentication::returnWebmounts()` will trigger a PHP
deprecation warning.


Affected installations
======================

All installations using :php:`BackendUserAuthentication::returnWebmounts()`
are affected.


Migration
=========

Existing calls to  :php:`BackendUserAuthentication::returnWebmounts()` should
be replaced by :php:`BackendUserAuthentication::getWebmounts()`.

If third party extensions convert the previous result array from an array of
strings to an array of integers, this can be skipped. In addition
superfluous calls to array_unique() can be removed since the uniqueness
is now guaranteed by BackendUserAuthentication::getWebmounts().

.. index:: PHP-API, TCA, FullyScanned, ext:core

```

</details>

**Comment by linawolf** [comment]
Has never been mentioned
