### ISSUE TITLE
[TASK] Revert "[TASK] Allow to disable CSP headers for a  particular site"

### ISSUE THREAD

**Issue by TYPO3IncTeam** [TYPO3-Documentation/Changelog-To-Doc#992]
:information_source: View this commit [on Github](https://github.com/TYPO3/typo3/commit/a58562617ab681cd69db2a199c802bca577439ad)
:busts_in_silhouette: Authored by Oliver Hader oliver@typo3.org
:heavy_check_mark: Merged by Oliver Hader oliver.hader@typo3.org

## Commit message

[TASK] Revert "[TASK] Allow to disable CSP headers for a  particular site"

Aims to combine disabling site-specific CSP with report-only mode later.

This reverts commit acf70306c44f9817552bcaae45aafc46b03dc0bf.

Reverts: #104549
Resolves: #104633
Releases: main, 12.4
Change-Id: I651f60d7b5cc24133801412c8f09b1efba98d3f4
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85646
Reviewed-by: Garvin Hicking <gh@faktor-e.de>
Tested-by: Oliver Hader <oliver.hader@typo3.org>
Reviewed-by: Oliver Hader <oliver.hader@typo3.org>
Tested-by: Garvin Hicking <gh@faktor-e.de>

**Comment by garvinhicking** [comment]
Closed, was not documented yet and waiting for future PR.
